### ISSUE TITLE
database.executeSql calls its success callback twice 

### ISSUE THREAD

**Issue by Typhlosaurus** [brody2consult/cordova-sqlite-storage#111]
The database.executeSql method is implemented in SQLitePlugin.js by passing the provided success and error callbacks both to the sql statement execution and to the transaction.  This means that on successful execution the success callback is called first as

callback(transaction, results);

then as:

callback();

On a failure, depending on the nature of the error, either the success then error callbacks will be called or the error callback will be called twice.

These oddities can be avoided by using an explicit transaction and transaction.executeSql.

**Comment by MuhammadImran-04** [comment]
I'm still facing this issue on android. The Plugin version I'm using is: "0.7.15-dev", and cordova version is 5.3.3. Can anyone help?

**Comment by brody2consult** [comment]
> I'm still facing this issue on android. The Plugin version I'm using is: "0.7.15-dev", and cordova version is 5.3.3. Can anyone help?

Unfortunately that is not enough information. Can you demonstrate this with a test program?
