### ISSUE TITLE
phone gap build error (ios only)

### ISSUE THREAD

**Issue by adamstein** [brody2consult/cordova-sqlite-storage#228]
Hi 

I am trying to add the brodysoft sqlite plugin to my app. Phonegapbuild 3.7.0. Android works fine but IOS returns a 

"Oh geez. Your build failed. Sorry, but a problem occurred on the build server" 

The log says 

"The following build commands failed: 
CompileC build/myproject.build/Release-iphoneos/myproject.build/Objects-normal/armv7/SQLitePlugin.o myproject/Plugins/com.brodysoft.sqlitePlugin/SQLitePlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler 
(1 failure) 

Any ideas? 

Cheers

**Comment by brody2consult** [comment]
Will be investigated. May be related to #214.

**Comment by njejina** [comment]
Hi,
I have the same problem with IOS and i have tried everything. It seems plugin.xml ok, but the error is still here:
"..clang: error: no such file or directory: '/project/pdbDoseCalc/Plugins/com.brodysoft.sqlitePlugin/SQLitePlugin.m' "
/******************************************************
.....
CompileC build/pdbDoseCalc.build/Release-iphoneos/pdbDoseCalc.build/Objects-normal/armv7/SQLitePlugin.o pdbDoseCalc/Plugins/com.brodysoft.sqlitePlugin/SQLitePlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /project/build/pdbDoseCalc.build/Release-iphoneos/pdbDoseCalc.build/pdbDoseCalc-generated-files.hmap -I/project/build/pdbDoseCalc.build/Release-iphoneos/pdbDoseCalc.build/pdbDoseCalc-own-target-headers.hmap -I/project/build/pdbDoseCalc.build/Release-iphoneos/pdbDoseCalc.build/pdbDoseCalc-all-target-headers.hmap -iquote /project/build/pdbDoseCalc.build/Release-iphoneos/pdbDoseCalc.build/pdbDoseCalc-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build -I/project/build/pdbDoseCalc.build/Release-iphoneos/pdbDoseCalc.build/DerivedSources/armv7 -I/project/build/pdbDoseCalc.build/Release-iphoneos/pdbDoseCalc.build/DerivedSources -F/project/build -include /var/folders/wl/m2cvyl7x4c7dn08tkybswclc0000gn/C/com.apple.DeveloperTools/6.1-6A1052d/Xcode/SharedPrecompiledHeaders/pdbDoseCalc-Prefix-ercazstzauvssjeuswnmacnytbtp/pdbDoseCalc-Prefix.pch -MMD -MT dependencies -MF /project/build/pdbDoseCalc.build/Release-iphoneos/pdbDoseCalc.build/Objects-normal/armv7/SQLitePlugin.d --serialize-diagnostics /project/build/pdbDoseCalc.build/Release-iphoneos/pdbDoseCalc.build/Objects-normal/armv7/SQLitePlugin.dia -c /project/pdbDoseCalc/Plugins/com.brodysoft.sqlitePlugin/SQLitePlugin.m -o /project/build/pdbDoseCalc.build/Release-iphoneos/pdbDoseCalc.build/Objects-normal/armv7/SQLitePlugin.o
clang: error: no such file or directory: '/project/pdbDoseCalc/Plugins/com.brodysoft.sqlitePlugin/SQLitePlugin.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

CompileC build/pdbDoseCalc.build/Release-iphoneos/pdbDoseCalc.build/Objects-normal/arm64/main.o pdbDoseCalc/main.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project.......
/***************************************
Cheers

**Comment by brody2consult** [comment]
@njejina for some reason the plugin was not installed correctly. Please try removing it and installing again.

**Comment by njejina** [comment]
Hi,
i haven't got a problem with XCode (OSX Maverick) and Eclipse (on WIN 7). Localy,it works fine. I have the problem in build.phonegap.com portal when i include "com.brodysoft.sqliteplugin" in config.xml file (it doesn't meter on which version ex:. 1.0.6).  I am supposing that  include gap: "com.brodysoft.sqliteplugin" is not correctly linked in build configuration  (but i'm not sure; i cann't change build configuration in portal) or the link "com.brodysoft.sqliteplugin" is not correctly.
thanks,

**Comment by njejina** [comment]
Hi,
i have found my problem. It was my fault: "res" folder was in root of www, not in "spec\res" folder. thanks for your support.
Regards

**Comment by brody2consult** [comment]
Problem should be fixed now.
