### ISSUE TITLE
SQLite plugin is not working in iOS [Ionic]

### ISSUE THREAD

**Issue by anusree003** [brody2consult/cordova-sqlite-storage#229]
I have been using the plugin successfully in my IONIC project. The android version is successfully completed. 

But the same is not working in IOS. I got some error regarding plugins - so i removed all the plugins and freshly installed one by one. Now there is no plugin related issue.

The db object is created successfully using var db = $cordovaSQLite.openDB({ name: "mydbname.db" }); 

I think the $cordovaSQLite.execute(db,query) is not working as i am not getting any response from this command

I tried to check if the table is created using

var qry = "SELECT name FROM sqlite_master WHERE type='table' AND name='savedsearchinfo'";
           $cordovaSQLite.execute(db, qry).then(function(resrr) {
               alert(resrr.rows.item(0).name);
           });

this returned my table name in my android but this command is not executed in IOS- thats why i understood the $cordovaSQLite.execute is not working

**Comment by brody2consult** [comment]
Will be investigated. May be related to #214.

**Comment by ozanturksever** [comment]
same here.

xcode console has this output.

```
2015-04-02 11:48:41.689 ion-translator-mobile[81787:4588378] -[__NSDictionaryM length]: unrecognized selector sent to instance 0x7fb3d2c9e610
2015-04-02 11:48:41.694 ion-translator-mobile[81787:4588378] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[__NSDictionaryM length]: unrecognized selector sent to instance 0x7fb3d2c9e610
```

**Comment by brody2consult** [comment]
Hi @ozanturksever can you try to show a full stack trace?

**Comment by ozanturksever** [comment]
actually i don't know how to do that. I am not familiar with xcode, all i got is the console output for now. Program doesn't stops or xcode not switches to debug view or something.

**Comment by brody2consult** [comment]
You can try the following change to SQLitePlugin.m:

``` Objective-C
--- a/src/ios/SQLitePlugin.m
+++ b/src/ios/SQLitePlugin.m
@@ -391,20 +391,15 @@ static void sqlite_regexp(sqlite3_context* context, int argc, sqlite3_value** va

                     column_type = sqlite3_column_type(statement, i);
                     switch (column_type) {
                         case SQLITE_INTEGER:
                             columnValue = [NSNumber numberWithDouble: sqlite3_column_double(statement, i)];
                             break;
                         case SQLITE_TEXT:
-                            columnValue = [[NSString alloc] initWithBytes:(char *)sqlite3_column_text(statement, i)
-                                                                   length:sqlite3_column_bytes(statement, i)
-                                                                 encoding:NSUTF8StringEncoding];
-#if !__has_feature(objc_arc)
-                            [columnValue autorelease];
-#endif
+                            columnValue = [NSString stringWithUTF8String:(char *)sqlite3_column_text(statement, i)];
                             break;
                         case SQLITE_BLOB:
                             columnValue = [SQLitePlugin getBlobAsBase64String: sqlite3_column_blob(statement, i)
                                                         withLength: sqlite3_column_bytes(statement, i)];
 #ifdef INCLUDE_SQL_BLOB_BINDING // TBD subjet to change:
                             columnValue = [@"sqlblob:;base64," stringByAppendingString:columnValue];
 #endif
```

**Comment by ozanturksever** [comment]
No it doesn't change. But i think i found the problem.

`$cordovaSQLite.openDB({ name: "mydbname.db" });` is not the correct way, `$cordovaSQLite.openDB( "mydbname.db");` is.

i think ngCordova is old or documentation wrong (my version 0.1.12-alpha), function signature for openDB is `function (dbName, background)` 

i also think adding check to SQLitePlugin.m:open function will be helpfull. It checks for dbname but not dbfilename.

**Comment by ozanturksever** [comment]
There is a ticket on ng-cordova.
https://github.com/driftyco/ng-cordova/issues/719

**Comment by brody2consult** [comment]
Thanks @ozanturksever. Not sure if this solves the problem for the OP.

**Comment by afshines** [comment]
i am solved it on ios with

var db = window.sqlitePlugin.openDatabase({name: 'mydb.db', location: 'default'});

**Comment by Ilyoskhuja** [comment]
@afshines How? can you show code?

**Comment by felimoles** [comment]
for me solve:

not work:     
`    this.sqlite.initDatabase(); (in the constructor, for init database)
`
work: 
```
    platform.ready().then((readySource) => {
      if(platform.is('ios') || platform.is('android')){
    this.sqlite.initDatabase();
      // Platform now ready, execute any required native code
      }
    });
```
