### ISSUE TITLE
Plugin create a new db even there is one exist on the directory

### ISSUE THREAD

**Issue by vitohuang** [brody2consult/cordova-sqlite-storage#233]
Hi,

Something really strange happened to my app. I have a database called "test.db" saved in /data/data/package_name/databases/ directory and I'm using the following code to open the db:

``` javascript
var db = window.sqlitePlugin.openDatabase({name: "test.db", androidLockWorkaround: 1});
```

but when try to get a list of tables in the database, 

``` sql
select name from sqlite_master where type="table"
```

its always return "andriod_metadata" table rather than my tables in the test.db.

When I check the content of the /data/data/package_name/databases/ directory, its contain

``` bash
TEST.DB
TEST.DB.DB
TEST.DB.DB-JOURNAL
```

It just create a new db rather than use my existing one, Anyone know what is going on here?

Thanks

**Comment by brody2consult** [comment]
Please specify which version of Android you are using and whether you are using a simulator or a device. Please confirm that you are using the latest version of this plugin as well. The Android added the ".db" extension in the past, but that was removed last year.

**Comment by vitohuang** [comment]
Thanks for the swift response!

I'm using Android version: 4.4.4 KTU84P

I'm using the phonegap build and

com.millerjames01.sqlite-plugin version 1.0.1 

From phonegap's plugin directory.

**Comment by vitohuang** [comment]
Its on a real device!

**Comment by brody2consult** [comment]
> I'm using the phonegap build and
> 
> com.millerjames01.sqlite-plugin version 1.0.1

That is an old version and was uploaded by someone else last year. You can find the latest stable version at: https://build.phonegap.com/plugins/2368

**Comment by vitohuang** [comment]
Cool, switched to the new plugin and it works.

What is the story behind the redirect of  https://build.phonegap.com/plugins/2368 -> https://github.com/litehelpers/Cordova-sqlite-storage

Just seems there are many redirects going on
