### ISSUE TITLE
Publish plugin to Cordova Plugin Registry - plugins.cordova.io

### ISSUE THREAD

**Issue by DanailMinchev** [brody2consult/cordova-sqlite-storage#238]
Hi,

Thank you for the awesome plugin!

I checked [plugins.cordova.io](http://plugins.cordova.io/) and found one [com.triarc.sqliteplugin](http://plugins.cordova.io/#/package/com.triarc.sqliteplugin) and several others that claims to be "Cordova SQLite Plugin".

Also I checked PhoneGap Build, on which the plugin is available: https://build.phonegap.com/plugins/2368

Can you make this plugin available on [plugins.cordova.io](http://plugins.cordova.io/) officially?
This way we can still use it with PhoneGap Build, like:
`<gap:plugin name="com.brodysoft.sqliteplugin" version="1.0.6" source="plugins.cordova.io" />`
and we can use it with other build systems, which works with Cordova's plugin registry and not PGB registry - it is more portable.
Moreover, this way we can ignore 3rd party uploads on plugins.cordova.io of this plugin, which code maybe changed, etc ...

Thank you!

**Comment by brody2consult** [comment]
Will do when I get a chance

**Comment by brody2consult** [comment]
Just published the latest version (`0.7.5`) to both plugins.cordova.io and PhoneGap build, and updated the links in README.md. Thanks @DanailMinchev for the good words!

**Comment by DanailMinchev** [comment]
@brodybits 
Thanks for your quick response!

I tried to build on PhoneGap Build using both repositories [Cordova](http://plugins.cordova.io/#/package/io.litehelpers.cordova.sqlitestorage) and [PGB](https://build.phonegap.com/plugins/2751)

On both I am receiving error:

```
CompileC build/MyApp.build/Release-iphoneos/MyApp.build/Objects-normal/armv7/sqlite3.o MyApp/Plugins/io.litehelpers.cordova.sqliteStorage/sqlite3.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -fstrict-aliasing -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=7.0 -iquote /project/build/MyApp.build/Release-iphoneos/MyApp.build/MyApp-generated-files.hmap -I/project/build/MyApp.build/Release-iphoneos/MyApp.build/MyApp-own-target-headers.hmap -I/project/build/MyApp.build/Release-iphoneos/MyApp.build/MyApp-all-target-headers.hmap -iquote /project/build/MyApp.build/Release-iphoneos/MyApp.build/MyApp-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build -I/project/build/MyApp.build/Release-iphoneos/MyApp.build/DerivedSources/armv7 -I/project/build/MyApp.build/Release-iphoneos/MyApp.build/DerivedSources -F/project/build -include /var/folders/m1/wl3zc68x40z6cn12m764qkf80000gn/C/com.apple.DeveloperTools/6.1-6A1052d/Xcode/SharedPrecompiledHeaders/MyApp-Prefix-cuwvfvqchlgzybhcdfblcuboserf/MyApp-Prefix.pch -MMD -MT dependencies -MF /project/build/MyApp.build/Release-iphoneos/MyApp.build/Objects-normal/armv7/sqlite3.d --serialize-diagnostics /project/build/MyApp.build/Release-iphoneos/MyApp.build/Objects-normal/armv7/sqlite3.dia -c /project/MyApp/Plugins/io.litehelpers.cordova.sqliteStorage/sqlite3.c -o /project/build/MyApp.build/Release-iphoneos/MyApp.build/Objects-normal/armv7/sqlite3.o
/project/MyApp/Plugins/io.litehelpers.cordova.sqliteStorage/sqlite3.c:32015:9: error: 'gethostuuid' is unavailable: not available on iOS
    if( gethostuuid(pHostID, &timeout) ){
        ^
/project/MyApp/Plugins/io.litehelpers.cordova.sqliteStorage/sqlite3.c:32003:12: note: 'gethostuuid' has been explicitly marked unavailable here
extern int gethostuuid(uuid_t id, const struct timespec *wait);
           ^
1 error generated.
```

**Comment by brody2consult** [comment]
Thanks @DanailMinchev. Will fix soon (sqlite already has a fix).

**Comment by brody2consult** [comment]
I just pushed a new version (plugin id changed slightly). Please let me know if it builds and works for you ok or not.

**Comment by DanailMinchev** [comment]
Yes, it is working now :)
Using io.litehelpers.cordova.sqlite@0.7.6

I have tested on both PhoneGap Build and Cordova registries:
`<gap:plugin name="io.litehelpers.cordova.sqlite" version="0.7.6" />` - PhoneGap Build
`<gap:plugin name="io.litehelpers.cordova.sqlite" version="0.7.6" source="plugins.cordova.io" />` - Cordova
