### ISSUE TITLE
it is there any library make Cordova-sqlite-storage easier to use?

### ISSUE THREAD

**Issue by wozzup** [brody2consult/cordova-sqlite-storage#239]
for example: a library like `sql.js`? https://github.com/kripken/sql.js

**Comment by brody2consult** [comment]
What this project needs is better documentation! Unfortunately I have had no time to address this. Right now I want to get the testing automated then I will take a look at this.

You may want to consider using a higher-level data storage library such as http://brian.io/lawnchair/ or PouchDB. This project provides an adapter for Lawnchair; the PouchDB project already has an adapter to use this plugin.

> for example: a library like sql.js? https://github.com/kripken/sql.js

sql.js is a lower-level library, which could be used to make this plugin work with targets such as Firefox OS.

**Comment by wozzup** [comment]
haha, thank you Mr.brodybits!
