### ISSUE TITLE
Unable to build on ios

### ISSUE THREAD

**Issue by tryggve** [brody2consult/cordova-sqlite-storage#241]
I get the following error when trying to build with Cordova 4.0 and cordova-ios 3.6.3:

`The following build commands failed:
CompileC build/Foo.build/Debug-iphonesimulator/Foo.build/Objects-normal/i386/sqlite3.o Foo/Plugins/io.litehelpers.cordova.sqliteStorage/sqlite3.c normal i386 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: app/platforms/ios/cordova/build: Command failed with exit code 65`

The same error resides with the latest Cordova (4.3 and 3.8) but with the addition of `You may not have the required environment or OS to build this project`

However - when i checkout the `r1.0.4`-tag from this repository, I can build the ios platform without any problems on both cordova versions.

**Comment by brody2consult** [comment]
Not enough information. Please post the the actual error message from the compiler, if you can.

**Comment by brody2consult** [comment]
I just pushed a version that should fix the problem. Please try it again.

**Comment by tryggve** [comment]
The new 0.7.6 version build great for iOS on Cordova 4.0 and 4.3.

Thanks for the quick response! Great Work!

**Comment by brody2consult** [comment]
:+1: thanks, happy to hear!
