### ISSUE TITLE
Cant create virtual table using fts3 on IOS

### ISSUE THREAD

**Issue by calebeaires** [brody2consult/cordova-sqlite-storage#244]
```

                    db.transaction(function(tx) {
                        tx.executeSql('CREATE INDEX liv_index ON book (liv, cap);');
                        tx.executeSql('DROP TABLE IF EXISTS virtual_book');
                        tx.executeSql('CREATE VIRTUAL TABLE IF NOT EXISTS virtual_book USING FTS3(liv, cap, ver, tex, tes);', [], function(tx, res) {
                            tx.executeSql("INSERT INTO virtual_book SELECT liv, cap, ver, tex, tes FROM book WHERE ver not null;", [], function(tx, res) {
                                abrirDB('jfa.db');
                            }, function(e) {
                                console.log("ERROR: " + JSON.stringify(e));
                            });
                        }, function(e) {
                            console.log("ERROR: " + JSON.stringify(e.message));
                        });
                    });


```

**Comment by brody2consult** [comment]
Thanks for reporting, your code is an excellent starting point for testing. Marked FTS3 support as not fully tested in README.md (and FTS4 as not supported). It may take a few weeks to get this fixed.

**Comment by calebeaires** [comment]
Thanks. 

The previous version works. I downgrade to it and have tested.

**Comment by brody2consult** [comment]
FTS3/FTS4 should be working now. Please report if you have any more problems.

**Comment by dlee** [comment]
@brodybits can you verify that FTS3/FTS4 should be working in iOS now?

The Limitations section of the README seems to indicate otherwise: https://github.com/litehelpers/Cordova-sqlite-storage/blob/master-rc/README.md#other-limitations

**Comment by brody2consult** [comment]
On Tuesday, August 18, 2015, David Lee notifications@github.com wrote:

> @brodybits https://github.com/brodybits can you verify that FTS3/FTS4
> should be working in iOS now?

Yes this is actually verified in the spec test suite.

> The Limitations section of the README seems to indicate otherwise:
> https://github.com/litehelpers/Cordova-sqlite-storage/blob/master-rc/README.md#other-limitations
> 
> My bad, I will fix it soon!

## 

Sent from my mobile
