### ISSUE TITLE
Select return null for string

### ISSUE THREAD

**Issue by crazyshock** [brody2consult/cordova-sqlite-storage#250]
Hi... I'm doing a select in my table but the values which are text is returning null...

Is a example of select:

```
 var queryPes = "SELECT "+
                               "  pf.name_full, paciente.number_id, paciente.name_id, paciente.APP_ID "+
                               "  FROM paciente paciente "+                              
                               "  left outer join pessoa_fisica pf on pf.pp_id = paciente.pp_id "+
                               "  order by pf.name_full";
```

the value name_full is returning null, but the value name_id which is an integer field is returning the correct value example: 2...

Can anyone help me?

**Comment by brody2consult** [comment]
Unfortunately that is not enough information-we have no idea how the table was created. We need the code you used to create the table and populate the data to help you find the issue.

**Comment by crazyshock** [comment]
the structure of the tables are simple... With type INTEGER and TEXT.
When I'm doing a select on a table just the return is correct.
But when I use "JOIN" just returns me the values INTEGER the TEXT are null.

**Comment by nolanlawson** [comment]
@over12 A good test is to use `window.openDatabase` (native WebSQL database) instead of `window.sqlitePlugin.openDatabase` and see if the results are any different. If they are NOT different, then it's a bug in your own code, not in the SQLite Plugin. :)

**Comment by trevorpowell** [comment]
If you haven't tried this, I would maybe try running the SQL query on the database in a standalone database browser like this one:

http://sqlitebrowser.org/

That helps isolate whether it's an issue with the SQL query or an issue with the plugin. If you've already done that, just ignore this. Could also try using aliases for the columns you are selecting maybe.
