### ISSUE TITLE
Can't open database on iOS

### ISSUE THREAD

**Issue by obrmm** [brody2consult/cordova-sqlite-storage#252]
Since I updated the plugin on iOs, I'm unable to open the database.

In xCode log I get
###### ##### Begin Error message

2015-04-28 15:14:50.176 XXX[552:134287] -[CDVCommandQueue executePending] [Line 158] FAILED pluginJSON = [
  "SQLitePlugin1655549170",
  "SQLitePlugin",
  "open",
  [
    {
      "name" : "database.sqlite",
      "location" : 0,
      "dblocation" : "docs"
    }
  ]
]
###### ##### End Error message

Would you have any idea, what could be causing that?

**Comment by brody2consult** [comment]
Can you try it with a fresh project?

**Comment by obrmm** [comment]
Ok, it's working on afresh project, so it must be something about my project.

I'll try to debug it further, thanks!

**Comment by obrmm** [comment]
Found it!
The Target Membership of the .m and .c files was not set in xCode.

Sorry for the noise...
