### ISSUE TITLE
what's the difference  between $cordovaSQLite.openDB and sqlitePlugin.openDatabase?

### ISSUE THREAD

**Issue by shikelong** [brody2consult/cordova-sqlite-storage#265]
I user  the version-- 
io.litehelpers.cordova.sqlite 0.7.8-dev "Cordova sqlite storage plugin"

on android platform.
i can't find  sqlitePlugin object . and i can't use openDB() to open a database.
there is in my console:
open  failed, aborting any pending transactions. 

thx!

**Comment by brody2consult** [comment]
> i can't find sqlitePlugin object

then try `window.sqlitePlugin` object

If you use `window.sqlitePlugin.openDatabase()`, you get the API as documented in README.md, which should match the standard Web SQL API very closely.

If you use `$cordovaSQLite.openDB()`, you get a promise-based API. The API is documented in http://ngcordova.com/docs/plugins/sqlite/ but right now it has a major mistake: the page tells you to call `$cordovaSQLite.openDB()` with an object, but you have to call `$cordovaSQLite.openDB()` with a string.

**Comment by shikelong** [comment]
Thank you very much.  
At first I inspect $window.
then i use:
var db = window.sqlitePlugin.openDatabase({name: "my.db", androidDatabaseImplementation: 2});
i find it work well.

**Comment by RupenAnjaria** [comment]
Is this difference still exist? which one is better (if they are different in any case). Further, which one should be used if we need to use database encryption using SQLCipher
