### ISSUE TITLE
On the Android platform,where can I found my (sqlite)db file?

### ISSUE THREAD

**Issue by shikelong** [brody2consult/cordova-sqlite-storage#266]
``` javascript

 var db = window.sqlitePlugin.openDatabase({name: "my.db", androidDatabaseImplementation: 2,androidLockWorkaround:1});

```

first I open sqlite database. but i can't find a file named my.db. where it exists?

**Comment by brody2consult** [comment]
> first I open sqlite database. but i can't find a file named my.db. where it exists?

/data/data/app.package.name/databases but you cannot see it on a non-rooted device without special tools: http://stackoverflow.com/questions/15326455/what-is-the-default-database-location-of-an-android-app-for-an-unrooted-device

Needs to be added to the documentation (when I get a chance).

**Comment by shikelong** [comment]
ok. thx.
