### ISSUE TITLE
SQLitePlugin.js catching general js errors at line 375?

### ISSUE THREAD

**Issue by mirko77** [brody2consult/cordova-sqlite-storage#271]
I am facing a weird issue when remote debugging using Chrome Dev Tools

The `SQLitePlugin.js` at line 374 (`catch (_error)`) is also catching general errors I have in my script, therefore the console does not show me the error messages.

I had to add the line `console.error(_error.message);` after the `catch` so it displays the error in the console. It happens even though I am not interacting with the database at all, and my code is wrapped in a closure.

It is just weird. is it just me facing this?

**Comment by brody2consult** [comment]
If you have a transaction error callback it _should_ be able to see the same information in the message member of the error parameter object, i.e. `err.message` or `error.message`.

**Comment by mirko77** [comment]
@brodybits I do not have a transaction going on sometimes and it is still catching the error. You are right though, if there is a transaction error callback the error message gets displayed there. I am wondering why it happens when no transactions are being processed.

**Comment by brody2consult** [comment]
In general: You know the API is completely asynchronous so your db.transaction() call would _always_ return before your transaction statements are actually executed. Also, in case someone calls executeSql() on a transaction object after it is finalized SQLitePlugin.js will simply throw an exception (which should not be automatically caught).

**Comment by brody2consult** [comment]
> I do not have a transaction going on sometimes and it is still catching the error.

In case of this observation please try to isolate the scenario as much as possible. This really should not happen.

**Comment by mirko77** [comment]
I know, I will look into it and post my findings, thanks

**Comment by ArnaudValensi** [comment]
I have the same problem. Here is my function to make the requests:

``` js
        function execRequest(rqst, args, cb) {
            _db.transaction(function(tx) {
                tx.executeSql(rqst, args,
                    function (tx, rsp) {
                        cb(null, rsp);
                    },
                    function (tx, err) {
                        cb(err);
                    }
                );
            }, function catchAllErrors(err) {
                cb(err);
            });
        }
```

The function `function catchAllErrors` is where takes place this problem.

**Comment by mirko77** [comment]
@ArnaudValensi that function `catchAllErrors` is supposed to be called when there is a transaction error, if I am not mistaking?

**Comment by ArnaudValensi** [comment]
@mirko77 I think so, I mean it would seem logic to me.

**Comment by brody2consult** [comment]
@ArnaudValensi, if the error handler of tx.executeSql() does not return false, then db.transaction() will call its error callback if there was a sql error. This _is_ according to [the W3 database spec](http://www.w3.org/TR/webdatabase/) as @aarononeal says in [this comment in #232](http://www.w3.org/TR/webdatabase/):

> In case of error, run the following substeps:
> 
> > 1. If the statement had an associated error callback that is not null, then queue a task to invoke that error callback ...
> > 2. If the error callback returns false, then move on to the next statement, if any, or onto the next overall step otherwise. [continue execution]
> > 3. Otherwise, the error callback did not return false, or there was no error callback. Jump to the last step in the overall steps. [rollback and fail]
> 
> The last step in the overall steps is:
> 
> > Queue a task to invoke the transaction's error callback, if it is not null, with a newly constructed SQLError object that represents the last error to have occurred in this transaction. Rollback the transaction. Any still-pending statements in the transaction are discarded.
> 
> So, if you don't want the transaction to fail, you need to provide an error callback and explicitly return false.
