### ISSUE TITLE
how to retrieve data from cordova sqlite database in android java

### ISSUE THREAD

**Issue by AshokBR** [brody2consult/cordova-sqlite-storage#273]
how can retrieve the sqlite database data created by cordova in android java
plz give me the solution..f

**Comment by brody2consult** [comment]
You can open the database using the standard Android sqlite database API.

**Comment by AshokBR** [comment]
can you send me the sample code .....
SQLite is already created by cordova/phonegap using jquery ...... i want to retrieve the same data using java .........plz send me the sample code ...
