### ISSUE TITLE
Issue in Android

### ISSUE THREAD

**Issue by keetonicc** [brody2consult/cordova-sqlite-storage#277]
I've been able to successfully use this awesome library for weeks now, but seem to have run into a problem with one of the recent updates. When I do "cordova run android", during the build, I get the message: 
Note: home/administrator/Workspace/analytics/app/analytics/platforms/android/src/io/liteglue/SQLiteAndroidDatabase.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Also, my logcat shows the following error message when I try to use the library in my application: 

E/art     (20974): No implementation found for java.lang.String com.almworks.sqlite4java._SQLiteSwiggedJNI.sqlite3_libversion() (tried Java_com_almworks_sqlite4java__1SQLiteSwiggedJNI_sqlite3_1libversion and Java_com_almworks_sqlite4java__1SQLiteSwiggedJNI_sqlite3_1libversion__)

Could this be an error with using the new sqlite4java? I've tried updating all my SDK libraries, remove and add the plugin, and remove and add the android platform with cordova to no avail. Thank you!

**Comment by brody2consult** [comment]
Looks like something went wrong loading the native library. As a workaround, you can add the option `androidDatabaseImplementation: 2` when you open the database to use the old implementation.

Which CPU architecture are you running this on?

**Comment by jonathancma** [comment]
Hi, just here to say that I'm having this issue as well during compilation. At first glance in my application, nothing is persisted - the application works fine, but when I exit it and enter again, nothing was stored. But this may be unrelated...

**Comment by brody2consult** [comment]
The original question had two parts:
1. a compilation message
2. a runtime problem
1. The compilation message is merely a warning that something is using an API function that is deprecated, and may actually be removed in the future. It _should_ not cause anything to break right now. I will investigate this when I get a chance.
2. The runtime problem in the original question had to do with a native library which has now been replaced. I gave a workaround and asked a followup question but did not hear anything back.

Your issue that you do not see anything persisted is something new. I have already given a procedure in README.md how to deal with this kind of problem. Basically, you should make sure you have updated your Cordova CLI, create a fresh new project and start with something simple. If you see something wrong when you try a limited test program, then please raise a new issue with your test program and I would be very happy to take a look.

**Comment by jonathancma** [comment]
Reporting back that indeed there is NO persistence issue, that was an unrelated bug. The compilation warning has no apparent effect on the application, but could in the future due to deprecation.
Thanks for your help :)
