### ISSUE TITLE
Android synchronization?

### ISSUE THREAD

**Issue by craig-at-rsg** [brody2consult/cordova-sqlite-storage#279]
First of all, thank you for this wonderful plugin!

I was hoping you could give me a tip which could help to vastly simplify my codebase...

My app has an Android service running in the background, and if there is any work done on a database in the background for Android, then I've been making all queries against that database from Java. 

Is it possible for me to access the same database instances this plugin uses from my Java code on Android? I think this would let me write only the queries that need to run in the background in Java, and I could then reuse many Javascript queries.

**Comment by brody2consult** [comment]
That is a really good idea and I tried to do it for someone else. But it will be a bit non-trivial for two reasons:
- the Android version implements a threading model where each database connection is running in its own thread
- the plugin allows the user to dynamically switch between two Android sqlite libraries.

The Android version uses asynchronous commands and callbacks to implement its threading model. It would be possible to add a Java API to work together with the plugin.

To be honest, I am not sure when I would have time to work on this feature. Also, to be frank I am not sure if I would want to either implement or support this feature for free.
