### ISSUE TITLE
Using ngCordova, $scope loses focus when nested exectuable

### ISSUE THREAD

**Issue by dcp3450** [brody2consult/cordova-sqlite-storage#280]
I'm running to select queries to create a multi dimensional array. I'm running one in an execute method and running a nested execute similar to the docs for this plugin. When I try to push to `$scope.installations.products` inside the second executable it doesn't recognize `installations` and says it's `undefined or null`

If I place the same `push` event outside the second execute it pushes fine:

```
var query = "SELECT nanoInst.rid AS instID, nanoInst.name AS instName, nanoInst.instLoc AS instLoc, nanoInst.instText AS instMainText, nanoInst.pixelPitch AS instPitch, nanoInd.name AS indName FROM nanoInst LEFT JOIN nanoRelInd ON nanoInst.rid = nanoRelInd.inst_id LEFT JOIN nanoInd ON nanoInd.rid = nanoRelInd.ind_id";



$cordovaSQLite.execute(nanoDB, query, []).then(function (res) {
$scope.installations = [];

//start loop to get the installations
for (var x = 0; x < res.rows.length; x++) {
    $scope.installations.push({ id: res.rows.item(x).instID, name: res.rows.item(x).instName, location: res.rows.item(x).instLoc, instText: res.rows.item(x).instMainText, pixelPitch: res.rows.item(x).instPitch, industry: res.rows.item(x).indName, products: []});
}

//run a new query to get the additional intallation info
for (var y = 0; y < $scope.installations.length; y++) {
    console.log($scope.installations[y].products);

    var installQuery = "SELECT nanoProd.name AS prodName FROM nanoProd LEFT JOIN nanoRelProd ON nanoProd.rid = nanoRelProd.prod_id WHERE nanoRelProd.inst_id = ?";

    $cordovaSQLite.execute(nanoDB, installQuery, [$scope.installations[y].id]).then(function (res2) {
        $scope.installations[y].products.push({ name: 'jill' });
    });
}
```

I know this might be an issue for ngCordova but their documentation isn't that great and no one responds to issues there.

**Comment by dcp3450** [comment]
I found the issue. When I get to the second execute it's passing the final y value since the for loop is running asynchronously. So now I need to figure out how to make a select call for each installation.

**Comment by shanmicheal25** [comment]
$scope.recordListVal.push({titleId: resCompRecVal.rows.item(l).titleId, componentId: resCompRecVal.rows.item(l).componentId, recordList: $scope.recordList });
