### ISSUE TITLE
Unable to execute two select statements that depend on each other

### ISSUE THREAD

**Issue by dcp3450** [brody2consult/cordova-sqlite-storage#281]
I need to end up with an array that looks something similar to this:

```
[
    {
        id: "1",
        name: "name1",
        location: "location1",
        products: [
            {
                name: "product1"
            },
            {
                name: "product2"
            },
            {
                name: "product3"
            }
        ]
    },
    {
        id: "2",
        name: "name2",
        location: "location2",
        products: [
            {
                name: "product4"
            },
            {
                name: "product5"
            }
        ]
    }
]
```

What I would normally do is run a `select` statement to populate my first level since my second depends on the `id` of the first. Since this is an asynchronous system that doesn't seem to workout. This is my attempt:

```
var query ="..."
$cordovaSQLite.execute(nanoDB, query, []).then(function (res) {
    $scope.installations = [];
    //start loop to get the installations
    for (var x = 0; x < res.rows.length; x++) {
        $scope.installations.push({ id: res.rows.item(x).instID, ... , products: [] });
        var installQuery = "...";
        $cordovaSQLite.execute(nanoDB, installQuery, [res.rows.item(x).instID]).then(function (res2) {
            for (var y = 0; y < res2.rows.length; y++) {
                $scope.installations[x].products.push({ name: res2.rows.item(y).prodName })
            }
        });
    }
});
```

Obviously the issue is the first for loop completes before the second (you know asynchronously).  If this ran as a synchronously the second loop would run before moving to the next iteration in the first for loop.

I can't see anything in the documentation about doing something like this. Can anyone provide some direction?

**Comment by brody2consult** [comment]
Unfortunately, I do not really follow the code very well. For this kind of question, I suggest you try the same code with a database opened using the normal HTML5/Web SQL API (i.e. `window.openDatabase()`).

**Comment by hnakhuva** [comment]
have you found the solution?? I am facing the same problem :(
