### ISSUE TITLE
Do this sqlite databases storage persist when replacing/upgrading the APK ?

### ISSUE THREAD

**Issue by boltex** [brody2consult/cordova-sqlite-storage#285]
same as title : Do this sqlite databases storage persist when replacing/upgrading the APK ?

**Comment by nolanlawson** [comment]
Yes, they do. You can check under `/data/data/com.mycompany.appname/databases`.

**Comment by brody2consult** [comment]
> same as title : Do this sqlite databases storage persist when
> replacing/upgrading the APK ?

Can you explain what you mean by "replacing" the APK? If you uninstall an
app to _will_ lose the app data including the database.

**Comment by boltex** [comment]
Thank you both, your answers confirm what nicraboy himself told me on the ionic forum : 

> Upgrading an already installed APK will not wipe your SQLite database unless you programmatically tell it to. When you uninstall / remove an APK, all data include the SQLite database will be removed with it.
