### ISSUE TITLE
iOS db.transaction and  tx.executeSql goes to long wait after reading/selecting data from same table again and again.

### ISSUE THREAD

**Issue by amitkumaroae** [brody2consult/cordova-sqlite-storage#289]
I am using com.brodysoft.sqliteplugin plugin in my cordova project.

I have created about 5-6 tables.

i need to read 1 table very frequently.

In android everything is working fine but in ios after reading table multiple time db.transaction  and tx.executeSql stops working and no callback (success or error) fires for long time, and after some time it fires the success of last transaction.

 Any solutions??

**Comment by brody2consult** [comment]
> I am using com.brodysoft.sqliteplugin plugin in my cordova project.

I just updated the plugin ID again to match the NPM style. Please use the latest version.

> In android everything is working fine but in ios after reading table multiple time db.transaction and tx.executeSql stops working and no callback (success or error) fires for long time, and after some time it fires the success of last transaction.
> 
> Any solutions??

Unfortunately that is not enough information to help find the cause of your problem. Please isolate a small, self-contained test program to reproduce the issue and either post it or send it to info@litehelpers.net.
