### ISSUE TITLE
SQLCipher Compatibility?

### ISSUE THREAD

**Issue by njtman** [brody2consult/cordova-sqlite-storage#29]
As this plugin currently stands, does it support Android SQLCipher?  It was really easy to get everything working in iOS just fine, but I keep running into roadblocks on the Android side.  

I have tried using SQL Cipher libraries 2.1.1 and the new 3.0 and neither of them seem to work, I keep getting errors in the console on the javaside.  I am using Cordova 3.2, and the code from this repository.  I have patched the code as per this blog post, http://brodyspark.blogspot.com/2012/12/using-sqlcipher-for-android-with.html to work with cipher.

The app does compile and run, but when I start to issue DB commands, it blows up.

Using a very old version of this plugin (with sql cipher patches), which I had stored on my computer from about a year ago (when the blog post mentioned above was written), everything works fine.  However, I would like to take advantage of some of the new features that are offered in the newer plugin.  Also for consistency, I would like to keep my android and ios projects using as much of the same code as possible.

I have made a simple test program, if you would like to see the error for yourself.  Let me know, and I can share the link.

**Comment by brodybits** [comment]
For those who are interested, I am happy to announce that I have just published a new version that supports SQLCipher embedded out-of-the-box here: https://github.com/brodysoft/Cordova-sqlcipher-adaptor

I hope that people will dare to try it out on both Android & iOS platforms. SQLCipher v3.2.0, which is currently the most recent release, is embedded as source code for iOS and as library code for
Android.

It is possible and recommended to install the sqlcipher version of the plugin using either the plugman tool or Cordova CLI.

In addition, there is (somewhat limited) automatic testing of the encryption & decryption functionality.
