### ISSUE TITLE
Error when build in Visual Studio 2015 and Cordova-sqlite-storage 7.10

### ISSUE THREAD

**Issue by cuong1024** [brody2consult/cordova-sqlite-storage#291]
Hi,
After I update cordova-sqlite-storage to 7.10, my app take error "version not found: 0.7.10-dev : io.litehelpers.cordova.sqlite/0.7.10-dev"
I creare a new project but it still take this error. 
Please help me. 
Thank alot.

**Comment by cuong1024** [comment]
Oh,
I can run it. :dancers:  
Sorry.

**Comment by jdnichollsc** [comment]
For Windows platform? How? :)
