### ISSUE TITLE
Can be used with platform browser ?

### ISSUE THREAD

**Issue by mrbinr** [brody2consult/cordova-sqlite-storage#297]
Hi,
I would like to use sqlite-storage with platform browser but i have this error : 
OPEN database: myDb.db SQLitePlugin.js:171
OPEN database: myDb.db failed, aborting any pending transactions SQLitePlugin.js:192
Could not open database

and here is my code : 

document.addEventListener('deviceready',onDeviceReady, false);
function onDeviceReady() {
  var db = window.sqlitePlugin.openDatabase({name: "myDb.db", location:2, createFromLocation: 1});
}

I use this command line to build and launch : 
cordova build browser
cordova run browser

Browser (Chrome) open and i can see error : 

OPEN database: myDb.db SQLitePlugin.js:171
OPEN database: myDb.db failed, aborting any pending transactions SQLitePlugin.js:192
Could not open database

I've tried to put myDb.db into folder plugins/io.litehelpers.cordova.sqliteStorage/www/ but i have the same error .. :(

And so i don't know if this plugin can be used with plateform browser , or may be another wau to use it ...

Thanks for your help ...
Best Regards

Pascall

**Comment by mrbinr** [comment]
No idea about it ?
I'm still trying to test it without result

**Comment by mrbinr** [comment]
Hi,
I've tried with another sqlite plugin and i works as expected, it take my db file from myProject/www and copy it into browser/www/ and i can access to it easily with my app ...
So i gonna use it ...
If any one has ideas about how to use cordova-sqlite-storage with browser platform,let me know about it ...

**Comment by brody2consult** [comment]
Unfortunately this plugin does _not_ yet support the "browser" platform. Happy that you found another solution (so far). Just curious which project you are using?

**Comment by mrbinr** [comment]
Hi,
i'm using https://github.com/samikrc/CordovaSQLite

**Comment by prankstr** [comment]
Hi, 

have you made any progress in the browser support or do you know of any workaround you can use? I'm not to keen on using the other library mentioned.

Thanks!

**Comment by brody2consult** [comment]
This feature is still under consideration. I am pretty swamped with both paid and free software work right now. Priority will be given to paid customers.

**Comment by ionutzp** [comment]
any updates on this issue @brodybits ? thanks

**Comment by brody2consult** [comment]
This feature is still under consideration and priority is given to paid users. For expedited feature development you may contact: brodybits@litehelpers.net or sales@litehelpers.net

**Comment by rafw87** [comment]
I've prepared simple browser implementation in this PR: #575 for my purposes.
You could use it if you want.

**Comment by brody2consult** [comment]
I raised #576 with an initial implementation for the browser platform. It supports the more difficult transaction cases such as nested transactions, error handling, and error recovery.

I may need 1-2 months to finish the browser platform due to some existing workload.

**Comment by fernandocode** [comment]
Hi @brodybits , any predictions for launching the version with platform browser support? This would be very useful!

**Comment by brody2consult** [comment]
Hopefully within the next 1-2 months

**Comment by alejandrohn** [comment]
Hello, 

when will it be ready?

**Comment by brody2consult** [comment]
My apologies for the delay. Browser platform support using SQL.js should be ready in July 2018 as discussed in PR #576 and issue #773 (July 2018 major release). I would like to keep further discussion in #773.
