### ISSUE TITLE
Implement prepopulation in visual studio cordova

### ISSUE THREAD

**Issue by vioir** [brody2consult/cordova-sqlite-storage#300]
I just installed the plugin in visualstudio in my cordova project , and i want to use prepopulation database in my project i put my database file (test.db) in www folder in project's solution 
![1212](https://cloud.githubusercontent.com/assets/13207882/8532847/58cb16ba-2446-11e5-919d-504410ae2340.JPG)
when i try to use the following code: 

``` javascript
document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() {
    var db = window.sqlitePlugin.openDatabase({ name: "test.db", createFromLocation: 1 });
        db.transaction(function (tx) {
            tx.executeSql("SELECT * FROM table1", [], function (tx, res) {
                console.log("res.rows.length: " + res.rows.length + " -- should be 1");
                console.log("res.rows.item(0).cnt: " + res.rows.item(0).cnt + " -- should be 1");
            });
        }, function (e) {
            console.log("ERROR: " + e.message);
        });
}
```

i get the following error:
![error](https://cloud.githubusercontent.com/assets/13207882/8533111/fa344340-2447-11e5-8a34-9ac0d4a8f83e.JPG)

also i get the error "DB opened: somethingNotExist.db" when i trying to open a database that is not in my project !!!
i am using android emulator to debug the project.
i checked my database file (test.db) it contain 'table1' table .

**Comment by brody2consult** [comment]
Unfortunately I am not sure if I understand your question 100%. There had been some discussion to add pre-populated database for both `windows` (universal) and `wp8` platforms. In general, if you try to open a database filename that does not exist, the database will be created automatically (I am planning to make this optional, along with some other API enhancements). Also, sqlite _should_ be ACID compliant, i.e. it has failure-safe mechanisms so that it should _never ever_ lose data.

If you have any questions or suggestions, please make them very clear, one point at a time. You can also open multiple bug reports if necessary.

**Comment by vioir** [comment]
ow , thank you , so i think i put my database in wrong folder , and the app does not find it , and create a new one instead .
can you please help me to find witch folder i should put my database into ?
how should i pass the correct address of my database to sqlitePlugin.openDatabase() function ?!

**Comment by brody2consult** [comment]
Do you know which Cordova platform version you are using?

NOTE: both `windows` and `wp8` will support Windows Phone 8.1.

**Comment by vioir** [comment]
i installed "Tools for Apache Cordova for Visual Studio 2013 - CTP3.1" ,
and i created a "Blank App (Apache Cordova)" project ,
then i added "https://github.com/litehelpers/Cordova-sqlite-storage.git" plugin to project .

**Comment by brody2consult** [comment]
> i installed "Tools for Apache Cordova for Visual Studio 2013 - CTP3.1" ,
> and i created a "Blank App (Apache Cordova)" project ,
> then i added "https://github.com/litehelpers/Cordova-sqlite-storage.git" plugin to project .

Happy that it worked for you! Someone else had problems with it in the past (#237).

**Comment by vioir** [comment]
i do not want use it for windows phone application , i am trying to use this plugin for android application , i think it is ok with android apps , but i put the database in wrong folder

**Comment by brody2consult** [comment]
> i do not want use it for windows phone application , i am trying to use this plugin for android application , i think it is ok with android apps , but i put the database in wrong folder

Thanks, happy you got it working.

I would like to add this in case it will help some others: The "Tools for Apache Cordova for Visual Studio 2013" was OK for Android. I am still not sure if it will work for Windows Phone, as discussed in #237.
