### ISSUE TITLE
new transaction is waiting for open operation

### ISSUE THREAD

**Issue by yokas** [brody2consult/cordova-sqlite-storage#301]
I'm following this tutorial to build an ionic ios app, but it always say:
`new transaction is waiting for open operation`

https://blog.nraboy.com/2014/11/use-sqlite-instead-local-storage-ionic-framework/`

I'm using io.litehelpers.cordova.sqlite 0.7.10-dev "Cordova sqlite storage plugin"

I have been working on this issue for two days , please help me.

**Comment by brody2consult** [comment]
Unfortunately that is not enough information. It looks like something went wrong with your installation. Please try it again and check your steps very carefully.

If you are really stuck, you can send a full archive of your project to info@litehelpers.net and I can take a look.

**Comment by yokas** [comment]
Thanks for reply, I noticed that there is an update?
So after I updated to this:
`io.litehelpers.cordova.sqlite 0.7.10-pre "Cordova sqlite storage plugin"`

it worked!

**Comment by brody2consult** [comment]
> So after I add this:
> io.litehelpers.cordova.sqlite 0.7.10-pre "Cordova sqlite storage plugin"
> 
> it worked!

Happy to hear!

**Comment by CodeYourLife** [comment]
what is the command line operation to install this?
