### ISSUE TITLE
Invalid database handle in android 2.3

### ISSUE THREAD

**Issue by lucidplus** [brody2consult/cordova-sqlite-storage#303]
I have used this plugin in my multi-platform cordova app. It is working perfect in android 4.x and windowsphone 8.1. But it is not working in android 2.3.6 samsung  y duos. It shows an error message "ERROR:Invalid database handle"
Please help..

**Comment by brody2consult** [comment]
Please make sure you are running the latest version (0.7.10-pre). I recently changed the default Android sqlite implementation from sqlite4java to [Android-sqlite-connector](https://github.com/liteglue/Android-sqlite-connector). If it still does not work on your device, you may have to use the `androidDatabaseImplementation` option as described in README.md.

**Comment by lucidplus** [comment]
Thank you Brody. 
I updated the version to 0.7.10 as you told. 
Now it is working perfectly.
Thanks for your fast response.

**Comment by brody2consult** [comment]
Thanks, happy to hear!

**Comment by veerajongit** [comment]
Mine is also not working :-( 
Same error.

**Comment by brody2consult** [comment]
> Mine is also not working :-( 
> Same error.

@veerajongit please make sure you are using the latest version. If you get the error using the latest error, please try setting the `androidDatabaseImplementation` option to `2` as desribed in README.md. If you continue to see the problem please make the simplest test program that you can, without any major frameworks such as Angular/ngCordova/Ionic or React, and raise a new issue with the test program.
