### ISSUE TITLE
window.sqlitePlugin doesn't exist on WP 8.1, but window.SQLite3 does

### ISSUE THREAD

**Issue by nolanlawson** [brody2consult/cordova-sqlite-storage#305]
It should be `window.sqlitePlugin`, no? Prompted by https://github.com/pouchdb/pouchdb/issues/4007

**Comment by brody2consult** [comment]
> It should be window.sqlitePlugin, no? Prompted by pouchdb/pouchdb#4007

Sounds like an installation problem to me

**Comment by nolanlawson** [comment]
@darkyen ^

**Comment by darkyen** [comment]
@brodybits Strange, no error logs were thrown that day, i followed all the steps on the site. Anything i can do to narrow down the error ?

**Comment by brody2consult** [comment]
> @brodybits Strange, no error logs were thrown that day, i followed all
> the steps on the site. Anything i can do to narrow down the error ?

Try it on a fresh new project and if you get the problem send it to
info@litehelpers.net. I can take a look over the coming week.

**Comment by brody2consult** [comment]
Looks like an installation problem, closing.
