### ISSUE TITLE
SQLITE Prepare statement error [INSERT]

### ISSUE THREAD

**Issue by subu1979** [brody2consult/cordova-sqlite-storage#310]
When i'am trying to insert into the database, iam getting following error

I/chromium( 1475): [INFO:CONSOLE(167)] "database already open: msfa.db", source: file:///android_asset/www/plugins/io.litehelpers.cordova.sqlite/www/SQLitePlugin.js (167)
I/chromium( 1475): [INFO:CONSOLE(79)] "DB opened: msfa.db", source: file:///android_asset/www/plugins/io.litehelpers.cordova.sqlite/www/SQLitePlugin.js (79)
V/sqlg    ( 1475): prepare db 0xa1264088 sql BEGIN
V/sqlg    ( 1475): sqlc_st_finish 0xa121e6e8
V/sqlg    ( 1475): prepare db 0xa1264088 sql INSERT INTO leads_master(orgname,contact,mobile,email,requirement,brand) VALUES ('C2il ','Subbu' , '7299003593', 'Subramaniyam.k@c2il.com ','Demo','CRM');
W/System.err( 1475): java.sql.SQLException: prepare statement failed with error: 1
W/System.err( 1475):    at io.liteglue.SQLiteGlueConnection.prepareStatement(SQLiteGlueConnection.java:45)
W/System.err( 1475):    at io.liteglue.SQLitePlugin$SQLiteDatabaseNDK.executeSqlStatementNDK(SQLitePlugin.java:493)
W/System.err( 1475):    at io.liteglue.SQLitePlugin$SQLiteDatabaseNDK.executeSqlBatch(SQLitePlugin.java:434)
W/System.err( 1475):    at io.liteglue.SQLitePlugin$DBRunner.run(SQLitePlugin.java:618)
W/System.err( 1475):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 1475):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 1475):    at java.lang.Thread.run(Thread.java:818)
V/executeSqlBatch( 1475): SQLitePlugin.executeSql[Batch](): Error=prepare statement failed with error: 1
V/sqlg    ( 1475): prepare db 0xa1264088 sql ROLLBACK
V/sqlg    ( 1475): sqlc_st_finish 0xa121e6e8

**Comment by brodybits** [comment]
Please post your JavaScript code or send it to info@litehelpers.net

**Comment by brody2consult** [comment]
SQLite error code `1` was returned from the C-interface function call, which means there was an error with the SQL statement (ref: https://www.sqlite.org/c3ref/c_abort.html). The sql statement looks OK by itself, so I suspect either the table was not created or the fields did not match. But I cannot say for sure without looking at your program.

I really need to see the code you used to open the database, create the table, and add the record to help you any further. You can either post it or send it to: info@litehelpers.net

**Comment by brody2consult** [comment]
A common cause is the case where a table has certain NOT NULL field(s) that are forgotten in the INSERT statement. This should be reflected in `error.message` that is returned in the error callback, needs to be tested.

**Comment by SP1966** [comment]
I was experiencing the same error and after pulling out my last remaining hair follicles I found the issue was the SQL to create the table was wrong, I was trying to use "CREATE TABLE IF NOT EXIST..." rather than "EXISTS". 

Leaving this here in case somebody else has the same issue.

**Comment by brody2consult** [comment]
Thanks @SP1966.

**Comment by inceptiveKshitij** [comment]
Hello @brodybits,
I created the database successfully by following your given. Also i saw the database as well as table in my chrome browser resource tab. Then i try to insert some data in my created table, but it give me an error which is "Could not prepare statement, 1 column not found." Please refer below code 
`if (testing == "browser") {
            db = window.openDatabase("myfriend.db", "1.0", "myfriend Database", -1);
        } else {
            db = window.sqlitePlugin.openDatabase({ name: "myfriend.db", location: 'default' });
        }
        db.transaction(function(tx) {
            tx.executeSql("INSERT INTO friends (first_name, last_name, city, mobile_No) VALUES (?,?,?,?)", [$scope.registerUser.firstname, $scope.registerUser.lastname, $scope.registerUser.city, $scope.registerUser.mobNo], function(tx, res) {
                console.log("INSERT ID -> " + res.insertId);
                $location.path("templates/playlists");

```
        }, function(err) {
            console.log(err);

        });

    });` 
```

Please help me for this issue. 
Thanks....

**Comment by brody2consult** [comment]
@inceptiveKshitij it looks like either the table does not exist or you are using an incorrect column name.

**Comment by DipakMahapurkar** [comment]
Please check your table creation:
tx.executeSql('CREATE TABLE IF NOT EXISTS friends(id integer primary key autoincrement, first_name text, last_name text, emailAddress text, city text, mobile_No text)');
replace it with 
tx.executeSql('CREATE TABLE IF NOT EXISTS friends(id integer primary key autoincrement NOT NULL, first_name text, last_name text, emailAddress text, city text, mobile_No text)');

**Comment by pratishtha20** [comment]
Hello @brodybits 
I have created DB successfully with tables & values. Now I am writing a generalized query for using select query. My function is : 
generalizedQuery(query: string, params: any[]=[]): Promise<any> {
    return new Promise((resolve, reject) => {
      try {
        this._db.transaction((tx: any) => {
          tx.executeSql(query, params,
            (tx: any, res: any) => resolve({ tx: tx, res: res }),
            (tx: any, err: any) => reject({ tx: tx, err: err }));
        },
          (err: any) => reject({ err: err }));
      } catch (err) {
        reject({ err: err });
      }
    });
  }
  
  get(selectorForGet: string, tbName: string, parameters: string): Promise<any>{
 const result = new Promise((resolve, reject)=>{
  if(isNull(parameters)){
    this.generalizedQuery('select ? from ?', [selectorForGet, tbName])
    .then((data)=>{
    resolve(data);
    }).catch(err => {debugger;
      console.error('Storage: Unable to create initial storage tables', err.tx, err.err);
  });
   }
   else{
    this.generalizedQuery('select ? from ? where ?', [selectorForGet, tbName, parameters])
    .then((data)=>{
    resolve(data);debugger;
    }).catch(err => {
      console.error('Storage: Unable to create initial storage tables', err.tx, err.err);
  });
    }
   });
 return result;
  }
And the parameters which are going into the sql query are 👍 
authUser() {
    debugger;
    const obj = { username: this.username, password: this.password };
    console.log(obj);
    //const selector = Object.keys(obj).toString();
    const selector = this.getSelector(obj);
    const tbname = "login";
    console.log(selector);
    const parameters = this.getParametersForDB(obj);
    console.log(parameters);
    const result = this.sqlquery.get(selector, "login", parameters);
    debugger;
    result.then((data: any) => {
      console.log(data);
      if (data.res.rows.length > 0) {
        console.log(data.res.rows.length);
        this.router.navigate(['tabs', { obj }]);
      } else {
        console.log(`${data} else`);
        this.message = "You are not authorized to login";
        console.log(this.message);
              }
    });debugger;
  }

  getSelector(obj : any){
    return Object.keys(obj).toString();
  }

  getParametersForDB(obj : any){
    var res = [];
    var str;
    Object.keys(obj).forEach(function (key) {
      str = `${key}="${obj[key]}"`;
      res.push(str);
    })
    return res.toString(); 
  }
----
I am getting the error as : shared.service.ts:72 Storage: Unable to create initial storage tables SQLTransaction {} SQLError {code: 5, message: "could not prepare statement (1 near "?": syntax error)"}

Can you please help me out with the syntax?
