### ISSUE TITLE
Websql INSTR function

### ISSUE THREAD

**Issue by meghalmodi12** [brody2consult/cordova-sqlite-storage#311]
Hello,

I am using this plugin in my application. At a point i want to used INSTR() function. And because of this I am getting an error: could not execute. not authorized to execute.  Can you help me with this?

Thank you,
Meghal Modi

**Comment by brody2consult** [comment]
Please specify which platform and if you use any options in `window.sqlitePlugin.openDatabase()`.

FYI resources:
- https://www.sqlite.org/lang_corefunc.html
- http://www.w3resource.com/sqlite/core-functions-instr.php
- http://stackoverflow.com/questions/16180117/instr-function-sqlite-for-android

**Comment by meghalmodi12** [comment]
Thanks a lot. It worked...

**Comment by brody2consult** [comment]
Happy to hear. I will add this to the test suite when I get a chance.
