### ISSUE TITLE
SQLite DB version

### ISSUE THREAD

**Issue by ljammala** [brody2consult/cordova-sqlite-storage#312]
I have released a phonegap app using Sqlite plugin. I am planning to make another release with some changes to the Database tables structure. Do I have to delete the DB and recreate it with the new release?

**Comment by brody2consult** [comment]
I suggest you add a table to store your database version (if you don't have it already), and then in the new release, the Javascript checks the database in the version table and does the restructuring if it shows an old version or if the version table does not exist.

Please report whether or not this makes sense to you.

**Comment by ljammala** [comment]
Thanks for the quick response. That will be a great approach. But I did not do that for the initial release of the app which is already there in the market. So I guess I should just drop and recreate the DB in this release and use the technique you suggested for further releases.

**Comment by brody2consult** [comment]
You can check the `sqlite_master` table to see if you have the version table, and you know you have to do the upgrade if the version table is not found: http://stackoverflow.com/questions/1601151/how-do-i-check-in-sqlite-whether-a-table-exists

This is very important since it can happen that someone upgrades from the first release to a newer release further down the road.

Please confirm if this makes sense or not.

**Comment by ljammala** [comment]
Thanks a lot!!! That works great!

**Comment by brody2consult** [comment]
:+1: Planning to document this in a "tips and tricks" section or blog article, someday.

**Comment by jdnichollsc** [comment]
Nice, is a common question :D

**Comment by brody2consult** [comment]
This is now documented in README.md.

**Comment by luigi37** [comment]
If the scope is just to add a table wouldn't be this enough?

tx.executeSql("CREATE TABLE IF NOT EXISTS xyz (id INTEGER PRIMARY KEY AUTOINCREMENT, Track_ID INTEGER, Track_Name TEXT)", [],function(){console.log('all good');},function(){console.log('problem');}); 

Unfortunately it seems like it does not get executed...

Thanks
