### ISSUE TITLE
SQLite Plugin Memory Issue

### ISSUE THREAD

**Issue by nishadchenicheri** [brody2consult/cordova-sqlite-storage#319]
We have created an iOS hybrid app[Cordova IOS 3.8.0, SQLite(Cordova-SQLite-Storage) 0.8.0 Dev] and noticed that there is huge memory consumption while we perform any CRUD operations.
We tried to debug the app by enabling each feature at a time and found that the memory consumption is high when there is a SQLite plugin call. The memory consumed is never released even after we are idle for few minutes.
To ensure that the memory consumption is from the SQLite plugin, we created a new project which performed the below operations
·         as a single record,
·         as a batch operation,
·         with a loop of n records
·         with a loop of n batches

The source code is uploaded in the below Git URL,
https://github.com/nishadchenicheri/SQLite-Plugin-Memory-Issues

![screen shot 2015-08-07 at 11 58 23 am](https://cloud.githubusercontent.com/assets/13657488/9129967/ae29d5ec-3cfb-11e5-802e-e42cc9acf073.png)
,  for the sample project in this repository.
Instruments captured during analysis is also attached, for following operations,
Insert - with a (batch of 100 records each) \* 100 loop
Select - with a loop of 100

Further analysis: Found the memory consumption was less by 5 to 6 MB if the transactions are not used for db operations.

Any help on addressing this memory leak would be highly appreciated.

**Comment by brody2consult** [comment]
I am running some tests with your project, and am trying with loop of 1000 and batch of 1000. In general I notice the memory usage goes up and down. Be careful that you have to look at the _Persistent_ values and _NOT_ the _Total_ values.

**Comment by brody2consult** [comment]
This issue looks similar to #299 and #308. Please see the version in https://github.com/litehelpers/Cordova-sqlite-enterprise-free (with a different licensing scheme) for some internal memory improvements. If you continue to see memory issues please file a bug report there.
