### ISSUE TITLE
Uncaught TypeError: Cannot read property 'exec' of undefined sqliteplugin:204

### ISSUE THREAD

**Issue by daryllchu** [brody2consult/cordova-sqlite-storage#320]
Hi,

In the console I managed to open the database ondeviceready with the following:

if (window.PhoneGap) {
db = window.sqlitePlugin.openDatabase({name: "my.db", location:1});
} else {
//something else
}
However, I get an error on the phonegap emulator with "Uncaught TypeError: Cannot read property 'exec' of undefined on sqliteplugin.js:204"

any idea?

**Comment by brody2consult** [comment]
That means the `cordova` object is not defined.

**Comment by morrismukiri** [comment]
Similar problem as this
https://stackoverflow.com/questions/42470244/intel-xdk-sqliteplugin-js452-uncaught-typeerror-cannot-read-property-type
