### ISSUE TITLE
"OPEN database: test.db failed, aborting any pending transactions" when auto copying pre-populated db

### ISSUE THREAD

**Issue by admin-ideia2001** [brody2consult/cordova-sqlite-storage#321]
I'm having a simple error... "OPEN database: test.db failed, aborting any pending transactions" on android. I've done my application running with the addition of dbcopy sqlite for cordova plugin and it worked well. But now, i need to open the pre populated db from a folder location. I saw that the android's folder for databases is /data/data/package-name/databases/test.db, but while trying to open i got this log.
I've already copied the file do this location manually, and tried changing the permissions folder already, but no results. I thought that it is the default folder, any help? Thanks!

**Comment by brody2consult** [comment]
Unfortunately I cannot completely follow what you are doing. Best if you can make a sample project that can demonstrate this issue.

**Comment by dm-marimuthu** [comment]
I have faced the same issue.

The problem with installation.

Please remove your cordova-sqllite-stroge and cordova-plugin-dbcopy. And remove your platform/android folder. 

Add android platform to your app. Ionic add platform android

and Install the cordova-sqllite-stroge and cordova-plugin-dbcopy again 

now build your app and run.It will work.

**Comment by 13632225945** [comment]
Have you solved it yet?
