### ISSUE TITLE
Uncaught #<Object> at file:///android_asset/www/plugins/io.litehelpers.cordova.sqlite/www/SQLitePlugin.js:297

### ISSUE THREAD

**Issue by BilelKrichen** [brody2consult/cordova-sqlite-storage#322]
I need Help about SqlitePlugin cordova. The error shown when I charge data from json to sqlite database 

<i>JsontoSqlite.js :</i>

<b>var db;
var path = 'localhost/jsontosqlite/';
document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() 
{
       db = window.sqlitePlugin.openDatabase({name: "mydb.db"});
       db.transaction(populateDB, errorCB, successCB);
}
function errorCB(err) {
    alert("Error processing SQL: "+err.message);
}
// Success error callback
function successCB() {
       alert("success");
}
function populateDB(tx) {
       tx.executeSql('DROP TABLE IF EXISTS gamme');
       tx.executeSql('CREATE TABLE IF NOT EXISTS gamme (id integer , libelle TEXT , libelleAffiche TEXT , style TEXT , gammeParDefaut boolean , materiauId integer )');
$.getJSON(path+"gamme", function(data)
{
    $.each(data, function(i,item)
    {
             alert(item.id);
             tx.executeSql('INSERT INTO gamme VALUES (?,?,?,?,?,?)', [ item.id , item.libelle , item.libelleAffiche , item.style , item.gammeParDefaut , item.materiauID ]);
    });
});
}

The success Callback execute first then just the first item.id show and any data charged in gamme table.

**Comment by brody2consult** [comment]
This is because the transaction is already completed before your $.getJSON callback function is called.

It would be better to start the transaction within your $.getJSON callback function.

You would encounter a similar problem using HTML5/Web SQL. I will document this when I get a chance.

**Comment by BilelKrichen** [comment]
I resolve the problem when i use $.ajax
