### ISSUE TITLE
iOS: Can I replace an already-opened database?

### ISSUE THREAD

**Issue by cepm-nate** [brody2consult/cordova-sqlite-storage#324]
On Android I run openDatase, (do some stuff), DeleteDatabase, download the new DB, copy the new file to the right folder, and now actions are taking place on the new DB. The filesize stays the same, but the actions work as expected (insert, update, delete).

On iOS I tried the exact same thing (took me a while to figure out to use (location:2) and (cordova.file.dataDirectory) as the path). openDatabase, do some stuff, deleteDatabase, copy in new DB file into the right folder, and run a simple select to see if the tables showed up. They don't. 

This workflow is for users who want to do a quick "reset" of the app. Also useful for an initial load. Using this method (Download & Swap) is WAY faster than doing a download of all the rows in JSON, then loading them into an empty DB. (Think 200K+ rows). At least it's faster on Android, where it works.

My question: How can I swap out an already-opened database for a new file on iOS?

Also of note: on iOS running openDatabase, deleteDatabase, then openDatabase again returns "database already opened". I thought the plugin would recognize deleteDatabase with the same filename and close it's connection to the file. (Again, it works as expected on Android, but not on iOS)

Any ideas?

**Comment by brody2consult** [comment]
> My question: How can I swap out an already-opened database for a new file on iOS?

I recommend that you actually close the database and wait for the callback before overwriting the database file. Then you _should_ be able to open the new database file.

I am planning to add a test for this scenario.

> Also of note: on iOS running openDatabase, deleteDatabase, then openDatabase again returns "database already opened". 

Please make sure you wait for the deleteDatabase callback before you try to open the database again. There are some tests that cover this scenario.

**Comment by cepm-nate** [comment]
Thanks for the tips!

Currently each call is made in the success callback of the previous call.

First it downloads the new file to a temp location. When done, it deletes the OLD DB file (using deleteDatabase). When done, it copies the NEW DB from the temp location to the data location (same spot and same filename as OLD DB). When done with that, is where I test the openDatabase call to see if the DB is still listed as 'open'. So far it has responded with 'Already Open' on iOS.

My workaround is going to be to delete old db file, bring the new one in with a _new_ name and record the new name in localStorage, then open it. From now on out, the app will use the new database name. This way it does not matter if the plugin has bugs in this area, as I'll always be using a 'new' db file. A little bit of a workaround, but I think it has fewer chances of running into a bug.

**Comment by cepm-nate** [comment]
Aha! I found a small discrepancy which had me confused for a while.

cordova.file.dataDirectory points to "~/Library/NoCloud", but when you pass 'location:2' to the sqlite plugin, it stores it's files in "~/Library/LocalDatabase"

Interestingly, there is no cordova.file property which points to the LocalDatabase folder, so I reference it using cordova.file.dataDirectory + '../LocalDatabase'.

Why is this?

**Comment by cepm-nate** [comment]
I'm closing this issue because my workaround is to copy in the new file, then delete the old one, storing the new db name so any subsequent launches of the app use the new DB.
