### ISSUE TITLE
no such table

### ISSUE THREAD

**Issue by greatredpie** [brody2consult/cordova-sqlite-storage#331]
Hello I'm trying to use this plugin to load a prepopulated database into my phonegap app.
I have my database stored in my base www directory.
I am using build.phonegap to compile this app.
Its ether not picking up my database and is creating a new one or its not finding the table in my database. Images for reference.

DB Location
![location](https://cloud.githubusercontent.com/assets/5037470/9572006/3deeadf2-4ffc-11e5-9f8b-ff551044f92a.PNG)

DB structure 
![db](https://cloud.githubusercontent.com/assets/5037470/9572014/4b8f0f2e-4ffc-11e5-9637-ae35d9d77031.PNG)

Code
![code](https://cloud.githubusercontent.com/assets/5037470/9572076/30a4a95c-4ffd-11e5-8012-16c0e4eba546.PNG)

Error
![errordb](https://cloud.githubusercontent.com/assets/5037470/9572018/5d75f914-4ffc-11e5-987d-8d8d1d71e7f6.PNG)

**Comment by brody2consult** [comment]
Please post your project if you need help.

**Comment by ayodio** [comment]
I seem to have the exact same problem. Can you please tell us how did you solve it ?
