### ISSUE TITLE
Inserting comes to halt in ios 

### ISSUE THREAD

**Issue by Gamerakki** [brody2consult/cordova-sqlite-storage#333]
I am using ajax call to get data from the server. The data may vary from person to person. But the i am using a demo user with all table data full in web. When i get data through ajax i start the insert statement.

For few records the inserting goes fast and smooth but after a particular time the insertion comes a half. When i  press the home key and again open the app the count get increase by only 6 records. I did this task repeatedly to get whole data inserted.

i thought it might be device issue but its happeing same on all iPhone devices.
i tried on iPhone 4 and iPhone 5s

Can u suggest me a solution. I read the issue and the solutions given by people over there but i did not got a satisfied answer for ios.

The same app work fine in android and windows

**Comment by brody2consult** [comment]
Not enough information. I need a test project to reproduce this problem.
