### ISSUE TITLE
calling openDatabase second time when reloading index.html never completes

### ISSUE THREAD

**Issue by jares777** [brody2consult/cordova-sqlite-storage#335]
When the application starts, the openDatabase works fine and all the transaction go through. But if the application is restarted by hitting the refresh button in safari ( sometimes necessary during debugging as initial console logs doesn't show up) causes openDatabase being called again and it causes the openDatabase to not succeed. Further transaction reports 'new transaction waiting for open' error.

**Comment by brody2consult** [comment]
Unfortunately that is not enough information. I need you to specify which platform(s) where you see this behavior and a test program that can reproduce this issue. Thanks.
