### ISSUE TITLE
upgrade to cordova-ios 4.0

### ISSUE THREAD

**Issue by andyverbunt** [brody2consult/cordova-sqlite-storage#338]
Please upgrade the cordova-sqlite-storage plugin so it supports cordova-ios 4.0

The new cordova version finally supports WKWebView which has much better performance.
Unfortunately, there are breaking changes in the API which means all plugins need to upgrade.

Please check: https://shazronatadobe.wordpress.com/

**Comment by brody2consult** [comment]
This is because they quietly removed `Cordova/NSData+Base64.h`. This is not the first time they have broken plugins like this. I will raise a bug on Cordova.

**Comment by brody2consult** [comment]
I just filed https://issues.apache.org/jira/browse/CB-9638.

**Comment by andyverbunt** [comment]
Hi Chris,

Do you mean that this is the only breaking change regarding your plugin?
Have you looked at the API changes here?
https://github.com/apache/cordova-ios/blob/master/guides/API%20changes%20in%204.0.md

Thanks,
Andy

**Comment by brody2consult** [comment]
> Do you mean that this is the only breaking change regarding your plugin?

Yes, and I am about to disable it.

> Have you looked at the API changes here?
> https://github.com/apache/cordova-ios/blob/master/guides/API%20changes%20in%204.0.md

Thanks, none of those changes affect this plugin.

**Comment by brody2consult** [comment]
Just fixed to build with cordova-ios 4.0, please close if it works for you.

**Comment by andyverbunt** [comment]
It compiles :)
Unfortunately I cannot easily test it because I have other plugins in my app that are not yet compatible with the new API.

Can you confirm that the compilation has a lot of warnings like these?

```
/platforms/ios/HelloCordova/Plugins/io.litehelpers.cordova.sqlite/sqlite3.c:105127:24: warning: ambiguous expansion of macro 'MAX'
      [-Wambiguous-macro]
        pParse->nMem = MAX(pParse->nMem, 8+j);
```

**Comment by brody2consult** [comment]
Yes, unfortunately. Ideally, we should add the compilations flags to plugin.xml to suppress these warnings on sqlite3.c.

**Comment by andyverbunt** [comment]
Just checking ;)

Anyways, thanks for the lightning fast response.
I'll close the issue.

**Comment by bhumikapathak** [comment]
You can find solution on my blog post. http://phonegapcmsworld.blogspot.in/2016/06/warning-sqlite3c-ambiguous-expansion-of.html

Solution: add “-Wno-ambiguous-macro” into “Other C flags”
Add flag to fix all warning related to Ambiguous expansion of macro.

**Comment by bhumika** [comment]
You can find solution on my blog post. http://phonegapcmsworld.blogspot.in/2016/06/warning-sqlite3c-ambiguous-expansion-of.html

Solution: add “-Wno-ambiguous-macro” into “Other C flags”
Add flag to fix all warning related to Ambiguous expansion of macro.

**Comment by RyanTully** [comment]
Hello Chris,

I'm using sql-cipher-adapter and seeing three warnings in Xcode related to sqlite3.c. If I understand correctly from the above comments, can these be ignored?

Lexical or Preprocessor Issue
 * Ambiguous expansion of macro 'MAX'
 * Ambiguous expansion of macro 'MIN'

User Defined Issue
 * "gethostuuid() is disabled."

Unused Entity Issue
 * Unused function 'sqlite3PagerState'


Using:
cordova-sqlcipher-adapter 0.1.9
cordova 6.5.0
cordova ios 4.3.1
Xcode 8.3.2

Thanks

Ryan
