### ISSUE TITLE
use crosswalk，when executeSql ，always throw new transaction is waiting for open operation

### ISSUE THREAD

**Issue by tomisacatyet** [brody2consult/cordova-sqlite-storage#340]
i solve crosswalk+sqlite crash by this link:
https://github.com/litehelpers/Cordova-sqlite-storage/issues/336
but now when i execute sql , the log below:
SQL : select count(_) as count from chat_record where receiver_id = ? and is_read = ?
SQLitePlugin.js:105 new transaction is waiting for open operation
ionic.bundle.min.js:5 SQL : select count(_) as count, unique_identification from chat_record where receiver_id = ? and is_read = ? group by unique_identification
SQLitePlugin.js:105 new transaction is waiting for open operation

who can help solve this problem?
@brodybits 

from China , thanks

**Comment by brody2consult** [comment]
~~Please make sure you use `androidDatabaseImplementation: 2` in the openDatabase() options, as described in README.md.~~

_EDIT:_ You _may_ have to use `androidDatabaseImplementation: 2` in the openDatabase() options, as described in README.md.

**Comment by brody2consult** [comment]
I just added the native libraries that were missing. Please try it again, and try it first without `androidDatabaseImplementation: 2` in the openDatabase() options.

**Comment by tomisacatyet** [comment]
@brodybits  you mean i didn‘t open database success may cause the executeSql fail? i will try it later,thanks

**Comment by tomisacatyet** [comment]
@brodybits  thanks a lot,i update the plugin lastest,and the problem solved !!!

**Comment by brody2consult** [comment]
:+1:
