### ISSUE TITLE
Missing native driver

### ISSUE THREAD

**Issue by lcsoka** [brody2consult/cordova-sqlite-storage#342]
Hi i wanted to install this plugin via cordova but i got the following error:
..plugins/io.litehelpers.cordova.sqlite/src/android/libs/arm64-v8a/libsqlc-native-driver.so" not found!
I solved it by downloading the previous commit and unzipped the jar.

**Comment by brody2consult** [comment]
I just added the native libraries that were missing. Please try it again.

**Comment by lcsoka** [comment]
Thank you now it works.

**Comment by brody2consult** [comment]
:+1: Thanks for reporting.

**Comment by Prasanna-kumar-Patra** [comment]
Hi,

Facing a similar issue but unable to locate sqlite-native-driver.jar in the zip.

Pls suggest

Thanks

**Comment by raymatos** [comment]
Same here

**Comment by gregbarish** [comment]
Same here

**Comment by raymatos** [comment]
Fixed by getting the latest from the repo  

```
cordova plugin add https://github.com/litehelpers/Cordova-sqlite-storage
```
