### ISSUE TITLE
How to make an asynchronous transaction?

### ISSUE THREAD

**Issue by screendriver** [brody2consult/cordova-sqlite-storage#343]
I have a really large blob of JSON data that can't be handled in memory at once. So I use [Oboe.js](http://oboejs.com) to process this JSON data as a stream. Unfortunately your library handles transaction in one big transaction function:

``` js
db.transaction(function(tx) {
  tx.executeSql('DROP TABLE IF EXISTS test_table');
  // How to handle asynchronous / AJAX code here?
});
```

Is there a way to make a database transaction that can manage asynchronous code? I thought something like that:

``` js
var tx = db.beginTransaction();
// some asynchronous code that use promises for example
service.fetchData().then(function(data) {
  tx.executeSql(data);
  tx.end();
});
```

**Comment by brody2consult** [comment]
This idea is in consideration for the future. Here is a workaround that you can try, to take some extra control over the transaction mechanism.

Make the following change to SQLitePlugin.js:

``` diff
--- a/www/SQLitePlugin.js
+++ b/www/SQLitePlugin.js
@@ -110,15 +110,15 @@
   };

   SQLitePlugin.prototype.transaction = function(fn, error, success) {
     if (!this.openDBs[this.dbname]) {
       error(newSQLError('database not open'));
       return;
     }
-    this.addTransaction(new SQLitePluginTransaction(this, fn, error, success, true, false));
+    this.addTransaction(new SQLitePluginTransaction(this, fn, error, success, false, false));
   };

   SQLitePlugin.prototype.readTransaction = function(fn, error, success) {
     if (!this.openDBs[this.dbname]) {
       error(newSQLError('database not open'));
       return;
     }
```

This will cause the plugin to stop using BEGIN/COMMIT/ROLLBACK. Then you have to do something like `db.executeSql('BEGIN')` at the beginning, `db.executeSql('COMMIT')` to commit, and `db.executeSql('ROLLBACK`)` to rollback the changes since BEGIN.

Please let me know if this works for you.

**Comment by screendriver** [comment]
Thank you for the workaround. I will try it out.
Is there a roadmap or something when this feature will be available in the official release?

**Comment by brody2consult** [comment]
Unfortunately I really cannot promise anything for free right now, due to some changing priorities.

**Comment by screendriver** [comment]
All right. Should we close this issue or leave it open until this feature is implemented?

**Comment by brody2consult** [comment]
Let's leave it open. I do want to add this when I get a chance.

**Comment by screendriver** [comment]
:+1:

**Comment by Yerkon** [comment]
@brodybits hi. You wrote: 

> This idea is in consideration for the future

Is any progress on it? Thanks

**Comment by brody2consult** [comment]
Will not be done in this plugin version. Similar functionality may be possible in case of a redesign (#548).

**Comment by Yerkon** [comment]
@brodybits, I have written solution for So question https://stackoverflow.com/a/50486135/5677886. This plugin used in Ionic 3. What do you think about it? It’s ok?

**Comment by brody2consult** [comment]
Please ask in <https://github.com/litehelpers/Cordova-sqlite-help/issues>.

I would like to suggest you consider using <https://github.com/brodybits/sql-promise-helper> which provides a clean Promise-based API and can be used on browser platform as discussed in <https://github.com/brodybits/sql-promise-helper/issues/4>.

Private support is also available, please contact <sales@litehelpers.net> for more details.
