### ISSUE TITLE
Interfaced locked during inserts?

### ISSUE THREAD

**Issue by cepm-nate** [brody2consult/cordova-sqlite-storage#344]
Inside a looping insert statement I have a progress calculator which updates a percentage on the screen. in WebSQL (Chrome on Windows) this works without a problem. If I use Android or iOS native WebSQL, this also works without a problem.

When I switch to this storage plugin, the updating percentage displayed does not update until after the transaction closes.

The console shows that the update percentage function is being called correctly and at the right time (even put a psudo sleep command in there to slow it down for testing), but none of the updates make it to the interface till after the transaction closes.

To clarify, this 'update display percentage' is called on the success of each INSERT query.

Loop looks like this:
-START LOOP
-PUT VALUES INTO ARGUMENT ARRAY
-RUN INSERT STATEMENT ( on success = update percentage)
-END LOOP

Has anyone else run into this?

**Comment by brody2consult** [comment]
Please make and post a sample program that can demonstrate your issue, thanks.

**Comment by cepm-nate** [comment]
Sure thing!

Here is a test case. I use jQuery and jquery mobile to create a div on the page and then update it (you should be able to spot the areas if you need to substitute anything else)

``` javascript
function buggy_percent_test(usePlugin)  {

    var row_count = 2000;
    var insertedRowIdx = 0;
    var perc = 0;
    var oldPerc = 0;

    // Remove the popup if it exists
    $('#popupPercent').remove();

    // Create popup to show percent
    var p = $('<div id="popupPercent" style="width:100%;height:2em; position:absolute; top:20%; left:0; z-index:10000; background-color: black; color:white; font-size: 5em; text-align:center"></div>')
        .appendTo( $.mobile.activePage )
        .show();

    // Open DB
    if (usePlugin) xdb = window.sqlitePlugin.openDatabase({name: 'xdb', location: 2});
    else xdb = openDatabase('xdb', '1.0', 'my first database', 3 * 1024 * 1024);    // Initial size = 100 mb

    // Create Table
    xdb.transaction(function (tx) { 
        tx.executeSql( "CREATE TABLE IF NOT EXISTS t1(a, b UNIQUE);", [], null, onFailure);
        tx.executeSql( "DELETE FROM t1", [], null, onFailure);
    });

    // For testing purposes I'm going to assume that we can create a table within two seconds (to avoid bing in the same transaction as insert statement)
    setTimeout(function()
    {
        // Open transaction for saving
        xdb.transaction(function (tx)
        {   
            // Loop lots of rows to insert
            for(i = 0; i < row_count; i++)
            {
                // run insert sql
                tx.executeSql( "INSERT INTO t1 (a) VALUES ("+i+")", [], function(trx,rs)
                {
                    perc = Math.floor( (insertedRowIdx / row_count)*100 );

                    update_percent ( perc );    // update percent
                    console.log(insertedRowIdx, perc);
                    //var currentTime = new Date().getTime();
                    //while (currentTime + 500 >= new Date().getTime()) {}

                    insertedRowIdx++;

                }, onFailure);
            } // close FOR loop
        }); // close transaction
    }, 2000); // close delay
}
function onFailure(trx,e) 
{ 
    console.error(e.message);
}
function update_percent(newPercent) 
{
    $('#popupPercent').text(newPercent + '%');
}
```

**To test**
- Copy and paste the code into an active console on a device which has this plugin loaded.
- Run "buggy_percent_test(false)" to see it use the webview WebSQL method.
- Run "buggy_percent_test(true)" to see it use the plugin.

**What happens on my end**
- Using WebSQL: shows increasing percentage on screen and in console. 
- Using the plugin: shows percentage in console, but the screen stays black till after the loop finishes.

_Note: this is a test case program. I've found I can get way better performance through use ? and arguments, and even batching numbers of rows together, but for the sake of this test, this method works fine_

**Comment by brody2consult** [comment]
This plugin batches the transaction statements and sends them when they are ready. When the transaction statements have been executed, the plugin calls the registered sql callback functions. If any of the registered sql callback functions call `tx.executeSql()`, the plugin will collect and run the sql functions (and this can be repeated). When all sql statements in the transaction are finished, the plugin will COMMIT the transaction unless there were any unrecovered errors in which case the plugin will ROLLBACK the transaction.

We tried our best to make these transaction semantics emulate the Web SQL transaction semantics, and have been mostly successful. Your case does expose a deviation. Since Cordova does not provide a good synchronous interface between Javascript and native code, fixing this deviation would cause some other applications to suffer from performance problems.

The workaround is to issue smaller-sized transactions and update the interface at the end of each transaction.

If you do not want to commit the data until the end, see the workaround I gave to #343.

I am planning some API enhancements to help deal with these problems, cannot promise when.

**Comment by cepm-nate** [comment]
Thank you for that explanation, but I'm not sure I understand one thing: How can only part of the onSuccess callback of executeSql get called?

If you watch the log (using the code posted above), you will see that executeSql does call it's onSuccess callback without a problem. Inside that function I both a) update the displayed percentage and b) log to the console.

The console shows that onSuccess is being called correctly. But the DOM doesn't get updated to show percentage. How on earth does that work? Does console.log have a secret priority which allows it to work, even when the DOM is locked? This is what has me baffled.

Thanks!

**Comment by brody2consult** [comment]
I suspect there is an issue with how your test program interacts with the DOM, which is beyond the scope of the free support of this project.

**Comment by cepm-nate** [comment]
I appreciate the plugin and the help you have provided. Thanks!

On Wed, Sep 16, 2015 at 2:04 AM, Chris Brody notifications@github.com
wrote:

> I suspect there is an issue with how your test program interacts with the
> DOM, which is beyond the scope of the free support of this project.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/litehelpers/Cordova-sqlite-storage/issues/344#issuecomment-140678007
> .

##

**Comment by cepm-nate** [comment]
Just in case anyone else is following this issue:

In my sample app, I coded the update_percent function to look like this

```
function update_percent(newPercent) 
{
    console.log(newPercent);
    document.getElementById("popupPercent").innerHTML = newPercent + '%';    
}
```

This skips any jquery selecting method and uses straight up javascript to update the text.

This does not help. When calling buggy_percent_test(true), the on-screen percentage does not update till AFTER the transaction is complete. It still works fine when calling buggy_percent_test(false). True means use the plugin, falls means use the native WebSQL implementation.

I'm going to broaden my search to see if anyone else has ran into issues where console.log works fine, but updating the DOM does not, during interaction with a plugin.

**Comment by cepm-nate** [comment]
I dug into it by putting the 'Update this text on the screen' command throughout the sqlite plugin js file, and then into the Cordova.js file. It looks like Cordova itself suffers in that it won't update the DOM from a native received message, until all messages have been received. I'm a little surprised nobody has run into this, but perhaps it's because plugins are usually "Do this, return this" style, and not "Do this, and let me update the DOM _while_ you return messages".

Any thoughts? Has anyone else run into anything like this?

It would be VERY useful to allow the user to see the status of an ongoing insert, especially for tables with 80K+ rows and 20+ fields.

**Comment by brody2consult** [comment]
> It looks like Cordova itself suffers in that it won't update the DOM from a native received message, until all messages have been received.

It would help if you can explain this a little better.

You _could_ change the executeSql callback something like this to update the DOM from within a DOM timer event instead of a Cordova callback:

``` Javascript
                    perc = Math.floor( (insertedRowIdx / row_count)*100 );

                    setTimeout(function() {
                      update_percent ( perc );    // update percent
                    }, 0);
                    // ...
```

Not sure if this will help you at all.

Also let's not forget that none of the executeSql callbacks will be executed until the entire transaction batch is finished.

**Comment by cepm-nate** [comment]
After a little more debugging, I've come to the conclusion that you are right! :-)

All the executeSQL responses are queued up, then when the transaction is done, they are all fired.

I think there is a related bug wherein DOM updates are not processed while a transaction is in progress while using the plugin (even if outside the executeSQL callback). Plus, using the plugin is much faster in this case than the native WebSQL.

Those three things combined are what caused me to make this post, and to think i was seeing real time executeSQL callbacks, but in fact I was seeing a delayed callback both when using WebSQL and when using the SQLite plugin.

While digging into the code where Cordova processes messages then passes them to your plugin, I see that in fact there are only 3 or so callbacks that happen (in Cordova), even when doing thousands of executeSQL's in a transaction. This leads me to believe there really is no way outside of disabling transactions, or using very small transactions, to get a good progress report while inserting thousands of rows. Both of those options would be a lot slower.

I did a google search to see if 'progress of a query' was available using SQLite, and ran across this article: https://www.sqlite.org/c3ref/progress_handler.html

I have no idea if that is even possible to use with this plugin, but if so, it would be a great addition for anyone who does large inserts!

Thanks again for your work in developing this plugin!

**Comment by cepm-nate** [comment]
Here's the latest version of my testing app which clearly shows that the GUI just does not update while a transaction is in progress while using the plugin.

```
var insertedRowIdx, perc, oldPerc, row_count = 20000;
function buggy_percent_test(usePlugin)  {

    insertedRowIdx = 0, perc = 0, oldPerc = 0;
    // Remove the popup if it exists
    $('#popupPercent').remove();
    // Create popup to show percent
    var p = $('<div id="popupPercent" style="width:100%;height:2em; position:absolute; top:20%; left:0; z-index:10000; background-color: black; color:white; font-size: 5em; text-align:center"></div>')
        .appendTo( $.mobile.activePage ).show();

    // Open DB
    if (usePlugin) xdb = window.sqlitePlugin.openDatabase({name: 'xdb', location: 2});
    else xdb = openDatabase('xdb', '1.0', 'my first database', 3 * 1024 * 1024);    // Initial size = 100 mb

    // Create Table
    xdb.transaction(function (tx) { 
        tx.executeSql( "CREATE TABLE IF NOT EXISTS t1(a, b UNIQUE);", [], null, onFailure);
        tx.executeSql( "DELETE FROM t1", [], null, onFailure);
    });

    show_both('Table created.');
    setTimeout(function()   // wait two seconds
    {
        show_both('2s Delay');
        xdb.transaction(function (tx)   // Open transaction for saving
        {   
            show_both('trx open');
            for(i = 0; i < row_count; i++)   // Loop lots of rows to insert
            {
                show_both(i + ' of ' + row_count + ' sent');
                tx.executeSql( "INSERT INTO t1 (a) VALUES ("+i+")", [], function()
                {
                    perc = Math.floor( (insertedRowIdx / row_count)*100 );
                    if ( perc > oldPerc+1 ) {
                        console.log(perc);
                        document.getElementById("popupPercent").innerHTML = perc + '%';
                        oldPerc = perc+0;
                    }
                    insertedRowIdx++;

                }, onFailure);
            } // close FOR loop
        }); // close transaction
    }, 2000); // close delay
}
function onFailure(trx,e) { console.error(e.message); }
function show_both(msg) {
    document.getElementById("popupPercent").innerHTML = msg; console.log(msg);
}
```

Feel free to close this issue when you want, as it appears that it is not possible without an addition to the plugin to access the 'Progress' feature of SQLite.

**Comment by brody2consult** [comment]
Thanks for reporting your results. About using `sqlite3_progress_handler()`, I suspect it will show the progress of each _individual_ sql statement which is _not_ what we really want.

I am planning some API enhancements in the future that _may_ help.

**Comment by cepm-nate** [comment]
I'll look forward to whatever improvements come along! Thanks again for the good support on this plugin.
