### ISSUE TITLE
Best way to debug executed sql?

### ISSUE THREAD

**Issue by postb99** [brody2consult/cordova-sqlite-storage#350]
Hi,

I use a transaction with error and success callback functions defined.
I execute sql using `executeSql` function of the `tx` transaction object.

What's the best function to put logging the sql query I execute in, so as not to get poor performance/too verbose code? Of course I want this debug mode to be configurable.

Thanks,

**Comment by brody2consult** [comment]
For per-statement debugging: `SQLitePluginTransaction.prototype.executeSql` or `SQLitePluginTransaction.prototype.addStatement`

The transactions are actually run in: `SQLitePluginTransaction.prototype.run`
