### ISSUE TITLE
Not working in IOS 9

### ISSUE THREAD

**Issue by iosdroid** [brody2consult/cordova-sqlite-storage#353]
I have develop application using this plugin. its working in android and ios 8.4. not working in ios 9

**Comment by brody2consult** [comment]
Can you please be specific about what is wrong with the behavior in iOS 9 and post any log output you may have?

**Comment by iosdroid** [comment]
sorry its a security issue.Thanks for your reply

**Comment by medindm** [comment]
Hi @iosdroid,

I did encounter this issue hoping you can help me with the security issue you've change in ios.

Thanks!
