### ISSUE TITLE
Working Example [with pre-populated database]?

### ISSUE THREAD

**Issue by jamesbyrneiitd** [brody2consult/cordova-sqlite-storage#356]
Hi,

is there a working example that I can directly compile?

I know html/css and have a very limited javascript experience. Going through this tutorial went over my head.

I need to build an app with offline prepopulated database for Android, iOs, Windows & Blackberry. Android and iOS being the priority. Simple features such as Listing, Read in Details with Prev & Next function, Search function.

A working example with be awesome. I can learn if someone could point me to the right direction with basic step by step instructions. There's no way i could understand this documentation :(

**Comment by lucascardoso** [comment]
Hello, maybe this example will help you.
[Ionuc tutorual poucjdb](https://github.com/ashteya/ionic-tutorial-pouchdb)

**Comment by brody2consult** [comment]
For a working example please see the following section: https://github.com/litehelpers/Cordova-sqlite-storage#quick-installation-test

For pre-populated database, I made https://github.com/brodybits/Cordova-pre-populated-db-example-android based off Cordova 2.7, will update for Cordova 4.x/5.x when I get a chance.

**Comment by jdnichollsc** [comment]
My example for pre-populated database using Ionic Framework, ngCordova and promises => https://gist.github.com/jdnichollsc/9ac79aaa3407e92677ba

@brodybits this plugin works with Windows 10 using pre-populated database?

Regards, Nicholls

**Comment by brody2consult** [comment]
Thanks for the sample. Pre-populated database support has been moved to https://github.com/litehelpers/cordova-sqlite-ext and is also included for Windows "Universal". As I said in #385 and #272, I recommend that you build your app for Windows 8.1 and Windows Phone 8.1 then it _should_ work for Windows 10 as well.

**Comment by jdnichollsc** [comment]
@brodybits  Ohh very interesting, I'll try.

@jamesbyrneiitd see my group on facebook => https://www.facebook.com/groups/phonegapcordova/

Thanks for your reply! :dancers:

**Comment by brody2consult** [comment]
Moved to litehelpers/cordova-sqlite-ext/issues/7

**Comment by jjab2020** [comment]
Hello friend any example to use your new great plugins for prepopulated sqlite database for Windows phone 10 or 8.1 version thanks
Have a great time.

**Comment by brody2consult** [comment]
I recently published a starter project for pre-populated databases at: https://github.com/brodybits/cordova-sqlite-ext-bootstrap-starter-app
