### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by mauricioac** [brody2consult/cordova-sqlite-storage#358]
So, we have an app, and among other data, we're storing some images as base64 along with other serialized data.
After inserting about 80 images (not sure how much actually is causing error) as base64 in db, we reload app and it crashes on initialization...

```
threadid=18: thread exiting with uncaught exception (group=0x40a3f1f8)
E/AndroidRuntime( 3039): FATAL EXCEPTION: pool-1-thread-2
E/AndroidRuntime( 3039): java.lang.OutOfMemoryError
E/AndroidRuntime( 3039):    at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
E/AndroidRuntime( 3039):    at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:132)
E/AndroidRuntime( 3039):    at java.lang.StringBuilder.append(StringBuilder.java:124)
E/AndroidRuntime( 3039):    at org.json.JSONStringer.string(JSONStringer.java:344)
E/AndroidRuntime( 3039):    at org.json.JSONStringer.value(JSONStringer.java:252)
E/AndroidRuntime( 3039):    at org.json.JSONObject.writeTo(JSONObject.java:667)
E/AndroidRuntime( 3039):    at org.json.JSONStringer.value(JSONStringer.java:237)
E/AndroidRuntime( 3039):    at org.json.JSONArray.writeTo(JSONArray.java:572)
E/AndroidRuntime( 3039):    at org.json.JSONStringer.value(JSONStringer.java:233)
E/AndroidRuntime( 3039):    at org.json.JSONObject.writeTo(JSONObject.java:667)
E/AndroidRuntime( 3039):    at org.json.JSONStringer.value(JSONStringer.java:237)
E/AndroidRuntime( 3039):    at org.json.JSONObject.writeTo(JSONObject.java:667)
E/AndroidRuntime( 3039):    at org.json.JSONStringer.value(JSONStringer.java:237)
E/AndroidRuntime( 3039):    at org.json.JSONArray.writeTo(JSONArray.java:572)
E/AndroidRuntime( 3039):    at org.json.JSONArray.toString(JSONArray.java:544)
E/AndroidRuntime( 3039):    at org.apache.cordova.PluginResult.<init>(PluginResult.java:46)
E/AndroidRuntime( 3039):    at org.apache.cordova.CallbackContext.success(CallbackContext.java:90)
E/AndroidRuntime( 3039):    at io.liteglue.SQLitePlugin.executeSqlBatch(SQLitePlugin.java:594)
E/AndroidRuntime( 3039):    at io.liteglue.SQLitePlugin.access$100(SQLitePlugin.java:41)
E/AndroidRuntime( 3039):    at io.liteglue.SQLitePlugin$DBRunner.run(SQLitePlugin.java:853)
E/AndroidRuntime( 3039):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime( 3039):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime( 3039):    at java.lang.Thread.run(Thread.java:856)
```

**Comment by mauricioac** [comment]
Oh, and this is happening with the normal sqlite plugin and on the enterprise free version...

**Comment by brody2consult** [comment]
1. Memory problems will be fixed in the free enterprise version only.
2. It is recommended to store images as files using the File API and store the _reference_ in the database.

**Comment by mauricioac** [comment]
Our backend is stored as JSON with a lot of nested data, I wanted to keep that structure, and not break up into lots of tables.

I just hit the issue with base64 encoded images while testing offline sync, but the issue is any large-ish string/json. Would putting all data in normal tables (i.e not using a single column for serialized data), make the JsonStringer not blow up and crash? What's the limit of string size in a column?

I tried putting the column type as text and blob. My first thought was that they had pretty "high" limits, but they don't... both give up.

The insert part is ok. I then reload app, and do like a count query on that table, with serialized data, and it crashes. Does sqlite load everything to RAM in order to do a count query?

**Comment by MrPayon** [comment]
Hi,

I am in the same situation
My app have only 4 tables and just 1 line by table to store JSON data : 
- I launch my app (first time) => get data from online database in JSON with images (base64) : INSERT query OK
- I close my app (close process).
- I open my app a second time => crash with "java.lang.OutOfMemoryError" with my SELECT query on local data.

Use File API is not a option for me. :/
Thanks in advance for your help.

**Comment by danielehrhardt** [comment]
Is there a fix for this?

**Comment by mauricioac** [comment]
Well, we couldn't afford to keep investigating a possible fix, so we did what the author recommended, and stored images in proper files, and also made tables for all the data instead of nested json.

It's a lot more work, but never saw memory issues again.
