### ISSUE TITLE
Error callback not fired

### ISSUE THREAD

**Issue by screendriver** [brody2consult/cordova-sqlite-storage#365]
I've got a SQLite table with some NOT NULL constraints. If I want to insert some data and forget to fill these column values it happens nothing. If I try to make the insert statement in my desktop SQLite tool it tells me something like `NOT NULL constraint failed` but if I make the same request with the cordova plugin the error callback isn't called. The same for inserts in tables that does not exist.

I can provide you an example if you want.

**Comment by brody2consult** [comment]
An example would be really helpful.

**Comment by screendriver** [comment]
Hmm sorry my bad. I've made a wrapper around the transactions and it seems that there is a :beetle:
