### ISSUE TITLE
Meaningless error code [error messages]

### ISSUE THREAD

**Issue by screendriver** [brody2consult/cordova-sqlite-storage#366]
I am getting wrong respectively meaningless error messages in my error callback. For example: I made a typo in my insert statement: `INSERTt into...`. Usually I get a syntax error in SQLite but in this cordova plugin I get a `{message: prepare statement failed with error: 1, code: 0}`. I can't really see what's going wrong. Same for not null constraints that must be fulfilled.

**Comment by brody2consult** [comment]
The message indicates to me that you are using the Android version. In this case, the sqlite error code is simply included within the error message.

**Comment by screendriver** [comment]
Yes, I am using the Android version. Hmm the only thing I get is `{message: prepare statement failed with error: 1, code: 0}`. So I have to check the error code and compare it with [SQLite Result Codes](https://sqlite.org/c3ref/c_abort.html)?

And why it tells me `error: 1` but `code: 0`? By the way: [SQLite Result Codes](https://sqlite.org/c3ref/c_abort.html) seems a little bit to generic.

**Comment by brody2consult** [comment]
The error `code` member is bogus on the Android and Windows platforms, marked in README.md.

**Comment by screendriver** [comment]
Hmm ok. So there is no way to indicate what error exactly occurred?

**Comment by brody2consult** [comment]
I will look into it later this week. According to the Web SQL spec `code` should be `5` in case of a syntax error or `6` in case of a constraint violation.

**Comment by screendriver** [comment]
Ok thank you.

**Comment by brody2consult** [comment]
This is now fixed in the default branch of this project as described in #121. This is still an issue for Windows (#539) to be fixed in the near future. The fixes will be propagated to the evcore and future (non-legacy) evplus versions.
