### ISSUE TITLE
Backing up data files to iCloud

### ISSUE THREAD

**Issue by arafath-mk** [brody2consult/cordova-sqlite-storage#369]
How do I backup my data saved by Cordova-sqlite-storage plugin to iCloud?
Is it possible? I heard that, if I backup my sqlite data, then Apple will reject my application. Is it true?

**Comment by brody2consult** [comment]
If someone with an iCloud subscription setup on a device and runs your app, the data is backed up to iCloud unless either the file has the excluded from backup flag set or is stored in a directory that has the excluded from backup set. By default, this plugin stores the database in the `Documents` subdirectory, which is backed up. If you set the `location` option to `2` as described in README.md then the plugin stores the database in the `Library/LocalDatabase` subdirectory, which has the excluded from backup flag set and will not be backed up.

**Comment by brody2consult** [comment]
I cannot really say anything about what Apple will accept or reject. Another thing is that according to the document at https://cordova.apache.org/docs/en/5.1.1/guide/platforms/ios/config.html a Cordova app has iCloud backup enabled **by default** (which I think is wrong) and tells you how to change it.

**Comment by arafath-mk** [comment]
I haven't specified `location` expecting it to use default value and create data files under `Documents`, but it doesn't create there, instead it always creates under `Library\WebKit\LocalStorage`.

Also, I have specified `BackupWebStorage` in config.xml as below:

```
<preference name="BackupWebStorage" value="cloud"/>
```
