### ISSUE TITLE
Error possible transaction database locking

### ISSUE THREAD

**Issue by codemonkeyneo** [brody2consult/cordova-sqlite-storage#372]
Recently my mobile application stopped inserting records locally , not sure what changed but going over the code its still the same and all I can think is the speed at which the data is running through a few steps I have in a database sync procedure.

Basically I have a global variable to the database ;

```
app.db = window.sqlitePlugin.openDatabase({name: "my.db", createFromLocation: 1});
```

I tried a few options for Android to avoid locking as per readme , but the issue happens on the iPhone also... Im assuming its the speed of the transaction and things not waiting to complete but really usure how i can get around it.... is there away to auto close the transaction after a statement ?

and then in the procedure I make a call as follows ;

```
app.db.transaction(function(tx) {
  tx.executeSql("INSERT INTO REF_CropGroups(CropGroupId, CropGroupName) VALUES(?,?) ;", [item.crop_group_id, item.name], function(tx, res) { },
              function(e) {
                console.log(JSON.stringify(e));
              });
});
```

I don't really get a details error message , but if I output e the string shows that txlock is true;

{"db":{"openargs":{"name":"wue.db","createFromLocation":1,"dblocation":"docs","createFromResource":"1"},"dbname":"my.db"},"txlock":true,"readOnly":false,"executes":[]}

Any help fixes or worksarounds would be appreciated.

Cheers

Neil

**Comment by codemonkeyneo** [comment]
Just noticed that I can get extra error message

```
statement error callback did not return false: finish failed with error: 19 
```

by adding additional function to transaction call. so for inert updates do I need to return a value ?

I also noticed that it doesnt matter what my Insert statements says as it will error out anyway from what seems to be the txlock....oh man!!!!!!!

**Comment by brody2consult** [comment]
That looks really strange. I suspect that it takes a while for the openDatabase call to copy the database file and then open it. You may want to wait for the openDatabase success callback to be fired before attempting any sql access.

SQLite error 19 indicates a constraint violation.

**Comment by codemonkeyneo** [comment]
I also noticed the application has some other strange behaviours... I'm going to rollback as I updated CrossWalk (maybe this causing my issues) in order to see if I could fix an issue with Samsung Edge x64....

The code and database connections have all been fine previously... I will update with more information tomoz...The strange thing is it works for other calls just before and then errors out before even trying to do other statements. thanks for coming back @brodybits .

**Comment by codemonkeyneo** [comment]
So pulling my hair out not understanding whats changed... went back to old code and problem was still there.....

Only recent hting is updated to Marshmallow on android ( but doesnt explain same issue on iphone ).

I have worked around it by altering my insert statements to ...

```
INSERT OR IGNORE etc etc .....
```

Which when I query the database everything is in there all good.... so my assumption is maybe its trying to do insert twice and cause a violation...  I'm going to try and setup a test app to emulate issue but happy for this to be closed for now... just hope INSERT OR IGNORE STATEMENT helps someone else ...

Cheers

Neil

**Comment by codemonkeyneo** [comment]
more testing and this may sound strange but , if i have  a global variable and open the db when I do inserts it tries twice... if I open db locally to functions then inserts once.... explains my above errors of constraints at least

**Comment by brody2consult** [comment]
This sounds _really_ strange. It would help if you can make a test program that demonstrates the issue.
