### ISSUE TITLE
Query inserted but not inserted...

### ISSUE THREAD

**Issue by igarpoor** [brody2consult/cordova-sqlite-storage#373]
Hi,

On iOS i insert a query and can get the inserted id with "results.insertId" but when i browse the records of the table, my table is empty, how come?

On android it is ok.
On iOS with the native sqlite database it is also ok.
I build the app with the version 0.7.7.

If someone have an idea.

Thanks,
Sebastian.

**Comment by brody2consult** [comment]
What do you mean by "browse the records of the table"?

Please try the latest version and make a simple test program that inserts the record, then select from the table in a new transaction and show the results (in either a log or an alert).

**Comment by igarpoor** [comment]
Umm sorry for accusing your plugin, it was a code in the callback that make the transaction fail...
Now i have to find why my code doesn't work in a builded iOS app.
Thank you for your work :)
