### ISSUE TITLE
Version 0.7.7 is unavaliable at registry.cordova.io

### ISSUE THREAD

**Issue by horochovec** [brody2consult/cordova-sqlite-storage#375]
The last version avaliable at registry.cordova is 0.7.5

**Comment by brody2consult** [comment]
Please use nom for this and other Cordova plugins. Will be documented in README.md.

**Comment by horochovec** [comment]
cordova plugin add cordova-sqlite-storage

horochovec: mediaglobe$ cordova plugin list
cordova-sqlite-storage 0.7.11 "Cordova sqlite storage plugin"
