### ISSUE TITLE
WP8 open database successful, but failed when issue the first select call

### ISSUE THREAD

**Issue by iosdevelopergithub** [brody2consult/cordova-sqlite-storage#377]
Hi,

I am using Cordova 5.3.3, AngularJS with this SQLite plugin for this hybrid app, the code base works in IOS and Android, however for WP8 the first page loads up but it is failing on the first SELECT statement, here's the log

'TaskHost.exe' (CoreCLR: DefaultDomain): Loaded 'C:\windows\system32\mscorlib.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Windows.RuntimeHost.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Windows.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Net.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Xml.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\Data\Programs{A526EAE0-7C05-11E5-9309-C709804D58C1}\Install\io.cordova.CT6WP.DLL'. Symbols loaded.
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\Microsoft.Phone.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\Microsoft.Phone.Interop.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\WinMetadata\Windows.winmd'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Xml.Linq.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Core.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Adding feature.value=Notification
Adding feature.value=Vibration
Adding feature.value=SQLitePlugin
Adding feature.value=SplashScreen
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\en-US\mscorlib.debug.resources.dll'. Module was built without symbols.
Exception thrown: 'System.IO.IsolatedStorage.IsolatedStorageException' in mscorlib.ni.dll
Updating IsolatedStorage for APP:DeviceID :: 2fa16686-9dd9-4868-896a-97179baac089
CordovaBrowser_LoadCompleted
Apache Cordova native platform version 3.8.1 is starting
CordovaBrowser_LoadCompleted
Apache Cordova native platform version 3.8.1 is starting
OPEN database: 6WP.db
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.ServiceModel.Web.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Runtime.Serialization.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Database opened successfully
Executing SELECT \* FROM Configs with bindings : %o,[]
new transaction is waiting for open operation
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Runtime.InteropServices.WindowsRuntime.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
DB opened: 6WP.db
Exception thrown: 'SQLite.SQLiteException' in io.cordova.CT6WP.DLL
The thread 0x56c has exited with code 0 (0x0).
Error when executing query : %o,{"message":"no such table: Configs","code":0}
The thread 0xb20 has exited with code 0 (0x0).

Here's the SQLite service that I am using
CT6App.factory('DB', function($q) {
    var db=null;
    return {
        init: function () {
            db=window.sqlitePlugin.openDatabase({name:"6WP.db", createFromLocation:1});
            console.log("Database opened successfully");
        },
        query: function(query, bindings) {
            bindings = typeof bindings !== 'undefined' ? bindings : [];
            var deferred = $q.defer();

```
        console.log("Executing "+query+" with bindings : %o", bindings);

        db.transaction(function(transaction) {
            transaction.executeSql(query, bindings, function(transaction, result) {
                console.log("Finished executing query");
                deferred.resolve(result);
            }, function(transaction, error) {
                console.log("Error when executing query : %o", error);
                deferred.reject(error);
            });
        });
        return deferred.promise;
    },
    fetchAll: function(result) {
        var output = [];
        for (var i = 0; i < result.rows.length; i++) {
            output.push(result.rows.item(i));
        }
        console.log("Returning %o", output);        
        return output;
    },
    fetch: function(result) {
        console.log("Returning %o",result.rows.item(0));
        return result.rows.item(0);
    }
}
```

})
....
.factory('Configs', function(DB) {
    return {
        all: function() {
            DB.init();
            return DB.query('SELECT \* FROM Configs')
            .then(function(result) {
                return DB.fetchAll(result);
            })
        },

**Comment by brody2consult** [comment]
The code tries to read from a pre-populated database, but pre-populated databases are NOT supported on WP8.

**Comment by iosdevelopergithub** [comment]
Thanks for your response Brody.

So, if WP8 does not support using pre populated database and since the DB file is ready, what are my option?

Should I export the DB file as SQL and ran it through, but I have a lots of metadata, so a really long SQL file, so should i use the openDatabase call to create a blank db first, then run the massive SQL in one shot?

Or is there any way in WP8 that I can use the openDatabase call to create the file first, then manually open that file and use some GUI tool to run the SQL myself? Or it's not possible becuz the DB lives in local storage only?

Thanks.

**Comment by brody2consult** [comment]
> Should I export the DB file as SQL and ran it through, but I have a lots
> of metadata, so a really long SQL file, so should i use the openDatabase
> call to create a blank db first, then run the massive SQL in one shot?

I am thinking that is your best option. It _may_ save you some effort to
convert the dump to a very dumb, simple JSON file that you would read (I
suspect there should be plenty of tools out there and the overhead should
not be too bad). Another idea may be to compress it somehow (again I
suspect you can find a pure-Javascript decompression library).

> Or is there any way in WP8 that I can use the openDatabase call to create
> the file first, then manually open that file and use some GUI tool to run
> the SQL myself?

I have to say I cannot understand why you would want to consider this.

**Comment by iosdevelopergithub** [comment]
Brody,

Thanks a lot for your help and making this plugin.

**Comment by iosdevelopergithub** [comment]
Brody,

So I followed your advice, I am trying to initialize the database but still getting the same error
CordovaBrowser_LoadCompleted
Apache Cordova native platform version 3.8.1 is starting
CordovaBrowser_LoadCompleted
Apache Cordova native platform version 3.8.1 is starting
Local Storage : null
OPEN database: 6WP.db
Executing SQL :BEGIN TRANSACTION; CREATE TABLE `WorkoutVALUES (4,'Machine Row');
..................... ( I have a hugh SQL with a lot of metadata, so not gonna bore you with details )
COMMIT;
new transaction is waiting for open operation <-- Here's showing 
Database opened successfully
Executing SELECT \* FROM Configs with bindings : %o,[]
new transaction is waiting for open operation
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Runtime.InteropServices.WindowsRuntime.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
DB opened: 6WP.db
Exception thrown: 'System.InvalidOperationException' in io.cordova.CT6WP.DLL
Exception thrown: 'SQLite.SQLiteException' in io.cordova.CT6WP.DLL
Exception thrown: 'SQLite.SQLiteException' in io.cordova.CT6WP.DLL
Error when executing query : %o,{"message":"no such table: Configs","code":0}

Here's my new init function

   return {
        init: function () {
            //Check for the marker file.
            console.log("Local Storage : "+ $window.localStorage.getItem('init'));
            db=$window.sqlitePlugin.openDatabase({name:"6WP.db", createFromLocation:1});
            if ($window.localStorage.getItem('init') == null) {
                console.log("Initializing DB with %o", db.transaction);
                console.log("Executing SQL :" + sql);
                db.transaction(function(transaction) {
                    transaction.executeSql(sql,[], 
                        // Successful callback
                        function(transaction, resp) {
                            console.log("Finished initializing DB : %o", resp);
                            deferred.resolve(resp);
                            $window.localStorage.setItem('init')=true;
                        },
                        // Error callback
                        function(transaction, error) {
                            console.error("Error when initializing DB : %o", error);
                            deferred.reject(error);
                        }
                        );
                });
            }
            console.log("Database opened successfully");
        },

The rest is the same as above.

Any pointers? Am I not using your plugin correctly?

Thanks in advance

**Comment by brody2consult** [comment]
The log shows that you do create a "WorkoutVALUES" table, but the exception in the log:

```
Exception thrown: 'System.InvalidOperationException' in io.cordova.CT6WP.DLL
Exception thrown: 'SQLite.SQLiteException' in io.cordova.CT6WP.DLL
Exception thrown: 'SQLite.SQLiteException' in io.cordova.CT6WP.DLL
Error when executing query : %o,{"message":"no such table: Configs","code":0}
```

shows that you are trying to do something on a "Configs" table that does not exist.

Before you ask for help again, please check your work very carefully and make a small, test project that does not include Ionic or any other form of ngCordova. Please be sure to enclose code blocks as follows

``````
```Javascript
// here is my Javascript
```
``````

and output as follows

``````
```
some output
```
``````

I am extremely busy with both paid and free project work and do not have time to help people debug their own code. Thanks!
