### ISSUE TITLE
First and second select is very slow

### ISSUE THREAD

**Issue by EricDosReis** [brody2consult/cordova-sqlite-storage#381]
I have a table with 518 rows and it's very slow in the first and second select. My select contains only two properties: ID and NAME.

The first select takes more than 20 seconds, and the second takes more than 10 seconds, but the third takes an average of 800ms.

**Comment by brody2consult** [comment]
If you attempt to execute any transaction(s) on a database object before it has been successfully opened, the transaction(s) will wait until the database is successfully opened. It is recommended to wait for the openDatabase success callback before attempting any transactions. I will document this tip when I get a chance.

**Comment by EricDosReis** [comment]
Thank you for your reply. 

I'm already doing this. We are developing an app with Ionic, Cordova and Angular, see our DAO Factory below:

``` javascript
(function() {
    'use strict';

    angular
        .module('factories')
        .factory('DAOFactory', DAOFactory);

    DAOFactory.$inject = ['$cordovaSQLite', '$q', '$ionicPlatform'];

    function DAOFactory($cordovaSQLite, $q, $ionicPlatform) {
        var self = this;

        self.db = null;

        self.init = function() {
            $ionicPlatform.ready(function() {
                self.db = $cordovaSQLite.openDB("upwayCrm.db");

                $cordovaSQLite.execute(self.db, "CREATE TABLE IF NOT EXISTS user (id integer primary key, username text, name text, fk_usergroup integer, fk_empresa integer, company text)");
            });

            console.info(self.db);
        }

        self.createTable = function(table, tableColumns) {
            var columns = [];
            for (var column in tableColumns)
                columns.push(column + " " + tableColumns[column]);

            var sql = "CREATE TABLE IF NOT EXISTS " + table + " (" + columns.join() + ")"

            return $cordovaSQLite.execute(self.db, sql);
        }

        self.query = function(query, parameters) {
            parameters = parameters || [];
            var q = $q.defer();
            $ionicPlatform.ready(function() {
                $cordovaSQLite.execute(self.db, query, parameters)
                    .then(function(result) {
                        q.resolve(result);
                    }, function(error) {
                        console.warn('Erro no acesso ao banco de dados!');
                        console.warn(error);
                        console.info(arguments);
                        q.reject(error);
                    });
            });

            return q.promise;
        }

        self.getAll = function(result) {
            var output = [];

            for (var i = 0, count = result.rows.length; i < count; i++)
                output.push(result.rows.item(i));

            return output;
        }

        self.getById = function(result) {
            return result.rows.item(0);
        }

        self.buildSQLColumns = function(objTableColumns) {
            return Object.keys(objTableColumns).join();
        }

        self.buildValueColumns = function(tableColumns, objValueColumns) {
            var value = [];

            for (var column in tableColumns)
                value.push(objValueColumns[column]);

            return value;
        }

        self.buildSQLColumnsUpdate = function(objTableColumns) {
            var columns = [];
            for (var column in objTableColumns)
                columns.push(column + " = (?)");

            return columns.join();
        }

        self.buildSQLColumnsValueInsert = function(objTableColumns) {
            var value = [];

            for (var column in objTableColumns)
                value.push("?");

            return value.join();
        }

        return self;
    }
})();
```

**Comment by brody2consult** [comment]
When I look through your code, we see that the `self.init` function opens the db object and _immediately_ attempts a transaction to create the table (if it does not exist). Also the `self.query` function attempts to query the db object _immediately_ on the `$ionicPlatform.ready` callback.

**Comment by EricDosReis** [comment]
Yes, but it's bad or good? Do you can say a better way?

Thank you.

**Comment by brody2consult** [comment]
It is ok to attempt the transaction _immedately_ after the openDatabase call, but then there is no way to know how long it will take.

Unfortunately I am not so experienced with Angular, but there are plenty of resources available to help you learn. Also for Web SQL API, which this project partially emulates on a database that is opened using window.sqlitePlugin.openDatabase.

**Comment by EricDosReis** [comment]
Sorry, our implementation was wrong.

When the user logs into the application, the database is populated. This action takes some time to complete and any query was very slow because the database was not populated.

**Comment by ozexpert** [comment]
is there a way to avoid this problem?

**Comment by EricDosReis** [comment]
Yes, we have created a view with a progress that hides when the populate is complete.

See the print:

![progress](https://cloud.githubusercontent.com/assets/6003424/11897118/de547a16-a573-11e5-8430-8d84a39afda1.png)

**Comment by ozexpert** [comment]
Thanks for the clue @EricDosReis I'm doing a dummy db open and select and once done i show the progress 100%.
