### ISSUE TITLE
Windows Store certification failed

### ISSUE THREAD

**Issue by sandrine-quadient** [brody2consult/cordova-sqlite-storage#384]
Hi, 

My application works well with sqlite plugin, but when I try to pass Windows Store certification, it fails and I have the following errors :
- The type SQLite3.Database in file SQLite3.winmd contains the inconsistently cased methods Close and close. Overloaded methods must use identical casing.
- The overloaded methods Close of type SQLite3.Database in file SQLite3.winmd have the same number of in parameters without one that has DefaultOverloadAttribute. Exactly one method overload must have DefaultOverloadAttribute.

Do you have any idea ?

Thank you for your help.

**Comment by brody2consult** [comment]
Thanks for reporting. I expect to have a fix in the next 1-2 hours or so.

**Comment by brody2consult** [comment]
I just published a new release to fix this issue. Please confirm if the certification is OK or not.

**Comment by sandrine-quadient** [comment]
Certification is now OK. Thank you.

**Comment by brody2consult** [comment]
Happy to hear!

**Comment by jdnichollsc** [comment]
Cool! :dancers:
