### ISSUE TITLE
Plugin broken on Android 4.1?

### ISSUE THREAD

**Issue by canadaka** [brody2consult/cordova-sqlite-storage#388]
I was trying to build our app on the old version of Android and the app wasn't working. Logcat shows the folowing.

```
V/sqlg: prepare db 0x2a455750 sql INSERT INTO search_ft (rowid, title) SELECT 10000000 + id, title FROM trails_search;
W/System.err: java.sql.SQLException: prepare statement failed with error: 1
```

But it was working fine a month ago, I was pulling my hair out. Then I decided to try an older version of this plugin and sure enough everything worked fine after.

I reverted to 0.7.8 https://github.com/litehelpers/Cordova-sqlite-storage/releases/tag/0.7.8
The newest 0.7.13 seems to have issues on Android 4.1, it works fine on Android 5.1

**Comment by brody2consult** [comment]
The error message indicates that you were using a development version. You may want to try the latest release again. You can also try the `androidDatabaseImplementation` option as described in README.md.

It would be really helpful if you can post a small test program that can demonstrate the issue on Android 4.1.
