### ISSUE TITLE
Error during the installation of the plugin

### ISSUE THREAD

**Issue by jreynerio** [brody2consult/cordova-sqlite-storage#391]
Hello, last week install the plugin on my project and it worked perfect, but since yesterday I'm trying to reinstall on another project and is giving me the following error

Error during processing of action! Attempting to revert ...
Failed to install 'Cordova-storage-sqlite': Error: Uh oh!
"C: \ projects \Project Name ..................... \ plugins \ Cordova-sqlite-storage \ src \ android \ libs \ arm64-V8A \ libsqlc-native-driver.so" not found!

Is there any error in the new version of the plugin that you upload a few days ago in the repository? or the error is in my work environment?

Greetings and thanks for the help

**Comment by squio** [comment]
Whoops, same here! New project (no previous installs of this plugin), installation from npm using the command `cordova plugin add cordova-sqlite-storage`. 

Same error message: plugins/cordova-sqlite-storage/src/android/libs/arm64-v8a/libsqlc-native-driver.so" not found!` 

Cordova version 5.4.0; Installed platforms: android 4.1.1, browser 4.0.0, ios 3.9.2

Update: installing previous version works: `cordova plugin add cordova-sqlite-storage@0.7.12`

```
Fetching plugin "cordova-sqlite-storage@0.7.12" via npm
Installing "cordova-sqlite-storage" for android
Installing "cordova-sqlite-storage" for browser
Installing "cordova-sqlite-storage" for ios
```

**Comment by jreynerio** [comment]
Thnks Squio ! , antoher way  is clone the project from https://github.com/litehelpers/Cordova-sqlite-storage.git and install the plugin directly form your machine, works with the last version.

**Comment by brody2consult** [comment]
For some reason, when I do `nom publish .`, it seems to add `src/android/libs/.npmignore` with `*.so`. I will investigate this one.

**Comment by brody2consult** [comment]
This should now be fixed, please report if this is a problem.

**Comment by squio** [comment]
Verified: fixed.

```
$ cordova plugin remove cordova-sqlite-storage
Uninstalling cordova-sqlite-storage from android
Uninstalling cordova-sqlite-storage from browser
Uninstalling cordova-sqlite-storage from ios
Removing "cordova-sqlite-storage"

$ cordova plugin add cordova-sqlite-storage
Fetching plugin "cordova-sqlite-storage" via npm
Installing "cordova-sqlite-storage" for android
Installing "cordova-sqlite-storage" for browser
Installing "cordova-sqlite-storage" for ios

$ cordova plugin ls
...
cordova-sqlite-storage 0.7.14 "Cordova sqlite storage plugin"
```

Thanks!!!
