### ISSUE TITLE
Cache and size limitation

### ISSUE THREAD

**Issue by appsystemstaff** [brody2consult/cordova-sqlite-storage#394]
I use this plugin https://build.phonegap.com/plugins/876. The sqlite database created by Cordova-sqlite-storage plugin is removed when taking cache clear. 

Any size limitation for the database created by this Cordova-sqlite-storage plugin? Are the databases stored in the browser cache or in a sqlite sql file?  

Thanks for your reply.

**Comment by brody2consult** [comment]
The database is stored in a sqlite file in the standard database directory (Android) or documents directory (iOS & Windows "Universal"), _never_ in a cache directory. In addition, neither this plugin nor the underlying SQLite database implementation enforce any size limitations.

I highly recommend that you add plugins from npm as announced at: http://phonegap.com/blog/2015/05/26/npm-plugins-available/

https://build.phonegap.com/plugins is now deprecated and becoming obsolete.

If you continue to face this problem, please specify the platform(s) where you see this issue and make a minimal test program to demonstrate it without any large frameworks such as Angular/ngCordova/Ionic, React, etc.
