### ISSUE TITLE
Disk I/O error when device is locked

### ISSUE THREAD

**Issue by sriram275** [brody2consult/cordova-sqlite-storage#395]
Hi,
I get the following error if I write to the database when the device is locked and after unlock.

**_an unknown error was returned: {"result":{"message":"disk I/O error"}}**_

Thanks.

**Comment by brody2consult** [comment]
Unfortunately that is not enough information. Please specify which target platform (Android/iOS/WP8/Windows "Universal") and which options you used to `sqlitePlugin.openDatabase`. I may need a small test program to reproduce your issue. This information is already requested in README.md.

**Comment by sriram275** [comment]
Hi,
I am using in IOS..and I got only one time after that I tried but I couldn't able to reproduce. The first time when I got this error, the transactions are in background and device goes idle and locked. After unlocking the Device I have seen the above error message in alert.

Let me know what might be the issue..is that issue with device is in locked? or any other? 
I will also investigate in this.

Thanks.
