### ISSUE TITLE
Cordova 5.4.0 + Windows Phone - Architecture processor mismatch

### ISSUE THREAD

**Issue by sandrine-quadient** [brody2consult/cordova-sqlite-storage#397]
I have an error when I compile my application with sqlite plugin and Cordova 5.4.0 (on Windows Phone Universal platform).

The error message in french is :
"C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(4388,5): 
error APPX0505: L'architecture du processeur du projet 'neutral' ne correspond pas à l'architecture du processeur 'x86' du projet 'SQLite3' référencé. 
Modifiez l'une des architectures de processeur ciblées de sorte qu'elles soient identiques. [C:...\platforms\windows\CordovaApp.Windows.jsproj]"

I think it means an architecture processor mismatch ...

On Android and iOS, it works well. 
Without sqlite plugin, it works on Windows Phone Universal.
Before I was using Cordova 5.2.0 and it worked well with Windows Phone Universal.

Do you know this error ? 

Thank you for your help.

**Comment by brody2consult** [comment]
I think you have to select a specific target architecture for the windows
version.

**Comment by sandrine-quadient** [comment]
Well, it seems working with Cordova 5.4.1 ...

**Comment by brody2consult** [comment]
> Well, it seems working with Cordova 5.4.1 ...

Happy to hear, closing.
