### ISSUE TITLE
Error: null is not an object (evaluating 'n.transaction') in ios app

### ISSUE THREAD

**Issue by firaskudsy** [brody2consult/cordova-sqlite-storage#400]
hi, am trying to use this plugin with my ios app, am already done with android and its work fine, but when i move to build and test the ios, am getting the following error 

Error: null is not an object (evaluating 'n.transaction')

any help ?

**Comment by brody2consult** [comment]
Unfortunately that is not enough information to help you. I suggest that you start with a very small test app, get it working with both Android and iOS, and add one thing at a time until you see what is wrong. In case you do find something that does not work with both of your target platforms, it is best to make a minimal but complete test program to demonstrate the issue.

I have also added a couple of checklists to help people double-check and debug their own work:
- https://github.com/brodybits/Cordova-quick-start-checklist
- https://github.com/brodybits/Cordova-troubleshooting-guide

**Comment by ishan123456789** [comment]
My database was not initialised that was resulting into an error.Please check your database connection.
