### ISSUE TITLE
openDatabase creation callback

### ISSUE THREAD

**Issue by corinzio** [brody2consult/cordova-sqlite-storage#401]
In the websql specification there is for the openDatabase function a creation callbak that should be executed only when the database has to be created.

``` javascript
Database openDatabase(in DOMString name, in DOMString version, in DOMString displayName, in unsigned long estimatedSize, in optional DatabaseCallback creationCallback);
```

I've tried but this is not working for me, its' my fault or it's a feature not supported (i didn't found a documentation specific for that feature).
Thanks.

**Comment by brody2consult** [comment]
Unfortunately the openDatabase creation callback is not supported by this
plugin. This feature is for future consideration.

**Comment by brody2consult** [comment]
I would like to resolve this in litehelpers/Cordova-sqlite-storage#212 (CREATE database if it does not exist should be optional). Closing for now, will reopen if desired by the user community.
