### ISSUE TITLE
Nothing happen after add Sqlite plugin

### ISSUE THREAD

**Issue by phuongtailtranminh** [brody2consult/cordova-sqlite-storage#402]
Hi,

I need some help to use SQLite-Plugin of Chris Brody [https://github.com/litehelpers/Cordova-sqlite-storage]

I'm using PhoneGap version 5.3.9 [phonegap -v]

These following are my commands history:

```
$phonegap create sqlite-demo
$cd sqlite-demo
$phonegap plugin list -> No added plugin
$phonegap plugin add https://github.com/litehelpers/Cordova-sqlite-storage
```

After run plugin add command, I saw the changes in /plugins folder but nothing change in config.xml file, Is that alright?

Then, I'm trying to use demo code, change index.js file:

```
    onDeviceReady: function () {
        app.receivedEvent('deviceready');
        var db = window.sqlitePlugin.openDatabase({ name: "my.db" });

        db.transaction(function (tx) {
            tx.executeSql('DROP TABLE IF EXISTS test_table');
            tx.executeSql('CREATE TABLE IF NOT EXISTS test_table (id integer primary key, data text, data_num integer)');

            // demonstrate PRAGMA:
            db.executeSql("pragma table_info (test_table);", [], function (res) {
                console.log("PRAGMA res: " + JSON.stringify(res));
            });

            tx.executeSql("INSERT INTO test_table (data, data_num) VALUES (?,?)", ["test", 100], function (tx, res) {
                console.log("insertId: " + res.insertId + " -- probably 1");
                console.log("rowsAffected: " + res.rowsAffected + " -- should be 1");

                db.transaction(function (tx) {
                    tx.executeSql("select count(id) as cnt from test_table;", [], function (tx, res) {
                        console.log("res.rows.length: " + res.rows.length + " -- should be 1");
                        console.log("res.rows.item(0).cnt: " + res.rows.item(0).cnt + " -- should be 1");
                    });
                });

            }, function (e) {
                console.log("ERROR: " + e.message);
            });
        });
    },
```

But nothing happen when I start my app. 

Any idea about this problem?

**Comment by brody2consult** [comment]
After you add the plugin, did you try `phonegap plugin list`?

In general, I have tested with the `cordova` CLI, not the `phonegap` cli. I can also test with the `phonegap` cli sometime next week.

**Comment by phuongtailtranminh** [comment]
Hi brodybits,

Thank for your reply!

I want to know is that correct way to install a plugin? (because I see nothing change in config.xml file) Do I need more step? (add something into config.xml file?)

What version of Cordova did you test? Do It follow the same step with mine?

How to check If installed plugin affect the project?

**Comment by kentr** [comment]
Here's how I installed.  There were no changes to `config.xml`.
1. `cordova plugin add https://github.com/litehelpers/Cordova-sqlite-storage`
2. Add the javascript to `index.html` _after_ `cordova.js`:
   
   ```
   <script type="text/javascript" src="SQLitePlugin.js"></script>
   ```
3. Add a `deviceready` listener to `index.html`:
   
   ```
   <script>    
     // Wait for Cordova to load
     document.addEventListener("deviceready", onDeviceReady, false);
     // Cordova is ready
     function onDeviceReady() {
       // DEV: test if sqlitePlugin is installed.
       if (window.sqlitePlugin) {
         alert("window.sqlitePlugin exists");
       }
       else {
         alert("window.sqlitePlugin doesn't exist");
       }
     }
   </script>
   ```

**Comment by kentr** [comment]
Just discovered that there are also several testing methods described in the [`README`](https://github.com/litehelpers/Cordova-sqlite-storage#echo-test).
