### ISSUE TITLE
Windows 8.1 Cordova app with sqlite implementation

### ISSUE THREAD

**Issue by gaurang-devrepublic** [brody2consult/cordova-sqlite-storage#403]
I have to port ios cordova app to windows app. 

After creating the cordova projects, I copied the required files and installed the required plugins but not able to run the project successfully. 

App is executed but local data base is not created and so no table is created.

It will be the great help if some one can check whats wrong.

Please download the code from following:
http://www.4shared.com/zip/wFR6aPG2ce/windows.html

**Comment by brody2consult** [comment]
I expect to try this early next week.

**Comment by gaurang-devrepublic** [comment]
Thanks...

**Comment by gaurang-devrepublic** [comment]
Hi Chris,

I solved the issue. Actually the issue was multiple plugins and other JS errors. 

Thanks for the great PlugIn and your help.

Gaurang
