### ISSUE TITLE
[__NSDictionaryM UTF8String]: unrecognized selector sent to instance 0x1551d4b0'

### ISSUE THREAD

**Issue by maciejkoch** [brody2consult/cordova-sqlite-storage#406]
Hello!

I have the current version of plugin and ngCordova. During creating database on ios 9.2 with command :_database = $cordovaSQLite.openDB(DB.NAME + '.db');

i have got:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM UTF8String]: unrecognized selector sent to instance 0x1551d4b0'
**\* First throw call stack:
(0x252862eb 0x24a52dff 0x2528bab5 0x2528970f 0x251b8c88 0x11a311 0x1196c9 0x119457 0x389cbf 0x396017 0x395909 0x24fbce0d 0x24fbc9fc)
libc++abi.dylib: terminating with uncaught exception of type NSException

Everything works perfectly with Android. Problem occurs only with iOS.

**Comment by brody2consult** [comment]
Unfortunately that is not enough information to help you. Please make a standalone project that demonstrates this error. It is preferred if you can demonstrate this error outside of the Angular/ngCordova/Ionic variations.
