### ISSUE TITLE
please I need the 0.7.12 version I cannot intall the last version 

### ISSUE THREAD

**Issue by nazihnemri** [brody2consult/cordova-sqlite-storage#407]
Hello this my error, 

 Install start for "cordova-sqlite-storage" on android. (TaskId:16)
1>  TypeError: Cannot call method 'indexOf' of undefined (TaskId:16)
1>Done executing task "MdaVsCli" -- FAILED. (TaskId:16)
1>Done building target "BuildMDA" in project "TerorDefeter.jsproj" -- FAILED.: (TargetId:15)

**Comment by brody2consult** [comment]
Unfortunately this is not enough information to help you. Please post a test project that demonstrates this issue.

**Comment by nazihnemri** [comment]
Hello i try to build my project and he show me that the build failed and show the error that I posted

**Comment by nazihnemri** [comment]
last week is work good when I clean my project and I rebuild the project it show me this build error

**Comment by brody2consult** [comment]
I have no way to find the cause. Please make a project that demonstrates your error.

**Comment by nazihnemri** [comment]
the problem that I create a new project and I just add the sqlite pluguin and make a build the project is empty 
this what the build show me when it begin to install the pluguin (i user visual studio 2013 with cordova 3.7.2) 
1>  Installing "cordova-sqlite-storage" for android (TaskId:22)
1>  Running command: cmd "/s /c ""C:\Users\Oracle\Documents\Visual Studio 2013\Projects\TerorDefeter\TerorDefeter\bld\Debug\platforms\android\cordova\version.bat""" (TaskId:22)
1>  Command finished with error code 0: cmd /s /c ""C:\Users\Oracle\Documents\Visual Studio 2013\Projects\TerorDefeter\TerorDefeter\bld\Debug\platforms\android\cordova\version.bat"" (TaskId:22)
1>  Install start for "cordova-sqlite-storage" on android. (TaskId:22)
1>  TypeError: Cannot call method 'indexOf' of undefined (TaskId:22)
1>Done executing task "MdaVsCli" -- FAILED. (TaskId:22)
1>Done building target "BuildMDA" in project "TerorDefeter.jsproj" -- FAILED.: (TargetId:15)
1>
1>Project Performance Summary:
1>    187985 ms  C:\Users\Oracle\Documents\Visual Studio 2013\Projects\TerorDefeter\TerorDefeter\TerorDefeter.jsproj   1 calls
1>              187985 ms  build                                      1 calls
1>
1>Target Performance Summary:
1>        0 ms  BeforeBuild                                1 calls
1>        0 ms  AfterBuild                                 1 calls
1>        0 ms  CoreBuild                                  1 calls
1>        0 ms  BuildOnlySettings                          1 calls
1>        1 ms  CleanCordovaDeploy                         1 calls
1>        1 ms  CompileTypeScript                          2 calls
1>        4 ms  PreComputeCompileTypeScript                1 calls
1>        4 ms  TrackJsChanges                             1 calls
1>       14 ms  _CheckForInvalidConfigurationAndPlatform   1 calls
1>    33447 ms  MDACleanAfterInstall                       1 calls
1>    34086 ms  InstallMDATargets                          1 calls
1>    34092 ms  EnsureNodeJsRequirementsAreAtCorrectVersion   1 calls
1>    153870 ms  BuildMDA                                   1 calls
1>
1>Task Performance Summary:
1>        0 ms  AssignTargetPath                           1 calls
1>        1 ms  MdaTrackJsChanges                          1 calls
1>        1 ms  Message                                    3 calls
1>        3 ms  VsTsc                                      1 calls
1>       40 ms  CreateBuildInfoMetadata                    1 calls
1>      637 ms  RunMdaTargetsInstall                       1 calls
1>     3283 ms  CreateItem                                 1 calls
1>     7984 ms  RemoveDir                                  7 calls
1>    22171 ms  Delete                                     1 calls
1>    67537 ms  CallTarget                                 3 calls
1>    153830 ms  MdaVsCli                                   1 calls
1>
1>Build FAILED.
1>
1>Time Elapsed 00:03:07.98
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by nazihnemri** [comment]
if possible Sir to give me the version of 0.7.12 thats all what I need and thanks for your help

**Comment by brody2consult** [comment]
https://github.com/litehelpers/Cordova-sqlite-storage/releases/tag/0.7.12

**Comment by nazihnemri** [comment]
thanks
