### ISSUE TITLE
Issue after v 0.7.11

### ISSUE THREAD

**Issue by sstraus** [brody2consult/cordova-sqlite-storage#410]
Starting with version 0.7.12 the following snippet fail because < is null in sqlliteplugin.js.

Any other have the same problem?

mycb = function(result) {
      var last, q, r, res, type, _i;
      last = result.length - 1;
      for (i = _i = 0; 0 <= last ? _i <= last : _i >= last; i = 0 <= last ? ++_i : --_i) {
        r = result[i];
        type = r.type;  <<<< r.type is undefined 
        res = r.result;
        q = mycbmap[i];
        if (q) {
          if (q[type]) {
            q[type](res);
          }
        }
      }
    };

**Comment by brody2consult** [comment]
Thanks for the explanation. The same issue was reported in #409 and will be handled there.

**Comment by brody2consult** [comment]
A workaround fix for #409 is published, thanks.
