### ISSUE TITLE
Breaks InAppBrowser Pluging

### ISSUE THREAD

**Issue by ghost** [brody2consult/cordova-sqlite-storage#411]
When having this implemented with an application that also have InAppBrowser pluging installed does not work. 

It looks like the open function of InAppBrowser gets redirected to SQLiteProxy.js

I'm running this on a Windows App. 

When I call window.open('http://www.google.com', '_blank', "location=no"); The calls goes to inappbrowser.js -> module.exports = function(strUrl, strWindowName, strWindowFeatures, callbacks) {}

When it calls exec(cb, cb, "InAppBrowser", "open", [strUrl, strWindowName, strWindowFeatures]) inside this module.exports function above the code jumps to cordova.js -> module.exports = function (success, fail, service, action, args) {}

In this function it reaches the proxy(onSuccess, onError, args); line then jumps to SQLiteProxy.js -> module.exports = { open: function(win, fail, args) { ..... } }

Is there a way around this?

**Comment by brody2consult** [comment]
It would be helpful if you can post a demo project that reproduces this issue.

**Comment by ghost** [comment]
I will put something together and post it. Thanks.

**Comment by ghost** [comment]
Ok I have noticed something. This only effects apps that use the Microsoft Edge browser. 
When I run this app on a Android or Windows 8 emulator it works fine. But when I open in in a Windows 10 app or Windows Phone 10 (both use Microsoft Edge browser) I run into issues.

Attached is a simple project created in Visual Studio. It only has one button and some text to explain how to replicate the issue. This project has InAppBrowser plugin installed but not the Sqlite. Once you test it without Sqlite you then install it and see the effects. All is explained in the text in the application.

You will need Visual Atudio 2015 with Cordova Tools installed for this project to run.

Does this help.
[InAppBrowserConflict.zip](https://github.com/litehelpers/Cordova-sqlite-storage/files/91805/InAppBrowserConflict.zip)

**Comment by brody2consult** [comment]
> Ok I have noticed something. This only effects apps that use the Microsoft
> Edge browser.
> When I run this app on a Android or Windows 8 emulator it works fine. But
> when I open in in a Windows 10 app or Windows Phone 10 (both use Microsoft
> Edge browser) I run into issues.

With this plugin you have to remove the Windows 10 target from the Visual
Studio build.


## 

Sent from my mobile

**Comment by ghost** [comment]
Do you have any plans to include Windows 10 support in the near future? 

Please say yes :)

**Comment by brody2consult** [comment]
The cordova-sqlite-ext version now supports Windows 10.
