### ISSUE TITLE
[PouchDB] Problems with latest versions [workaround available]

### ISSUE THREAD

**Issue by enricodeleo** [brody2consult/cordova-sqlite-storage#413]
Upgrading from 0.7.11 to 0.7.4 (or the new ev-free 0.8.2-pre) the plugin stops to work. Either upgrading an existent applications, or on a fresh install.

It doesn't load neither save dbs/data and looking to XCode's console it doesn't print the usual infos such as DB_OPEN etc...

Tested with: 
- ionic cli 1.7.13
- cordova 5.4.1
- cordova-ios 3.9.2
- PouchDB 4.0.3

On:
- iOS 8.4 (emulator)
- iOS 9.2 (emulator)
- iOS 9.2.1 (Device)

Rolling back to 0.7.11 (simply `cordova plugin rm/add`) restores full functionality with no further efforts. Any ideas?

**Comment by brody2consult** [comment]
In the case of PouchDB you have to apply the workaround described in #409.
I will fix it when I get a chance.

**Comment by enricodeleo** [comment]
Thanks @brodybits it seems to work now! As far as you know is there any drawback (maybe using the plugin without PouchDB)?

**Comment by brody2consult** [comment]
A workaround fix is published.
