### ISSUE TITLE
Android - Logs getting filled with V/sqlg tag logs

### ISSUE THREAD

**Issue by vishalkardode** [brody2consult/cordova-sqlite-storage#414]
Hi,
This might be android issue as I have not seen any "sqlg" in sources.
All my queries are getting logged including preparedStatement params values passed with `V/sqlg` tag. I can see this as log level set to VERBOSE for sqlg tag but could not find where to change logger level.
-- Vishal

**Comment by brody2consult** [comment]
I suspect you are using an old version. Please upgrade and try it again.

**Comment by vishalkardode** [comment]
Thanks, I was on 0.7.11 and after upgrading to 0.7.14 I am no longer seeing those logs.
