### ISSUE TITLE
alter table add column not working

### ISSUE THREAD

**Issue by rbabler** [brody2consult/cordova-sqlite-storage#418]
Hi,

after device ready i create db tables and alter statements. All statements are succesfully executed.
If i try to insert in my table, i got an error that my new column (created with alter table add ...) does not exists.
I don´t have a typo.

If i clear the data of my app, then i works correctly. But in this way i lost the data and so it is not a possible way.

Is there a problem, if the table has data and i try to add a new column?

Please do you have some tips for me.

best regards
René

**Comment by brody2consult** [comment]
Please make a simple, self-contained test program to reproduce the issue.

**Comment by brody2consult** [comment]
Please report the platform(s) where you see the issue as well.

In general I don't support old plugin versions or external forks. I noticed the question raised in Telerik-Verified-Plugins/SQLite#2 which is now almost 10 _months_ behind. I suspect this is a sqlite usage issue.

**Comment by aqibmapari** [comment]
I am also facing this issue.
I have so far tested on android and ios.
It goes into success function but the column is not added. 

I have the following code for alter

`function alterTable(tx,tablename,columnname,datatype){
    tx.executeSql('select '+columnname+' from '+tablename+'',[],function(tx,results){
                  //console.log('coloumn exists');
    },
    function(err){
          console.log(tablename+' - '+columnname+' select error '+err);
          tx.executeSql('ALTER TABLE '+tablename+' ADD COLUMN '+columnname+' '+datatype+'',[],function(tx,results){},function(err){console.log(tablename+' - '+columnname+' alter error '+err);})
     });
}
`

The below is the call to this function 
`alterTable(tx,"cformreport","quarter","text");`

Please suggest some fix for the same as maintaining app updates is not working due to this issue.

**Comment by tomdominion** [comment]
Hi, I've had this issue as well.  My problem was I has created the db using a previous sqllite plug in and then upgraded to the Brody soft plug in.  After upgrading I could do everything except alter the table.  Dropping the table, then creating the table then altering the table did work however.  My solution was to create a new database and copy the data into the new database.  I was then able to  alter the table.  I hope this makes sense and helps.
