### ISSUE TITLE
exectuteSql statement fails on ios with pre-populated database.

### ISSUE THREAD

**Issue by ScolDev** [brody2consult/cordova-sqlite-storage#425]
I have an issue with the plugin in the next scene:
- I download the pre-populated db when the user login successfully on my app.
- I storage the db on the cordova.file.dataDirectory path (in this point, this works fine, the db is located on this directory successfully).
- Whe i use:

`...
var dbPath = cordova.file.dataDirectory + dbName;
var db = window.sqlitePlugin.openDatabase(dbPath);

db.transaction(function(tx){

tx.executeSql("some query", [], function(tx, data){
//do-something
}, function(err){
console.log(JSON.stringify(err));
});
});`

Next, the program enter on function error, and prints the next object error:

![simulator screen shot 12 02 2016 12 18 39 p m](https://cloud.githubusercontent.com/assets/7546162/13014724/44cba8c4-d183-11e5-87dc-17b220fc36b6.png)

I dont know if this plugin works fine with pre-populated databases, or the error message on execute the sql statment is for some permissions on iOS. :s

The code below works fine on android. :(

PD: sorry for the closed issue lately

**Comment by brody2consult** [comment]
Please use cordova-sqlite-ext for pre-populated database support. Thanks!

**Comment by ScolDev** [comment]
But, the pre-populated db is stored on cordova.file.dataDirectory, is downloaded from x server :s

can't i load the db from this directory (cordova.file.dataDirectory)? in the plugin's doc, tells me to put the db on www directory, however when the app is running, i can't do this :s

**Comment by brody2consult** [comment]
In your case please take a look at how cordova-plugin-dbcopy does it.

**Comment by ScolDev** [comment]
But the cordova-plugin-db copy the db from www directory to another dir, not vice versa. I dont have the db on this directory, i have the db on cordova.file.dataDirectory and the cordova-sqlite-ext plugin loads db from this www directory. How can I do it?

**Comment by brody2consult** [comment]
I am not sure if I follow you. My understanding is that you need to download a db file from a server then open it with the plugin.

This is different from the pre-populated database feature. The pre-populated database feature copies the database from the www folder to either the default database directory or to another location that is selected using the openDatabase location option (iOS only).

I highly recommend that you use the standard Cordova features to download the database file and copy it to the correct location before opening it with this plugin. For iOS this is documented in README.md, repeating here:

> The `location` option is used to select the database subdirectory location (iOS _only_) with the following choices:
> - `0` (default): `Documents` - visible to iTunes and backed up by iCloud
> - `1`: `Library` - backed up by iCloud, _NOT_ visible to iTunes
> - `2`: `Library/LocalDatabase` - _NOT_ visible to iTunes and _NOT_ backed up by iCloud

Please confirm if this answers your question or not. If not then please explain what you want to achieve very clearly.

**Comment by ScolDev** [comment]
Thanks, I think I did not understand me well.

I have a db file already downloaded on cordova.file.dataDirectory ("Library/NoCloud") when the user login successfully in the app; well.. now i need load the database from this location, but on run the executeSql statement, this fail, i don't know why. The image post in the first comment shows the data object in the error function.

Regards!

**Comment by brody2consult** [comment]
The plugin does NOT open the database from "Library/NoCloud". The library can open the database from "Library/LocalDatabase" if you open the database with the `location: 2` option as documented in README.md. It is up to you to use the standard Cordova plugins to copy the database to a location where this plugin can read it.

The image does not tell me anything. But I will make the following guess: it appears that you open the database with a file:/// URI as the database name, which is _not_ supported by this plugin.

**Comment by ScolDev** [comment]
Thanks for response.

I'm loading the db from 'Documents' directory and when I am doing a transaction, show the next message in console output.

'new transaction is waiting for open operation'

The code looks like:

`var db = window.sqlitePlugin.openDatabase({name: 'folder/DataBase.db'});

db.transaction(function(tx){
tx.executeSql('Some Query');
});
`

Thanks!

**Comment by brody2consult** [comment]
Unfortunately use of a folder name in sqlitePlugin.openDatabase is neither tested nor supported. For future consideration.

FYI I also offer priority support and feature development through a commercial support program. For more information please reach out to: info@litehelpers.net

**Comment by StevensCol** [comment]
Thanks, but when i change for a single name "DataBase.db", get the next error and the app crash:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM UTF8String]: unrecognized selector sent to instance 0x7fb1d600a470'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e070e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000110afedeb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e07948d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010dfc690a ___forwarding___ + 970
	4   CoreFoundation                      0x000000010dfc64b8 _CF_forwarding_prep_0 + 120
	5   AppName               0x000000010de0ff8a -[SQLitePlugin executeSqlWithDict:andArgs:] + 554
	6   AppName               0x000000010de0f1bd -[SQLitePlugin executeSqlBatchNow:] + 733
	7   AppName               0x000000010de0ee0a __42-[SQLitePlugin backgroundExecuteSqlBatch:]_block_invoke + 42
	8   libdispatch.dylib                   0x00000001113afe5d _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x00000001113d049b _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x00000001113b8bef _dispatch_root_queue_drain + 1829
	11  libdispatch.dylib                   0x00000001113b84c5 _dispatch_worker_thread3 + 111
	12  libsystem_pthread.dylib             0x0000000111708a9d _pthread_wqthread + 729
	13  libsystem_pthread.dylib             0x00000001117063dd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by ScolDev** [comment]
Ohh finally find the solution, sending the name without subfolder as parameter to the openDatabase function. There were many things I was doing wrong. Thank you very much for your help!

**Comment by brody2consult** [comment]
:+1: Happy to hear!
