### ISSUE TITLE
SURVEY: Has anyone encountered iOS locking issues?

### ISSUE THREAD

**Issue by brody2consult** [brody2consult/cordova-sqlite-storage#431]
I have seen a couple of reports of iOS database locking:
- PR #264 - added support to enabling database when ios is locked
- sqlcipher/sqlcipher#156 - .sql can't open when the iphone locked (possible interaction with FMDB)

I have not seen this issue myself. I would be interested if anyone else has seen this issue.

**Comment by brody2consult** [comment]
I discovered the following: http://codeblow.com/questions/sqlite-error-database-is-locked/

I do not think this is an issue with this plugin since the sql access is protected by a `@synchronized(self)` block.

**Comment by asnyderabode** [comment]
This is an issue if you are using Data Protection. 

<img width="415" alt="screen shot 2016-08-19 at 5 00 08 pm" src="https://cloud.githubusercontent.com/assets/18235456/18072012/806f8c64-6e28-11e6-9aa9-eada487c386d.png">

**Comment by brody2consult** [comment]
Thanks @asnyderabode. Anyone else?

Any suggestions how to enable the "Data Protection"?

From discussion in sqlcipher/sqlcipher#156 and ccgus/fmdb#262 I think the ideal would be to use the SQLITE_OPEN_FILEPROTECTION_NONE flag. It may need some Apple or iOS specific code. I kinda remember there being an Apple or iOS specific SQLite branch. For further investigation.

I am also marking this as a bug for now.

**Comment by brody2consult** [comment]
Closing this discussion in favor of issue reported in #786
