### ISSUE TITLE
db.executeSQL or tx.executeSQL

### ISSUE THREAD

**Issue by brunoravanhani** [brody2consult/cordova-sqlite-storage#432]
Hi, I'm a beginner user of this plugin and I like to know what are the advantages or improvements to use `db.executeSql()` rather than `tx.executeSql()` inside a `db.transaction()`.

**Comment by brody2consult** [comment]
`db.executeSql()` does _not_ incur the BEGIN/COMMIT/ROLLBACK (transaction locking) overhead since it is a single statement that can atomically either succeed or fail. This will be documented when I get a chance.

**Comment by markarupert** [comment]
When I try and use db.executeSql() I get the following error. db.transaction with executeSql works fine.

angular.js:11358 TypeError: db.executeSql is not a function

**Comment by brody2consult** [comment]
@markarupert that error means you did not open the database properly. Please check the following:
- If you use `window.openDatabase` to open the database `db.executeSql` is not available.
- You *MUST* wait for the `deviceready` event before attempting to open the database.  This can be especially tricky in certain Angular constructions that do *NOT* wait for this `deviceready` event.

**Comment by markarupert** [comment]
Thanks, I was testing on the emulator and did not realize that db.executeSQL was unavailable. I tested on the Android and it is working fine.
