### ISSUE TITLE
Unable to open a Database on Windows Phone ("Could not open database, code 0")

### ISSUE THREAD

**Issue by mglmgl** [brody2consult/cordova-sqlite-storage#433]
Hi there,

my following solution works fine on iOS and Anroid.
But on a Windows Phone 8.1 or Windows Phone 10 Emulator i'm unable to open a database file or create a new one.

```
$ionicPlatform.ready(function() {
 db = window.sqlitePlugin.openDatabase({ name: "database.db", location: 0 }, successCb, errorCb);

            function successCb(res){
                console.log("DB open success!")
            }
            function errorCb(err){
                console.log("DB open error: "+err)
            }
}
```

The error-callback logs out the following:

> Could not open database - code 0

I'm using Cordova 6.0.0 with ionic 1.2.1 and my project is an windows-project (not wp8).
Plugin version is 0.8.2.

**Comment by brody2consult** [comment]
Please use cordova-sqlite-ext or cordova-sqlite-legacy for Windows.
