### ISSUE TITLE
Build Warnings in iOS [ionic] [pouchdb]

### ISSUE THREAD

**Issue by milkmusket** [brody2consult/cordova-sqlite-storage#434]
I'm unable to get this working on my project. Pouchdb consistently returns `sqlite_plugin: false`. When doing `ionic build ios` I get the following warnings:

```
/Users/Milkmusket/Documents/tarot/platforms/ios/Golden Thread Tarot/Plugins/io.litehelpers.cordova.sqliteStorage/sqlite3.c:32015:9: warning: 'gethostuuid' is deprecated: first deprecated in iOS 5.0 - gethostuuid() is no longer supported [-Wdeprecated-declarations]
    if( gethostuuid(pHostID, &timeout) ){
        ^
/Users/Milkmusket/Documents/tarot/platforms/ios/Golden Thread Tarot/Plugins/io.litehelpers.cordova.sqliteStorage/sqlite3.c:32003:12: note: 'gethostuuid' has been explicitly marked deprecated here
extern int gethostuuid(uuid_t id, const struct timespec *wait);
           ^
/Users/Milkmusket/Documents/tarot/platforms/ios/Golden Thread Tarot/Plugins/io.litehelpers.cordova.sqliteStorage/sqlite3.c:8970:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
/Users/Milkmusket/Documents/tarot/platforms/ios/Golden Thread Tarot/Plugins/io.litehelpers.cordova.sqliteStorage/sqlite3.c:12934:21: warning: unused function 'sqlite3BenignMallocHooks' [-Wunused-function]
SQLITE_PRIVATE void sqlite3BenignMallocHooks(void (*)(void), void (*)(void));
                    ^
/Users/Milkmusket/Documents/tarot/platforms/ios/Golden Thread Tarot/Plugins/io.litehelpers.cordova.sqliteStorage/sqlite3.c:13083:20: warning: unused function 'sqlite3BitvecBuiltinTest' [-Wunused-function]
SQLITE_PRIVATE int sqlite3BitvecBuiltinTest(int,int*);
                   ^
/Users/Milkmusket/Documents/tarot/platforms/ios/Golden Thread Tarot/Plugins/io.litehelpers.cordova.sqliteStorage/sqlite3.c:13187:21: warning: unused function 'sqlite3PrngSaveState' [-Wunused-function]
SQLITE_PRIVATE void sqlite3PrngSaveState(void);
                    ^
/Users/Milkmusket/Documents/tarot/platforms/ios/Golden Thread Tarot/Plugins/io.litehelpers.cordova.sqliteStorage/sqlite3.c:13188:21: warning: unused function 'sqlite3PrngRestoreState' [-Wunused-function]
SQLITE_PRIVATE void sqlite3PrngRestoreState(void);
                    ^
6 warnings generated.
```

as well as later on:

```
/Users/Milkmusket/Documents/tarot/platforms/ios/Golden Thread Tarot/Plugins/io.litehelpers.cordova.sqliteStorage/SQLitePlugin.m:47:17: warning: method definition for 'getBlobAsBase64String:withlength:' not found [-Wincomplete-implementation]
@implementation SQLitePlugin
                ^
In file included from /Users/Milkmusket/Documents/tarot/platforms/ios/Golden Thread Tarot/Plugins/io.litehelpers.cordova.sqliteStorage/SQLitePlugin.m:9:
/Users/Milkmusket/Documents/tarot/platforms/ios/Golden Thread Tarot/Plugins/io.litehelpers.cordova.sqliteStorage/SQLitePlugin.h:55:1: note: method 'getBlobAsBase64String:withlength:' declared here
+(NSString*)getBlobAsBase64String:(const char*) blob_chars
^
1 warning generated.
```

The kicker is that it apparently works on another person's computer who is helping me test. Pulling my hair out trying to figure this out. Thanks in advance.

**Steps to reproduce:**
Install the plugin cordova plugin add io.litehelpers.cordova.sqlitestorage

Made these edits to the my code (an otherwise basic app, similar to http://gonehybrid.com/how-to-use-pouchdb-sqlite-for-local-storage-in-your-ionic-app/)

```
+// Have to use location=2 to avoid being rejected by the app store, as per:
+// https://github.com/pouchdb/pouchdb/issues/3617
+var DB_OPTIONS = {
+  adapter: 'websql',
+  location: 2,
+};
 var app = angular.module('starter', ['ionic', 'starter.controllers', 'ksSwiper', 'ui.router', 'chart.js'])

 .run(function($ionicPlatform) {
 @@ -1676,7 +1684,7 @@ function achievementService($q) {

     function initDB() {
         // Creates the database or opens if it already exists
-        _db = new PouchDB('achievements');
+        _db = new PouchDB('achievements', DB_OPTIONS);
     };

     function updateAchievement(achievement) {
 @@ -1757,7 +1765,8 @@ function logService($q) {

     function initDB() {
         // Creates the database or opens if it already exists
-        _db = new PouchDB('logs');
+        _db = new PouchDB('logs', DB_OPTIONS);
+        _db.info().then(console.log.bind(console));
     };

```

**Comment by brody2consult** [comment]
You are using an old version of this plugin. Please install as follows: `cordova plugin add cordova-sqlite-storage`

**Comment by milkmusket** [comment]
Updated this, but still facing issues. I thought it might have been an issue with a conflict with leftover data from local storage, but I reset the simulator, and still no dice. :( Here's what the logs from the simulator tell me:

```
Feb 28 12:30:07 Macintosh assetsd[5191]: CoreData: error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///Users/Milkmusket/Library/Developer/CoreSimulator/Devices/Device Id/data/Media/PhotoData/Photos.sqlite options:{
        NSSQLitePersistWALOption = 1;
        NSSQLitePragmasOption =     {
        NSStoreType = SQLite;
            NSStoreType = SQLite;
Feb 28 12:30:07 Macintosh assetsd[5191]: CoreData: annotation: Incompatible version schema for persistent store 'file:///Users/Milkmusket/Library/Developer/CoreSimulator/Devices/Device Id/data/Media/PhotoData/Photos.sqlite'.  store metadata = {
        NSStoreType = SQLite;
Feb 28 12:30:11 Macintosh assetsd[5191]: CoreData: annotation: (migration)   Automatic schema migration succeeded for store at 'file:///Users/Milkmusket/Library/Developer/CoreSimulator/Devices/Device Id/data/Media/PhotoData/Photos.sqlite'
Feb 28 12:30:11 Macintosh assetsd[5191]: CoreData: annotation: Incompatible version schema for persistent store 'file:///Users/Milkmusket/Library/Developer/CoreSimulator/Devices/Device Id/data/Media/PhotoData/Photos.sqlite'.  store metadata = {
        NSStoreType = SQLite;
        migrationManagerClass = NSSQLiteInPlaceMigrationManager;
Feb 28 12:30:11 Macintosh assetsd[5191]: CoreData: annotation: (migration)   Automatic schema migration succeeded for store at 'file:///Users/Milkmusket/Library/Developer/CoreSimulator/Devices/Device Id/data/Media/PhotoData/Photos.sqlite'
Feb 28 12:30:21 Macintosh ondemandd[5246]: No existing database at /Users/Milkmusket/Library/Developer/CoreSimulator/Devices/Device Id/data/Library/OnDemandResources/Database/odr.sqlite, signal folks that this one might not be trustworthy IRT files on the device.
```

**Comment by milkmusket** [comment]
So we did a bit more debugging last night and here are some things we found:
- On the simulator, the plugin is working, meaning it returns `sqlite_plugin: true` (so long as you click the reload page in safari's developer tools, it doesn't not work upon load however.).
- When tethered to a device, the plugin does not work at all. 
- When building, and clicking around the app in xcode, it appears that the Frameworks > libsqlite3.dylib file is missing. We reattached the most current version (which is a libslqite3.tbd file according to this link: http://stackoverflow.com/questions/31420166/libsqlite3-dylib-and-libz-dylib-missing-in-xcode-7-how-do-i-use-parse). However, the issue did not resolve on the device.
- We downloaded the files for the app from the device, and it appeared that no extra .db files were being created. 

Unsure of where to take this from this point forward, so any guidance here would be helpful.

**Comment by brody2consult** [comment]
I suggest that you try the cordova-sqlite-ext version, which embeds its own version of sqlite.[hc] and should not have this issue.

**Comment by jamesjacobs** [comment]
@milkmusket I'm having the exact same issue - did swapping to the -ext version resolve it?

**Comment by brody2consult** [comment]
@jamesjacobs please try this yourself. In general there is not enough information in this issue.

**Comment by jamesjacobs** [comment]
Swapping to -ext version did not solve for me. I've tried various version combinations of ngcordova, ios cordova, pouchdb and this plugin. I'm manually bootstrapping angular in my ionic app to ensure the plugin has loaded. I've also tried various CSP configurations with no luck.

Calling the `window.sqlitePlugin.echoTest();` gives me `isSQLitePlugin: true` whilst using Pouch's recommended debug `db.info().then(console.log.bind(console));` gives me `sqlite_plugin: false` (both inside device ready)

I've also started with a vanilla ionic app, added ngCordova, then pouchDB and the SQL plugin (also tried the -ext version). Which still gives me `sqlite_plugin: false` on both the ios simulator and device. Beginning to think this plugin is not compatible with PouchDB as mentioned in the Pouch DB docs.

**Comment by milkmusket** [comment]
I got this notification late but it never worked for me either. I ended up switching to another setup. James, I did all the things you did too. 

One thing that did curiously work on the simulator only was refreshing using safari's refresh page button in developer mode. That seemed to initialize the database according to console logs. 😔

What other information can we provide you, Chris?

**Comment by brody2consult** [comment]
Guys if this is still an issue please post a very simple demo project. Marked as invalid for now.
