### ISSUE TITLE
Samsung Galaxy Note 3 - DB truncates after run

### ISSUE THREAD

**Issue by flaviotulino** [brody2consult/cordova-sqlite-storage#436]
Hi all,
I'm encountering an issue while using this plugin. 
Everything is working fine during the application lifecycle (inserts, selects, updates), but every time I run my app again `cordova run android` the database looks like has been truncated and my data are gone.

This happens on my Samsung Galaxy Note 3, but works fine on any other devices. 

Any suggestion? Could be a bug?

**Comment by brody2consult** [comment]
You may have to apply the `androidLockWorkaround` option, as described in README.md.

**Comment by flaviotulino** [comment]
Thank you for your reply, but, of course, I tried with that flag too. On other devices the application works as expected, on iOS too.

**Comment by brody2consult** [comment]
This is really strange, and I will need more information before I can accept this as a bug. The cordova-sqlite-ext version uses a different database implementation by default that should suffer from such data loss, can you try that one?

**Comment by flaviotulino** [comment]
Tested with Cordova SQLite Ext @_https://github.com/litehelpers/cordova-sqlite-ext_ but the got the same issue, facing a data loss every time I run the app. 
Please tell me if any other information is needed.

**Comment by brody2consult** [comment]
1: Can you confirm that you did _not_ use the `androidDatabaseImplementation` option when running the cordova-sqlite-ext version?

2: Can you isolate the simplest test program that you can make that demonstrates your issue?

If you are using Ionic or any other form of Angular, it would be great if you can make the test program without such a framework. Same for React or React Native. (No problem if you use JQuery)
