### ISSUE TITLE
NO callback called, after few successful queries

### ISSUE THREAD

**Issue by aleksandrmelnyk** [brody2consult/cordova-sqlite-storage#437]
Android emulator, 4.4.4 and also 4.4.2. Plugin version 0.8.2. Phonegap version: 6.0.0

The problem:
1. Running sqlBatch for 20-30 create statements, and about 4000 inserts. It runs fine.

```
me.db.sqlBatch(statements, function(){
                console.log("All statements done");
                callback.call(ctxt || me, null);
            },
            function(error){
                console.log('transaction error: ' + error.message);
                callback.call(ctxt || me, 'transaction error: ' + error.message);
            });
```
1.  Runing VACUUM, and either callback for it is never called:

```
window.sqlitePlugin.openDatabase(this.getDbParameters(), function(db){
            db.executeSql("VACUUM", [], function (res) {
                callback.call(ctxt || me, null);
            }, function(e) {
                callback.call(ctxt || me, e.message);
            });
        }, function(e){
            callback.call(ctxt || me, e.message);
        });
```

Tried:
1. Content-Security-Policy issue. Put maximum rights with "*". didn't help
2. androidLockWorkaround, didn't help
3. androidDatabaseImplementation: 2, didn't help

if I do not execut VACUUM, it  hangs within 1-2 sql statements anyway.

**Comment by aleksandrmelnyk** [comment]
also tried some branches for this plugin eg. enterprise-free, -ext etc. same issue for them

**Comment by brody2consult** [comment]
This is very strange. I have no way to understand the possible cause from this description. A complete, self-contained test program would be really helpful.
