### ISSUE TITLE
Select statement with parameters return 0 records

### ISSUE THREAD

**Issue by shohdi** [brody2consult/cordova-sqlite-storage#438]
On huawei  Mate 8 android marshmallow  select statement with parameters doesn't work.

when I try this query 
`db.executeSql('select * from user_tasks where REQUEST_REF_NO = 2246 and SURVEYOR_REQ_INDX = 1 ; ',[] , function(tx,data){console.log(data.rows.length);});`

it returns 16 in console

when I move the values in parameters like this
`db.executeSql('select * from user_tasks where REQUEST_REF_NO = ? and SURVEYOR_REQ_INDX = ? ; ',[2246,1] , function(tx,data){console.log(data.rows.length);});`

it returns 0 in console

**Comment by brody2consult** [comment]
I need a complete, self-contained test program to find a way to reproduce this issue.
