### ISSUE TITLE
Performance problems // cannot find the point 

### ISSUE THREAD

**Issue by Shapeshifter70** [brody2consult/cordova-sqlite-storage#440]
Hello there,

thanks for the great work on this plugin!

I use this plugin in a very simple way and create a table with approx. 30.000 records (insert is quite ok, approx 3 secs). After that we try to query this, but this takes up to 20 minutes (!) until the successor returns a result.

Is there a chance to see the outcome of EXPLAIN QUERY PLAN SELECT x FROM table somewhere? 
Am i missing something? Do i need to create Index (tried that already, but no effect so far). I have been searching for hours now and cannot find a solution.

Pls help.
thanks alot! 
John

**Comment by reconka** [comment]
Hi John,
could you share with us the  SELECT query and  schema of the table ?
Maybe this article can be  helpful for you: https://www.sqlite.org/cvstrac/wiki?p=PerformanceTuning

**Comment by Shapeshifter70** [comment]
Sure.
CREATE:

```
db.transaction(function (tx) {
    tx.executeSql('DROP TABLE IF EXISTS delivery');
    tx.executeSql("CREATE TABLE IF NOT EXISTS delivery(ID INTEGER PRIMARY KEY ASC, a TEXT, b TEXT, c TEXT, d TEXT, e TEXT, f TEXT, g TEXT, h TEXT, i TEXT, j TEXT, k TEXT, l TEXT, m TEXT, n TEXT, o TEXT, p TEXT )", []);
});
```

INSERT:
db.transaction(function (tx) {
        tx.executeSql("INSERT INTO delivery(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            [a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p],
            function () {
            console.log("inserted some data...");
        },
            errfunc;
    });

QUERY ( this is really more of a test). I added the explain query plan to see what happens but cannot reach the result.

EXPLAIN QUERY PLAN SELECT \* FROM delivery WHERE ID < 1000 LIMIT 100

Insert goes ok, query is a mess. I am sure i am doing something wrong the basic way, but cannot figure out what it is.

Do you have an idea?

**Comment by brody2consult** [comment]
In general performance improvements will be supported in https://github.com/litehelpers/Cordova-sqlite-enterprise-free (which is available under a different licensing scheme).

In addition, I would really need a complete, self-contained test program that can demonstrate the actual problem. For example (_not_ guaranteed to be 100% correct):

> The following test program demonstrates a serious performance issue on iOS and sometimes crashes:
> 
> ``` Javascript
> db.transaction(function(tx) {
>  tx.executeSql('DROP TABLE IF EXISTS TestTable');
>  tx.executeSql('CREATE TABLE TestTable (ID INTEGER PRIMARY KEY, A TEXT NOT NULL, B TEXT, C, D)');
>  for (var i=0; i<100000; ++i) {
>    tx.executeSql('INSERT INTO TestTable VALUES (?,?,?,?)', ['AAA-'+i, 'BBB-'+i, 'CCC-'+i, 'DDD-'+i]);
>  }
> }, function(error) {
>  alert('broken');
> }, function() {
>  alert('Test populated OK');
>  tx.executeSql('SELECT * FROM TestTable', [], function(tx, res) {
>    alert('got results OK');
>  }, function(error) {
>    alert('SELECT BROKEN WITH ERROR: ' + JSON.stringify(error));
>  });
> });
> ```

**Comment by Shapeshifter70** [comment]
Hello Chris,

thanks a lot for your reply. I could send you my demo project incl. files. Since the data is non-public, i would not post it here but send it to an eMail-Adress of yours. 

Is that ok for you and if yes: which adress?

thanks alot
John

**Comment by brody2consult** [comment]
You may contact me at info@litehelpers.net or brodybits@litehelpers.net for an estimate. I regret to say that this kind of support is no longer offered for free.
