### ISSUE TITLE
'SELECT' returns an object with 'rows.length' but no 'rows.items'

### ISSUE THREAD

**Issue by benshope** [brody2consult/cordova-sqlite-storage#441]
I am having the same issue as this person:

http://stackoverflow.com/questions/32973678/cordova-sqlite-query-rows-length-0-but-items-throws-exception

My sql `SELECT` returns an object with `rows.length` but no `rows.item`.  My script works fine in Chrome.  I attempted to downgrade, but that did not appear to solve the problem.  Any idea what might be going on?

**Comment by brody2consult** [comment]
Please specify which platform(s), which Xcode version in case of iOS, and a small test program to reproduce the issue thanks!

**Comment by benshope** [comment]
Nvm, sorry!  Tried a few more things and it works.  Thanks for writing a great plugin!

**Comment by osro** [comment]
@benshope Any idea what did you do? I'm having this same issue after I upgraded cordova, cordova project version and cordova plugins including this plugin.

Same thing happens on iOS and Android.

I have database that is holding blop images. The result comes out just fine when I example COUNT images that I have in my database.

```
tx.executeSql("SELECT count(tile_id) AS cnt FROM images;", [], function (tx, res) {
       console.log("res.rows.item(0).cnt: " + res.rows.item(0).cnt + " -- should be 2191");
     });
} 
```

And the output is 2191 like it should be.

But when I try to fetch the actual image BLOP 

```
tx.executeSql("SELECT tile_data FROM images INNER JOIN map ON images.tile_id = map.tile_id WHERE zoom_level = ? AND tile_column = ? AND tile_row = ?", [z, x, y], function (tx, res) {               
                    console.log("%o", res.rows.item(0));                
            }
```

The rows length is 1 like it should be, but when I try to access it by item(0) it is completely empty.
I have tested that the SQL-statement is correct and it works fine with SQLite Browser. Also this actually used to work earlier, but now something happen in the updates.

cordova 6.0.0 
cordova-sqlite-storage 0.8.4-dev

**Comment by brody2consult** [comment]
@osro I think you meant that you tried to fetch an image BLOB.

The storage and retrieval of the BLOB data type is currently _not_ supported by this project. A version that supports retrieval of BLOB data is available with a different licensing scheme at: https://github.com/litehelpers/Cordova-sqlite-evfree-ext

**Comment by osro** [comment]
Yep, that was it :smile: Thanks!

**Comment by doc-brown** [comment]
@benshope I am having the same problem and I am just trying to read a string from the database. Can you tell me what you did to solve this problem?

**Comment by brody2consult** [comment]
@doc-brown please raise a new issue in <https://github.com/litehelpers/Cordova-sqlite-help> with a self-contained demo if you are having this kind of an issue.

**Comment by brody2consult** [comment]
> http://stackoverflow.com/questions/32973678/cordova-sqlite-query-rows-length-0-but-items-throws-exception

The code in this question will not work since it is missing the location setting.

The accepted solution is NOT recommended since it will miss over 2 years of updates, including a couple data loss risk issues #666 and #716 that were discovered and fixed over the past year.

I would like to ask anyone facing this kind of an issue to discuss in <https://github.com/litehelpers/Cordova-sqlite-help/issues>, with self-contained reproduction code. I would also like to recommend giving <https://github.com/brodybits/cordova-sqlite-storage-starter-app> a try.

**Comment by benshope** [comment]
@doc-brown @osro sorry for the late response to some questions, what I think might have fixed my problem is that things have to be fetched from the sql response object using `things.get('items')` instead of normal javascript syntax `things.items` or `things["items"]`

EDIT: after reading the comment below, I realized that it was not a `.get()`, that confused me - it was  `rows.item(index)` instead of `rows[index]` syntax

**Comment by brody2consult** [comment]
@benshope thanks for commenting. Your response indicates that you are using some kind of a library to access the data in the sql response object, which would probably not work the same for most other users.

In general the row object is accessed in the following forms:
```js
resultSet.rows.item(rowIndex).columnName // individual column from a row
resultSet.rows.item(rowIndex) // full row object
```

So far I have seen the following possible causes of this kind of issue:
- <http://stackoverflow.com/questions/32973678/cordova-sqlite-query-rows-length-0-but-items-throws-exception> shows the database opened with location parameter missing (location value has been mandatory for almost 2 years)
- attempt to read BLOB value - does not work consistently on all platforms; it is recommended to use non-standard BASE64 function (supported by cordova-sqlite-ext and cordova-sqlite-evcore-extbuild-free) or builtin HEX function
- some other issue using this plugin in an app (it is recommended to try using <https://github.com/brodybits/cordova-sqlite-storage-starter-app> in case of this kind of issue)

**Comment by benshope** [comment]
@brodybits  Yes, you're totally right, it wasn't `.get()`, that confused me was the `rows.item(index)` syntax that was my issue.  Thanks for the correction!
