### ISSUE TITLE
Multiple bindings over tx.executeSql give syntax error

### ISSUE THREAD

**Issue by vabatta** [brody2consult/cordova-sqlite-storage#442]
With the following code, I get an error for wrong syntax while it's correct if using more than 1 parameter:

``` js
var table = 'db_table';
var update = ['col1=var1','col2=var2'];
var query = 'UPDATE ? SET ' + update.join(',') + ' WHERE id = ?';
// var workingQuery = 'UPDATE ' + table + ' SET ' + update.join(',') + ' WHERE id = ?';
db.transaction(function(transaction) {
  //  transaction.executeSql(query, [81729], function(transaction, result) {
  transaction.executeSql(query, [table, 81729], function(transaction, result) {
    deferred.resolve(result);
  }, function(transaction, error) {
    deferred.reject(error);
  });
});
```

Returing error object from reject

``` json
{
  "code": 5,
  "message": "could not prepare statement (1 near '?': syntax error)"
}
```

What could be the problem?

**Comment by brody2consult** [comment]
According to: https://www.sqlite.org/lang_update.html

You have to have a qualified table name after UPDATE.

In general it is _not_ allowed to use the `?` parameter placeholder in that part of the query.

**Comment by brody2consult** [comment]
I will document this when I get a chance.

**Comment by vabatta** [comment]
As seen in the comment, actually would be just handy to have it, because isn't really necessary to get the fully qualified name. Anyway, I implemented the substitution before the function, without using the bindings to work around this.
