### ISSUE TITLE
Does cordova-sqlite-storage plugin  work for blackberry10?

### ISSUE THREAD

**Issue by PrithvirajChauhan** [brody2consult/cordova-sqlite-storage#444]
I really need help cordova-sqlite-storage plugin works excellent in both android and ios but not working with blackberry is there any other things i have to add ?

**Comment by brody2consult** [comment]
From #262:

> #260 has a pointer to [ffournier / cordova-plugin-mbtiles](https://github.com/ffournier/cordova-plugin-mbtiles) which supports reading from a database and I discovered has a Blackberry 10 version (written in C++). Looks like a nice starting point.

**Comment by PrithvirajChauhan** [comment]
any guidance what should i do after installing cordova-plugin-mbtiles plugin

**Comment by brody2consult** [comment]
I do not recommend that you actually install that plugin. I only suggest that it has code that someone can use as a starting point for someone to develop a blackberry10 version.

**Comment by PrithvirajChauhan** [comment]
Thanks brodybits ,i will look into that.

**Comment by brody2consult** [comment]
If someone develops a blackberry10 version of this plugin I would be happy to add a link and maybe include it in the future.

I can also develop the port to blackberry10 but am not sure if I want to do this for free.

**Comment by assetsense** [comment]
Blackberry10 supports WebSQL API similar. Did anybody use it? Do you see any reason why it may not work as well as this plugin?

**Comment by brody2consult** [comment]
The blackberry10 platform is deprecated, closing.
