### ISSUE TITLE
no such module: rtree (code 1)

### ISSUE THREAD

**Issue by jayyeo** [brody2consult/cordova-sqlite-storage#446]
latest release 0.8.2 has rtree issue.  Tried on Lollipop and Marshmallow.  previous version works on lollipop but marshmallow will crash.

sql = CREATE VIRTUAL TABLE tableName USING rtree(fields)

Thanks,

**Comment by brody2consult** [comment]
On Mar 24, 2016 7:29 PM, "jayyeo" notifications@github.com wrote:

> latest release 0.8.2 has rtree issue. Tried on Lollipop and Marshmallow.
> previous version works on lollipop but marshmallow will crash.
> 
> sql = CREATE VIRTUAL TABLE tableName USING rtree(fields)

This looks like an issue with the Android platform. It should work in the
cordova-sqlite-ext version which includes its own build of sqlite3.

**Comment by jayyeo** [comment]
got it to work on marshmallow on release 0.7.14.  

Thanks,
