### ISSUE TITLE
Insert error

### ISSUE THREAD

**Issue by thomashrabe** [brody2consult/cordova-sqlite-storage#447]
Can somebody please explain me the error message my ionic / cordova app is returning when writing to an already open SQLite DB?

A `SELECT` request before the `UPDATE` to the DB fine, but writing fails...

`[Log] {"db":{"openargs":{"name":"mydb.db","dblocation":"docs"},"dbname":"mydb.db"},"txlock":true,"readOnly":false,"executes":[],"finalized":true} (console-via-logger.js, line 174)`

This is what SQLite outputs before I run the write transaction:

```

    [Log] OPEN database: mydb.db (console-via-logger.js, line 174)
    [Log] new transaction is waiting for open operation (console-via-logger.js, line 174)
    [Log] DB opened: mydb.db (console-via-logger.js, line 174)

```

That's how I write to it

```

            var myDB = $cordovaSQLite.openDB('myDB.db');

        var dataJSON = JSON.stringify(data);

        var deferred = $q.defer();

myDB.transaction(function(transaction) {
                 var query = "UPDATE Data SET Values='"+dataJSON+"'";
    //           console.log(query);
                 transaction.executeSql(query,[],
                 //On Success
                 function(tx, result) {
    //               console.log('UPDATE SUCCESSFULLY');
                     deferred.resolve(true);
                 },
                 //On Error
                 function(error){
    //               console.log('Backing up data to DB failed');
                     deferred.reject(error);
                 });
        });
```

**Comment by brody2consult** [comment]
I suspect this code is run before the Cordova deviceready event has been fired.

**Comment by thomashrabe** [comment]
I am running it in ionic and after the platform has loaded. 
Also, I successfully run a `SELECT` on the DB prior to the `INSERT`.

**Comment by payneBrandon** [comment]
Was this ever solved? I'm running into the same issue.  I'm working to sync data retrieved from a service to the SQLite db.  I select from a table to determine which values may need inserted.  On the success of that query, I open a transaction and run several insert statements in that transaction.  My error function is always hit, although it appears that my data WAS inserted.  Any ideas?

**Comment by thomashrabe** [comment]
No, I abandoned that route for a server side storage of that data...

**Comment by payneBrandon** [comment]
Dang, I need the ability to go offline with it.  Thanks for the input though! @brodybits any ideas?  This is in an ionic 2 application using typescript...

**Comment by brody2consult** [comment]
Sorry I have never used Ionic 2 with Typescript. Maybe you can find a sample somewhere.

**Comment by brody2consult** [comment]
@payneBrandon I just raised #585 to add a sample with Ionic 2 and TypeScript. You may want to try the tutorial at https://www.thepolyglotdeveloper.com/2015/12/use-sqlite-in-ionic-2-instead-of-local-storage/ (it uses TypeScript).
