### ISSUE TITLE
How to use existing database (sqlite3) database with apache cordova.

### ISSUE THREAD

**Issue by ZekariasNegash** [brody2consult/cordova-sqlite-storage#449]
I am using apache cordova with Visual Studio 2015. I have added a sqlite3 database inside the www folder and used the following code to connect to it.

this.db = window.sqlitePlugin.openDatabase({ name: "Test.sqlite3", location: 'default' });

But the application keep on creating a new database and any of my queries not working as no tables exist on the newly created database. Please Help.

**Comment by brody2consult** [comment]
You have to use the cordova-sqlite-ext version and use the
createFromLocation option. You may also have to uninstall the old version
of your app for this to work.
