### ISSUE TITLE
Unable to build plugin to W10 device (ext)

### ISSUE THREAD

**Issue by Artfloriani** [brody2consult/cordova-sqlite-storage#452]
Hey, 

I'm trying to build my ionic2 app to Windows 10 Mobile but I'm getting several errors when building the app.

I'm using the -ext version of the plugin.

![capture](https://cloud.githubusercontent.com/assets/6491691/14210156/20c47054-f7fe-11e5-9022-d7708a1bccc7.PNG)

Any idea on what the issue could be?

**Comment by brody2consult** [comment]
This looks like litehelpers/cordova-sqlite-ext#15, fixed by litehelpers/cordova-sqlite-ext#16. Please report any further issues with Windows 10 on the cordova-sqlite-ext project.
