### ISSUE TITLE
How to specify Database Version while opening the Database

### ISSUE THREAD

**Issue by Tawsif** [brody2consult/cordova-sqlite-storage#456]
In previous versions the syntax for opening the database was as follows

var dbobj = window.openDatabase("databasename", "version", "display_name", "size");

where "version" specifies the Database Version.

But as the method is changed, Now I do not know where to specify the version according to following syntax:

window.sqlitePlugin.openDatabase({name: "databasename", iosDatabaseLocation: "default"});

Please Help !!!!!!!!

**Comment by brody2consult** [comment]
In the past the database version parameter was simply ignored. This plugin has never supported this feature and will never support this feature. It is **highly** recommended to specify your database schema feature in your own table and support automatic upgrades, as described in a tip in README.md.
