### ISSUE TITLE
I cant makein work in phonegap 6.0.1

### ISSUE THREAD

**Issue by Democles** [brody2consult/cordova-sqlite-storage#467]
A get error opening database.

Any clue?
Thx.

**Comment by brody2consult** [comment]
Which platform(s)?

Do you have any other plugins or frameworks installed?

Did you try the echo test?

Did you try a simple test program? If so, please post it. If not, can you try a very simple test program and post it?

**Comment by Democles** [comment]
Platform: Browser and Android.
Framework: Phonegap 6.0.1
I try  the echo test, "Missing Command Error"
When the database is pre-populates cant find the table.
Cant create in device a new database.

**Comment by brody2consult** [comment]
The browser platform is _not_ supported by this project. In addition, the pre-populated database feature is _only_ supported in the cordova-sqlite-ext version.

**Comment by brody2consult** [comment]
Use with PhoneGap build (#466) and PhoneGap CLI are no longer be supported due to reported issues. This plugin is only tested and supported with Cordova CLI. Support for plugman is also dropped.
