### ISSUE TITLE
createFromLocation is being ignored

### ISSUE THREAD

**Issue by RaederDev** [brody2consult/cordova-sqlite-storage#468]
Hi,

I had to update the plugin to the newest version (1.2.1) because the old one wouldn't work with the new cordova version. Since I updated createFromLocation is being ignored and my sqlite file is not being copied when I call openDatabase.

I call the plugin like this:
`window.sqlitePlugin.openDatabase({name: "myapp.db", createFromLocation: 1, iosDatabaseLocation: 'default'});`

I have a file called myapp.db in my "www" folder.
I've noticed that this does nothing on Android I haven't had the chance to confirm this for iOS yet.

The SQLitePlugin JS file also still references this option:
`if (!!openargs.createFromLocation && openargs.createFromLocation === 1) {
        openargs.createFromResource = "1";
      }`

Am I doing something wrong here?

**Comment by brody2consult** [comment]
As documented the pre-populated database feature is moved to
cordova-sqlite-ext and is no longer supported here.

You will probably have to adjust your openDatabase call as documented.
Please use the same location as before otherwise you will break the app
upgrade.

**Comment by RaederDev** [comment]
Thanks I'll take a look at it.
