### ISSUE TITLE
Database not being saved

### ISSUE THREAD

**Issue by novalex** [brody2consult/cordova-sqlite-storage#469]
Hi,

I am building an app with Ionic, and am having trouble figuring out why my data is not being saved. Everything works fine when I test it in-browser or on an Android device with PhoneGap, but when I compile the APK and install it on the device, the database is not being saved. The echoTest returns successfully, and the app does what it's supposed to do when an execute statement completes, there are no errors, but the data itself is not being stored.

I'm not sure if this is the place to ask for help for this issue, but I've been stuck with this problem for more than a week now and am getting desperate, I've worked on it a lot and can't use it for anything if it can't store data.

This is the code for the service I'm using:

```
angular.module('chemspeed.services', [])

    .service('$sql', $sqlService);

$sqlService.$inject = ['$cordovaSQLite', '$q', '$ionicPlatform'];
function $sqlService($cordovaSQLite, $q, $ionicPlatform) {

    var self = this;
    var _db;

    self.db = function() {
        if ( ! _db ) {
            if ( window.cordova ) {
                _db = $cordovaSQLite.openDB({ name: 'data.db', location: 'default', androidLockWorkaround: 1 });
            } else {
                _db = window.openDatabase('data.db', '1.0', 'Data', 9999);
            }
        }
        return _db;
    };

    self.execute = function(query, parameters) {
        parameters = parameters || [];
        var db = self.db(),
            q = $q.defer();

        db.transaction( function(transaction) {
            transaction.executeSql(query, parameters, function(transaction, result) {
                q.resolve(result);
            }, function (error) {
                console.warn('DB ERROR');
                console.warn(error);
                q.reject(error);
            });
        });

        return q.promise;
    };

    self.updateConfig = function(ids, values) {
        var parameters = [ ids[0], values[0], ids[1], angular.toJson(values[1]), ids[2], angular.toJson(values[2]) ];
        return self.execute(
            'INSERT OR REPLACE INTO config SELECT "id" AS "ids", "value" AS "values" ' +
            'UNION ALL SELECT ?, ? ' +
            'UNION ALL SELECT ?, ? ' +
            'UNION ALL SELECT ?, ?', parameters);
    };

    self.getConfig = function() {
        return self.execute('SELECT * FROM config', []);
    };

    self.addDeviz = function(value) {
        var parameters = [angular.toJson(value)];
        return self.execute('INSERT INTO devize (value) VALUES (?)', parameters);
    };
}
```

Let me know if I can provide other info.

Thanks!

**Comment by brody2consult** [comment]
I recommend that you try the cordova-sqlite-ext version which has an improved sqlite database access implementation.

If that does not work: I recommend that you try a very simple test program without any other plugins or frameworks such as Angular/Ionic, both with this plugin version and with cordova-sqlite-ext. If this works then try one thing at a time until you can find the cause.
