### ISSUE TITLE
DB version is not wroking

### ISSUE THREAD

**Issue by nisarcitrus** [brody2consult/cordova-sqlite-storage#475]
After open a database, I getting db.version is undefined but there is no problem with HTML5/Web SQL.  How can I get exisiting db version ? Please help.

**Comment by brody2consult** [comment]
Database versioning is not supported, as I have documented in the past. I
will specifically document the missing db.version when I get a chance.

**Comment by Andrew67** [comment]
Given that "PRAGMA user_version" queries are throwing me errors, and the docs already recommend the "version table" pattern, I'm assuming that query is also not supported?

**Comment by brody2consult** [comment]
You _should_ be able to execute this from db.executeSql (outside a transaction).

**Comment by Andrew67** [comment]
After reading your comment, I went back, and there was a rookie mistake in passing parameters to db.executeSql. I can confirm "PRAGMA user_version" works, thanks!
