### ISSUE TITLE
PhoneGap Build Issues with 1.4.0+

### ISSUE THREAD

**Issue by jfi** [brody2consult/cordova-sqlite-storage#477]
Hi @brodybits, thanks for your work on this plugin. We've been using it in an app with PhoneGap Build which was working fine until today, when I got the following error and it refused to build:

`Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-sqlite-storage" via npm Installing "cordova-sqlite-storage" at "1.4.1" for ios Error during processing of action! Attempting to revert... Failed to install 'cordova-sqlite-storage':Error: Uh oh! "/private/tmp/gimlet/70256508913260/2067507/project/cordova/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies/sqlite3.c" not found! at Object.module.exports.common.copyFile (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/platforms/common.js:38:40) at Object.module.exports.common.copyNewFile (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/platforms/common.js:69:16) at installHelper (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/platforms/ios.js:55:16) at module.exports.source-file.install (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/platforms/ios.js:147:13) at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/platforms/PlatformApiPoly.js:662:27 at Object.ActionStack.process (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/node_modules/cordova-common/src/ActionStack.js:56:25) at PlatformApiPoly.addPlugin (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/platforms/PlatformApiPoly.js:262:20) at handleInstall (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:602:6) at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:391:24 at _fulfilled (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54) Uh oh! "/private/tmp/gimlet/70256508913260/2067507/project/cordova/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies/sqlite3.c" not found!` 

I was asking for the latest version with a source of npm.

I understand from #466 that you aren't supporting PhoneGap Build as it stands. For anyone who comes across this, I have managed to build successfully by locking the plugin in the config.xml:

`<plugin name="cordova-sqlite-storage" source="npm" spec="~0.8.5"/>`

The following versions seem to work - at least, they build successfully, I haven't been able to test beyond that:
- 0.8.5
- 1.2.0
- 1.2.1

1.4.0 and 1.4.0 cause the above error.

**Comment by brody2consult** [comment]
Thanks @jfi for reporting your findings. This plugin is now using a`before_plugin_install` hook in plugin.xml to fetch sqlite3 dependencies via npm and PhoneGap Build (PGB) evidently does not support this.

Older versions will not be supported and may miss important updates, such as fixing the wrong default iOS database location.

I can think of two possible ways forward to supporting this plugin with PGB:
1. If anyone wants to raise an issue at https://github.com/phonegap/build/issues with an objective that you should be able to install this plugin run the self test functions, PGB should be able to solve this.
2. If anyone wants to purchase a few hours of support from me I would be happy to re-enroll with PGB and work with PGB to get this working. You may contact me at brodybits@litehelpers.net or sales@litehelpers.net if you are interested.

**Comment by jfi** [comment]
@brodybits Thanks, dropped you an email about option 2. 👍

**Comment by derksacklowski** [comment]
Are there any news on this topic as i'm unable to use the current version of the plugin with cordova/ionic-cli. The build process fails, showing the exact same error message.

Cheers

**Comment by brody2consult** [comment]
@derksacklowski can you please confirm that you get this error message when using Cordova from a **local** installation of the Ionic CLI?

If so then please raise a new issue since I want to treat this separately from the issue with PhoneGap Build.

**Comment by derksacklowski** [comment]
Nevermind, i had a problem with my local node installation.

**Comment by daniel-lang** [comment]
Is there a way to get the current version (1.4.1) running with PhoneGap Build? What is the current situation of this issue?

**Comment by Dineshrajaa** [comment]
I am also facing the same issue working fine with ~0.8.5 version will be fine if we get support for 1.4.3 too.

**Comment by brody2consult** [comment]
The version at https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free supports PhoneGap Build and is available under GPL and commercial license options. For commercial license please contact: sales@litehelpers.net

**Comment by brody2consult** [comment]
#529 has discussion whether or not to keep cordova-sqlite-ext in a separate version. Another idea under consideration would be to include the sqlite3 dependencies in cordova-sqlite-ext as a long term solution to support PhoneGap Build, Intel XDK, etc.

**Comment by lyntechsupport** [comment]
Any updates on this @brodybits  

"    If anyone wants to purchase a few hours of support from me I would be happy to re-enroll with PGB and work with PGB to get this working. You may contact me at brodybits@litehelpers.net or sales@litehelpers.net if you are interested.

@jfi
jfi commented on May 12

@brodybits Thanks, dropped you an email about option 2. 👍
"

will it now support phonegap?
or are we having to use ext?

**Comment by brody2consult** [comment]
The following versions work on PhoneGap Build:
- https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free (GPL or commercial license options)
- https://github.com/litehelpers/Cordova-sqlite-legacy-build-support (permissive licensing like this version)

This is already documented. Maybe it is not clear enough.

At the moment https://github.com/litehelpers/Cordova-sqlite-legacy-build-support does contain all features that are in this version. But this may change in the future (sqlite3 update, for example).

**Comment by lyntechsupport** [comment]
So our only option is 500 dollar licence or a legacy version??

**Comment by brody2consult** [comment]
Those are the options at the moment if you use PhoneGap Build and do not want to follow the GPL.
