### ISSUE TITLE
Intel XDK undefined

### ISSUE THREAD

**Issue by Moghul** [brody2consult/cordova-sqlite-storage#480]
So, installing from git repo directly with the Intel XDK gives me the following error:

Uh oh! "E:\path\to\application\plugins\cordova-sqlite-storage\node_modules\cordova-sqlite-storage-dependencies\libs\sqlite-connector.jar" not found!

The error doesn't really make sense to me but is that because the latest version is unstable or... what?

EDIT: It adds fine with 1.4.0 from pulled repo but I haven't tested yet.

EDIT2: This code

document.addEventListener("deviceready", deviceReady, false);
function deviceReady() {
    cordova.getAppVersion.getPackageName(function(value){
        console.log(value);
    });

```
window.sqlitePlugin.echoTest(function(msg){
    console.log(msg);
}, function(e){
    console.log(e);
});
```

}

returns the following error: "Uncaught TypeError: Cannot read property 'echoTest' of undefined" at the window.sqlitePlugin.echoTest line (of course).

The other plugin works fine so Cordova is defined.

EDIT 3: I just checked the build and the plugin just doesn't get installed in the app... So strange.

So, I removed the engine requirements and it gives me the initial error. I am guessing it's just not compatible with Cordova 5.4.1. Which version of the plugin is, though? I tried with the featured 1.2.1 and it didn't work either.

**Comment by brody2consult** [comment]
> So, installing from git repo directly with the Intel XDK gives me the following error:
> 
> Uh oh! "E:\path\to\application\plugins\cordova-sqlite-storage\node_modules\cordova-sqlite-storage-dependencies\libs\sqlite-connector.jar" not found!

Starting with `1.4.0` this project uses a `before_plugin_install` hook to fetch some dependencies via npm. Unfortunately this is not supported by PhoneGap Build and evidently not by Intel XDK.

You _should_ be able to install and use `1.2.2` or earlier with Intel XDK.

**Comment by Moghul** [comment]
1.2.1 didn't work either. I went all the way back to 0.7.14 which worked fine on Android.
Have yet to test on iOS.

**Comment by brody2consult** [comment]
This is pretty strange. Did you try `1.2.2`?

**Comment by Moghul** [comment]
The latest featured version is, according to the Intel XDK UI, 1.2.1. I have yet to try 1.2.2 as I'm testing 0.7.14 right now.

http://i.imgur.com/Zm4O8T0.png

I'll check later if 0.7.14 fails.

EDIT: 0.7.14 works fine.

**Comment by brody2consult** [comment]
Please see #489 for further discussion.
