### ISSUE TITLE
cordova-sqlite-storage 1.2.1 doesn't seem to work on Android 5.1/6 with Cordova 6.0.0

### ISSUE THREAD

**Issue by nitzanwilnai** [brody2consult/cordova-sqlite-storage#481]
I am using cordova-sqlite-storage 1.2.1. 

It definitely worked in the past. 

Now the same code that used to work doesn't run anymore. No error messages. 

This call:             m_localSQLDatabase = window.sqlitePlugin.openDatabase({name: 'my.db', location: 'default'}, function(){log("DB success");}, function(){log("DB error");});

Doesn't return anything. DB success nor DB error are returned. 

Works fine on iOS.

**Comment by nitzanwilnai** [comment]
I should add that the test code does not work either. It seems like the plugin is installed, but is not running properly. 

In chrome console I called:

```
window.sqlitePlugin.openDatabase({ name: 'hello-world.db', location: 'default' }, function (db) {
    db.executeSql("select length('tenletters') as stringlength", [], function (res) {
      var stringlength = res.rows.item(0).stringlength;
      console.log('got stringlength: ' + stringlength);
      document.getElementById('deviceready').querySelector('.received').innerHTML = 'stringlength: ' + stringlength;
   });
  });
```

this is the response received:

```
SQLitePlugin.js:175 OPEN database: hello-world.db
SQLitePlugin {openargs: Object, dbname: "hello-world.db"}
```

**Comment by brody2consult** [comment]
Please try the latest version which is 1.4.1. If it does not work please try it with a fresh, clean project with no other plugins or major frameworks such as Angular/Ionic/React/React Native installed.

**Comment by nitzanwilnai** [comment]
That worked. Thanks!
