### ISSUE TITLE
Cannot add plugin to intel xdk, shows missing sqlite-connector.jar file

### ISSUE THREAD

**Issue by SUBINARTIFICERS** [brody2consult/cordova-sqlite-storage#484]
When i try to add this plugin to my project in Intel Xdk, its shows

projectname\plugins\cordova-sqlite-storage\node_modules\cordova-sqlite-storage-dependencies\libs\sqlite-connector.jar" not found!.

**Comment by brody2consult** [comment]
Apparently the `before_plugin_install` Cordova hook used by this project is not supported by the Intel XDK. Let me think about how to solve this.

**Comment by SUBINARTIFICERS** [comment]
solve this issue by download the sqlite dependency jar file and create the directory ,place the jar file in it. Now plugin add working good.

**Comment by brody2consult** [comment]
Thanks for the workaround solution. I will documented this when I get a
chance. I would like to see a more automatic solution sometime in the
future.

**Comment by AjaySandhu** [comment]
Hi there, trying to install the plugin but getting the same error. Please can you tell me where can I find the file to download it and where should I create the directory?

Please let me know

Many thanks,

Ajay

**Comment by payen83** [comment]
If you are importing plugin using Intel XDK

1. Download the dependencies from: https://github.com/litehelpers/Cordova-sqlite-storage-dependencies (save as zip file)

2. Extract the zip file in 1 folder

3. Copy all files inside the folder

4. Back to the "cordova-sqlite-storage-master" folder, Go inside the folder cordova-sqlite-storage-master/node_modules/ 
 - Create a folder name "cordova-sqlite-storage-dependencies" then paste all files inside the new folder

5. Try import local plugin (cordova-sqlite-storage-master) again using Intel XDK and you should be good
