### ISSUE TITLE
1.4.1 not installing on Intel XDK

### ISSUE THREAD

**Issue by iodev** [brody2consult/cordova-sqlite-storage#489]
Message pops up and says "...\plugins\cordova-sqlite-storage\node_modules\cordova-sqlite-storage-dependencies\libs\sqlite-connector.jar" not found!  So, temporarily, I installed 1.2.0 ... to try it out.

**Comment by brody2consult** [comment]
Yes. If you use Intel XDK it does not honor the before_plugin_install hook. Same as #480, similar to #477 (PhoneGap Build issues with 1.4.0+). See cordova/cordova-discuss#38 for discussion.
