### ISSUE TITLE
Unable to run example code on Cordova WP8

### ISSUE THREAD

**Issue by sumitsoman** [brody2consult/cordova-sqlite-storage#490]
I added the plugin to a cordova wp8 project and ran the sample code in a javascript function.

```
window.sqlitePlugin.openDatabase({ name: 'hello-world.db', location: 'default' }, function (db) {
    db.executeSql("select length('tenletters') as stringlength", [], function (res) {
        var stringlength = res.rows.item(0).stringlength;
       alert('got stringlength: ' + stringlength);
      });
});
```

This does not work and I get the error in the console as

> Unable to get property 'openDatabase' of undefined or null reference. Source File: x-wmapp0:www/js/CreateTableScript.js, Line: 2
> Unable to get property 'querySelector' of undefined or null reference. Source File: x-wmapp0:www/js/index.js, Line: 41

How can I fix this?

**Comment by brody2consult** [comment]
Please use Cordova-sqlite-legacy if you need to support WP8. It is already
documented in README.md.

**Comment by sumitsoman** [comment]
Using cordova-sqlite-legacy gives the same issue.

**Comment by brody2consult** [comment]
On Mon, May 30, 2016 at 12:27 PM, Sumit Soman notifications@github.com
wrote:

> Using cordova-sqlite-legacy gives the same issue.

It sounds like an installation issue. Please start with a fresh, clean
project, try adding cordova-sqlite-legacy with no other plugins and try the
echoTest as described in its README.

**Comment by sumitsoman** [comment]
Still get this error:

> Unable to get property 'querySelector' of undefined or null reference. Source File: x-wmapp0:www/js/index.js, Line: 41

No success message appears. This is the script.

```
// Wait for Cordova to load
//
document.addEventListener("deviceready", onDeviceReady, false);

// Cordova is ready
//
function onDeviceReady() {
    window.sqlitePlugin.echoTest(successCallback, errorCallback);
}
// Transaction success callback
//
function successCallback() {
    alert("success!");
}

function errorCallback() {
     alert("error!");
}

window.onerror = function (message, file, line) {
    window.external.Notify("Error in Application: " + message + ". Source File: " + file + ", Line: " + line);
}
```

**Comment by brody2consult** [comment]
Moving discussion to litehelpers/Cordova-sqlite-legacy#4
