### ISSUE TITLE
Cannot read property 'executeSql' of null

### ISSUE THREAD

**Issue by ghost** [brody2consult/cordova-sqlite-storage#495]
Hi everyone! I try to select some values from my db in chartd.js but db created in another file named litedb.js below i attach my code and logs. I will be very grateful for any help! 
**chartd.js**
`var db = null;
angular.module('starter.chart', ['ionic', 'chart.js', 'ngCordova'])
.controller("DoughnutCtrl", function ($scope,$cordovaSQLite, $ionicPlatform) {
 $ionicPlatform.ready(function() {
var db = window.sqlitePlugin.openDatabase({name: 'my.db', location: 'default'});
// }, function (error) {
//     console.log('Open database ERROR: ' + JSON.stringify(error));
// });
  });
    function selChart(){
    $scope.labels = [];
    $scope.data = [];
    db.executeSql("SELECT sum, category FROM smsdata", [], function (result) {
         for(var x = 0; x < result.rows.length; x++) {
  console.log(' Sum: ' + result.rows.item(x).sum + 
    ' category: ' + result.rows.item(x).category);

  $scope.data.push({sum:result.rows.item(x).sum});
  $scope.labels.push({category:result.rows.item(x).category});

};
}, function(error) {
  console.log('SELECT error: ' + error.message);
});
}
 selChart();
});  `

**litedb.js**  where I created my db <br>
`var db = null;

angular.module('starter.litedb', ['ionic','ngCordova'])

// db controller
.controller("LitedbCtrl", function($scope, $ionicPlatform, $cordovaSQLite){

```
var db = window.sqlitePlugin.openDatabase({ name: 'my.db', location: 'default' }, function () {
db.executeSql("CREATE TABLE IF NOT EXISTS smsdata (id integer primary key, cardnum text, datat text, eventt text, sum text, category text, total text)");
```

}, function (error) {
    console.log('Open database ERROR: ' + JSON.stringify(error));
});

function addItem(cardnum, datat, eventt, sum, category, total) {
    db.transaction(function (tx) {
        var query = "INSERT INTO smsdata (cardnum, datat, eventt, sum, category, total) VALUES (?, ?, ?, ?, ?, ?)";
        tx.executeSql(query, [cardnum, datat, eventt, sum, category, total], function(tx, res) {
            console.log("insertId: " + res.insertId);
            console.log("rowsAffected: " + res.rowsAffected);
        },
        function(tx, error) {
            console.log('INSERT error: ' + error.message);
        });
    }, function(error) {
        console.log('transaction error: ' + error.message);
    }, function() {
        console.log('transaction ok');
    });
}
});
`
[And logs](http://cs630017.vk.me/v630017066/33de5/dubcIpp5zA4.jpg)

**Comment by brody2consult** [comment]
Please be sure that both sqlitePlugin.openDatabase calls wait for the deviceready event. I suspect this is not the case in litedb.js. I already added a warning in README.md.

I am busy with an urgent project for the next 2-3 weeks and am ending free support for Ionic/Angular/ngCordova. There are free starter projects and tutorials with and without pre-populated databases.

**Comment by ghost** [comment]
@brodybits I appologize for my inadvertence,  yestarday I find a right answer in README.md! Thank you for reply and many thanks for the plugin!
