### ISSUE TITLE
Logs in Deployed Apps

### ISSUE THREAD

**Issue by AtomLegend** [brody2consult/cordova-sqlite-storage#497]
Hello

Could you please remove the NSLogs when the app is compiled for release builds? 
One can easily read them with Xcode, which is a security risk. Besides that it is just bad practice to have NSLogs in release builds.
I would really appreciate if you guys could fix this. If you want, I can make this for you and create a pull request.

**Comment by brody2consult** [comment]
A pull request to fix this would be great, thanks!

**Comment by brody2consult** [comment]
Thanks for PR #498, now included.
