### ISSUE TITLE
openDatabase fails on Windows 10

### ISSUE THREAD

**Issue by JohnBrammas** [brody2consult/cordova-sqlite-storage#501]
- I built a basic app in Windows 10. 
- Added cordova-sqlite-storage plugin (v. 1.4.1) so only this and the whitelist plugins are installed.

The function testDB() gets called in onDeviceReady().

```

function testDB() {
    var name = 'myDB';
    var displayName = 'myDB';
    var size = 10 * 1024 * 1024;
    var version = '1.0';

    var db = window.openDatabase(name, version, displayName, size);
}
```

This fails with: 
Unhandled exception at line 40, column 5 in ms-appx-web://<APP-ID>/www/scripts/index.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'openDatabase'

(Line 40 -> var db =  ...)

**Comment by brody2consult** [comment]
Your code follows the Web SQL API, which is **not** available in the Windows platform. Please read the and follow the documentation very carefully.

I will add this as a common pitfall when I get a chance.

**Comment by daniele-sartiano** [comment]
I have the same problem, but I'm using ionic 2 with SqlStorage.

**Comment by JohnBrammas** [comment]
After I followed the documentation everything worked fine for me.

**Comment by daniele-sartiano** [comment]
@JohnBrammas  can you suggest me the part of documentation that solved your problem?

**Comment by JohnBrammas** [comment]
I replaced 
`var db = window.openDatabase(...)`
with
`var db = window.sqlitePlugin.openDatabase(...)`
which fixed the problem for me.
