### ISSUE TITLE
database not prepopulating in android 6.0.1

### ISSUE THREAD

**Issue by appglobaltech** [brody2consult/cordova-sqlite-storage#503]
I am prepopulating database by including in www directory and in on deviceready function the transaction is successfull.

var db = window.sqlitePlugin.openDatabase({name: 'abc.db', location: 'default', androidDatabaseImplementation: 2});
    db.transaction(function (tx) {
    });

Now in click event I am writing 
var db = window.sqlitePlugin.openDatabase({ name: 'abc.db' , location : 'default', androidDatabaseImplementation: 2});

db.executeSql("select \* from product_list",[], function (resultSet) {
                alert(resultSet.rows.length);
            }, function(error) {
                alert('SELECT error: ' + error.message);
            });

It says there is no such table....that means it creates new database....
database is not repopulating when using this plugin....

**Comment by brody2consult** [comment]
Please use cordova-sqlite-ext for pre-populated databases. This is already documented.
