### ISSUE TITLE
Sqlstorage not working on my android device 

### ISSUE THREAD

**Issue by saurabhvyas** [brody2consult/cordova-sqlite-storage#509]
I am getting this error in device logs  

unexpected error

06-30 07:01:57.655 E/SQLitePlugin( 2489): java.lang.IllegalArgumentException: exec is not a constant in io.sqlc.SQLitePlugin$Action

06-30 07:01:57.655 E/SQLitePlugin( 2489):   at java.lang.Enum.valueOf(Enum.java:200)

06-30 07:01:57.655 E/SQLitePlugin( 2489):   at io.sqlc.SQLitePlugin$Action.valueOf(SQLitePlugin.java:423)

06-30 07:01:57.655 E/SQLitePlugin( 2489):   at io.sqlc.SQLitePlugin.execute(SQLitePlugin.java:61)

06-30 07:01:57.655 E/SQLitePlugin( 2489):   at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)

06-30 07:01:57.655 E/SQLitePlugin( 2489):   at org.apache.cordova.PluginManager.exec(PluginManager.java:133)

06-30 07:01:57.655 E/SQLitePlugin( 2489):   at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)

06-30 07:01:57.655 E/SQLitePlugin( 2489):   at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)

06-30 07:01:57.655 E/SQLitePlugin( 2489):   at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)

06-30 07:01:57.655 E/SQLitePlugin( 2489):   at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)

06-30 07:01:57.655 E/SQLitePlugin( 2489):   at android.os.Handler.dispatchMessage(Handler.java:102)

06-30 07:01:57.655 E/SQLitePlugin( 2489):   at android.os.Looper.loop(Looper.java:135)

06-30 07:01:57.655 E/SQLitePlugin( 2489):   at android.os.HandlerThread.run(HandlerThread.java:61)

06-30 07:01:57.664 E/SQLitePlugin( 2489): unexpected error

I am running cordova 6.2
JDK 1.8 
Node v5
Ionic beta 9

**Comment by JamalANasier** [comment]
Nahh i prove it this is not an issue, check my post.

If you read carefully and do a lot of tests and console logs, you will be fine buddy.

**Comment by saurabhvyas** [comment]
where is your post that you are referring to ?,If you were referring to the post you posted recently I dont understand how that is related and its in Ionic1, I think I will create a fresh project and just add this plugin and see if a simple query is working or not

Update: I have performed device logging, I am getting error is undefined , So even error handling with promise is not giving any useful info

**Comment by brody2consult** [comment]
You may want to try the sample at: https://github.com/litehelpers/Ionic-sqlite-database-example

Ionic and other Angular frameworks are no longer supported for free. For professional support you may contact: sales@litehelpers.net
