### ISSUE TITLE
cannot start transaction within transaction sqlite error

### ISSUE THREAD

**Issue by sagarhiremath6** [brody2consult/cordova-sqlite-storage#512]
I am using sqlite3. I am stuck with 'cannot start transaction within transaction sqlite' error. I am using Javascript functions to do DB operations.

Here is my sample code.

`document.addEventListener('deviceready', onDeviceReady, false);
      function onDeviceReady()
      {
         DbSetup();
$(document).on("click","#storyPost",function() {
                  insert();
            })
      }

var db;
function DbSetup()
{

db  = window.sqlitePlugin.openDatabase({name: 'testing', location: 'default'});
       db.transaction(function(tx) {
                    var create_sql = 'CREATE TABLE IF NOT EXISTS story(Nid integer primary key AUTOINCREMENT, title TEXT)';
                      tx.executeSql( create_sql,[], function (tx, results) {
                            console.log('table created');
                      });
                  }, function(err) {
                       navigator.notification.alert(
                                 err,                            // message
                                 alertDismissed,                   // callback
                                 'Database open error',            // title
                                 'OK'                              // buttonName
                              );
                       console.log('Open database ERROR: ' + JSON.stringify(err));
                  });

}

function insert()
{
var insert_sql = "INSERT INTO story(title) VALUES(?)";
db.transaction(function(transaction) {
     transaction.executeSql( insert_sql, [title], function (resultSet) {
        }, function(error) {
             navigator.notification.alert(
                             error,                            // message
                             alertDismissed,                   // callback
                             'Story upload error',            // title
                             'OK'                              // buttonName
                          );
            console.log('Insert error: ' + error.message);
         });

```
 });
```

}`

Can any one tell me where its going wrong?

**Comment by brody2consult** [comment]
Hi @sagarhiremath6,

I think you have found a bug and will need some help to reproduce this. Can you make an isolated reproduction program and either post it or send it to brodybits@litehelpers.net?

Also: which platform did you see this on?

**Comment by sagarhiremath6** [comment]
Its android platform. 
What is happening is: if I put my insert query after table creation in single transaction ( that is in DbSetup() function ) then it works fine, no issues with that.

But If I try insert transaction on HTML button event ( that is in insert() function ) then it throws 'cannot start transaction within transaction sqlite' error.

**Comment by brody2consult** [comment]
I can make a test program for this case within the next 1-2 days. It would be faster if you can post or send me a test app.

**Comment by brody2consult** [comment]
I made a test based on your JavaScript code (with a few minor fixes) using Bootstrap and JQuery, and it is working OK on both Android and iOS. Please post a test project to demonstrate your issue otherwise I will assume it is a bug in your own application.

**Comment by sagarhiremath6** [comment]
Thanks brodybits for all help. Its working now.  Issue was deviceReady was getting called for each form submit button, that means DbSetup was getting called multiple times. Its not issue with plugin.
