### ISSUE TITLE
Failed to restore plugin "SQLitePlugin" from config.xml

### ISSUE THREAD

**Issue by sgs1** [brody2consult/cordova-sqlite-storage#518]
Hello!

I've followed this tutorial:

https://dileepyadav.wordpress.com/2014/11/26/complete-solution-of-apache-cordova-sqliteplugin/

but when I type "cordova build", i see this error:
Failed to restore plugin "SQLitePlugin" from config.xml. You might need to try adding it again. Error: Error: Registry returned 404 for GET on https://registry.npmjs.org/SQLitePlugin

What does it mean?
Thank you

**Comment by brody2consult** [comment]
It looks like a nice article but that way of installation is not supported. It is recommended to start from a new Cordova project. You may also want to use https://github.com/brodybits/Cordova-sqlite-starter-test as a starting point.

**Comment by KishorMi** [comment]
hi i m getting error in my cordova app. i m using mac
Failed to restore plugin "Storage" from config.xml. You might need to try adding it again. Error: Error: Registry returned 404 for GET on https://registry.npmjs.org/Storage.
