### ISSUE TITLE
QUESTION - Typescript typings recommendation

### ISSUE THREAD

**Issue by jonnysmith1981** [brody2consult/cordova-sqlite-storage#522]
In a TypeScript project, when data is returned we access it like this (as an example):

`db.executeRequest(sqlCmd, params).then((res) => {
   let pokemon = res.rows.item(0);
}`

However the TypeScript transpiler complains that `Property 'rows'  does not exist on type '{}[]'`.

To get round this we have been typing the `res` as `any` but this feels a bit hacky. I was wondering if there were any typings available for this plugin?

**Comment by brody2consult** [comment]
You may want to check out:
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/cordova/plugins/WebSQL.d.ts
- https://github.com/retyped/websql-tsd-ambient

They may need some adaptation to work with the openDatabase call as implemented by this plugin.

For the future, I would like to see a Web SQL database wrapper that solves this for both this plugin and Web SQL in the browser.

**Comment by jonnysmith1981** [comment]
Brilliant, thank you. I didnt mentally join the dots between the plugin following the WebSQL standard, and using the actual WebSQL typings.
