### ISSUE TITLE
window.sqliteplugin.opendatabase undefined

### ISSUE THREAD

**Issue by ghost** [brody2consult/cordova-sqlite-storage#523]
Hi,

When running my app on an android device using version 6.0.1 I get an error saying cannot read openDatabase of undefined.

Have tested with iOS and works perfectly.

Here is my connection details:

`var db = window.sqlitePlugin.openDatabase({name: "my.db", location: 'default'});`

Which is called like this:

`document.addEventListener("deviceready", onDeviceReady, false);

```
    function onDeviceReady() {

        var width = $(window).width();

        if (width <= 500) {
            screen.lockOrientation('portrait');
        }

        databaseSetup.setup();
```

}`

And finally attached
[config.txt](https://github.com/litehelpers/Cordova-sqlite-storage/files/385815/config.txt)
 is my config.xml

I am using it with AngularJS and the controllers are called based on the route rather than being bound to HTML itself.

Sorry for the long post just wanted you to have all the information.

Any help / guidance into finding this issue would be great.

Thanks,

Harry

**Comment by brody2consult** [comment]
This sounds like an installation issue. I suggest you try the echoTest and selfTest functions to help pinpoint the actual problem.

Support for use with Angular is available within the professional support program. For more details please check http://litehelpers.net or contact sales@litehelpers.net

**Comment by ghost** [comment]
Hi,

I now get "Uncaught TypeError: Cannot read property 'echoTest' of undefined", source: file:///android_asset/www/js/app.min.js"

If it works on iOS fine would it be an installation issue? Seems like it just isn't loading the plugin for it.

Any  further advice would be amazing.

Thanks,

Harry

**Comment by brody2consult** [comment]
I suggest you try https://github.com/brodybits/Cordova-sqlite-starter-test and see if it solves your problem. In case of further problems please post a test project based on https://github.com/brodybits/Cordova-sqlite-starter-test (with no Angular) and I would be happy to take a look. For professional support you may contact: sales@litehelpers.net

**Comment by ghost** [comment]
Hi,

Thanks for your help - the problem was me not reading correctly and using this version with Adobe Phonegap build.... Have used https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free and all is working as it should now.

Thanks again,

Harry

**Comment by ghost** [comment]
I am trying to sort out the error but in android devices showing 
Uncaught TypeError: Cannot read property 'openDatabase' of undefined
    at Channel.<anonymous> (index.js:4)
    at Channel.fire (cordova.js:846)
    at cordova.js:231

and in the browser 
OPEN database: my.db
cordova.js:1001 Error: exec proxy not found for :: SQLitePlugin :: close
cordova.js:1001 Error: exec proxy not found for :: SQLitePlugin :: open
SQLitePlugin.js:196 OPEN database: my.db FAILED, aborting any pending transactions
SQLitePlugin.js:82 Could not open database


index.html
<html>
    <head>

        <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="initial-scale=1, width=device-width, viewport-fit=cover">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <title>Hello World</title>
    </head>
    <body>
        <div class="app">
            <h1>Apache Cordova</h1>
            <div id="deviceready" class="blink">
               
             
            </div>
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
    </body>
</html>


Index.js
var db = null;

document.addEventListener('deviceready', function() {
  db = window.sqlitePlugin.openDatabase({
    name: 'my.db',
    location: 'default',
  });
});





Please helppppppp
