### ISSUE TITLE
cordova-sqlite-storage build.phonegap.com issue last version (Uh

### ISSUE THREAD

**Issue by SvenAtGit** [brody2consult/cordova-sqlite-storage#524]
When using the buildserver https://build.phonegap.com the last version   of the cordova-sqlite-storage plugin  is not working.

The error is: 

> "plugman install --platform ios --project /project --plugin cordova-sqlite-storage": Fetching plugin "cordova-sqlite-storage" via npm
> Installing "cordova-sqlite-storage" at "1.4.6-pre5" for ios
> Error during processing of action! Attempting to revert...
> Failed to install 'cordova-sqlite-storage':CordovaError: Uh oh!
> "/private/project/cordova/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies/sqlite3.c" not found!
>     at copyFile (/private/project/cordova/lib/plugman/pluginHandlers.js:274:36)
>     at copyNewFile (/private/project/cordova/lib/plugman/pluginHandlers.js:306:5)

The build server supports until phonegap cli version cli-6.3.0

```
<preference name="phonegap-version" value="cli-6.3.0" /> 
<plugin name="cordova-sqlite-storage" />
```

A workaround is to use an older version, however this older version but this is not working for the windows 10 build.

```
<preference name="phonegap-version" value="cli-6.3.0" /> 
<plugin name="cordova-sqlite-storage" version="1.2.1" />
```

**Comment by brody2consult** [comment]
PhoneGap Build is supported by the following versions:
- https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free (available under GPL or commercial licenses)
- https://github.com/litehelpers/Cordova-sqlite-legacy-build-support

For Windows please see the discussions in:
- phonegap/build#530
- https://forums.adobe.com/message/8905272

**Comment by brody2consult** [comment]
This is now documented, closing.

Ongoing discussions for Windows:
- https://github.com/litehelpers/Cordova-sqlite-legacy-build-support/issues/10
- https://forums.adobe.com/message/9123283

**Comment by Shardj** [comment]
Do those work with pouchdb? The sqlite adaptor by default uses this plugin
