### ISSUE TITLE
Ionic callback

### ISSUE THREAD

**Issue by TommyQu** [brody2consult/cordova-sqlite-storage#527]
I have a question, in normal cordova js, I have a callback function when transaction is done.

```
db.readTransaction(function(tx) {
  tx.executeSql("SELECT UPPER('Some US-ASCII text') AS uppertext", [], function(tx, resultSet) {
    console.log("resultSet.rows.item(0).uppertext: " + resultSet.rows.item(0).uppertext);
  }, function(tx, error) {
    console.log('SELECT error: ' + error.message);
  });
}, function(error) {
  console.log('transaction error: ' + error.message);
}, function() {
  console.log('transaction ok');
});
```

But in ionic, do we have such callback function? I tried the below code but seems not work.

```
$cordovaSQLite.execute(db, "delete from table1;", []).then(function(res) {

}, function(err) {
    console.error(err);
}, function() {
    alert("aa");
});
```

**Comment by brody2consult** [comment]
The ngCordova has a different API. It looks like the code does not follow the Promise API correctly. You may want to try the code like this:

``` js
$cordovaSQLite.execute(db, "delete from table1;", []).then(function(res) {
  console.log('delete success');
  alert('aa delete success');
}, function(err) {
    console.error(err);
});
```

I will add a note that the ngCordova sqlite API is different.

A commercial support package is required for further support with ngCordova or Angular. You may reach out to: sales@litehelpers.net
