### ISSUE TITLE
Is executeSql more efficient than $cordovaSQLite.execute?

### ISSUE THREAD

**Issue by TommyQu** [brody2consult/cordova-sqlite-storage#528]
Usually, we do transactions like below, it seems run fast when doing muliple executeSql commands.

```
db.transaction(function(tx) {
    tx.executeSql();
    tx.executeSql();
    tx.executeSql();
});
```

However, in Ionic, I'm trying something like below, which runs slower than executeSql:

```
$cordovaSQLite.execute();
$cordovaSQLite.execute();
$cordovaSQLite.execute();
```

**Comment by brody2consult** [comment]
Yes. This is because the ngCordova implementation uses a transaction for each `$cordovaSQLite.execute()` call. The ngCordova implementation should be fixed to simply use `db.executeSql()` instead.

_P.S. This is the code that should be fixed: https://github.com/driftyco/ng-cordova/blob/master/src/plugins/sqlite.js#L26-L33_

**Comment by TommyQu** [comment]
@brodybits 
Thanks for your response. I tried to fix the code, but I don't see the performance improvement. Did I do something wrong?

Original code:

```
            execute: function(n, r, o) {
                var t = e.defer();
                return n.transaction(function(e) {
                    e.executeSql(r, o, function(e, n) {
                        t.resolve(n)
                    }, function(e, n) {
                        t.reject(n)
                    })
                }), t.promise
            },
```

Code changed:

```
            execute: function(n, r, o) {
                var t = e.defer();
                return n.executeSql(r, o, function(e, n) {
                        t.resolve(n)
                    }, function(e, n) {
                        t.reject(n)
                    }), t.promise
            },
```

**Comment by brody2consult** [comment]
I could speculate about some things but really cannot make any conclusions without taking some time for proper investigation and testing. I do have some backlog and am not sure when I would get a chance to do the testing and investigation.

**Comment by TommyQu** [comment]
It's Ok. Thanks for the instructions.
