### ISSUE TITLE
CDVPlugin class SQLitePlugin (pluginName: SQLitePlugin) does not exist

### ISSUE THREAD

**Issue by abada** [brody2consult/cordova-sqlite-storage#53]
SQLitePlugin openargs: {"name":"db.sqlite"}
CDVPlugin class SQLitePlugin (pluginName: SQLitePlugin) does not exist.
ERROR: Plugin 'SQLitePlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.

-[CDVCommandQueue executePending] [Line 158] FAILED pluginJSON = [
  "SQLitePlugin756881153",
  "SQLitePlugin",
  "open",
  [
    {
      "name" : "db.sqlite"
    }
  ]
]

ios 7.1  and ohonegap 3.4.0

**Comment by cballock** [comment]
I followed the installation process exactly but had this same problem with the SQLitePlugin. For everyone else who steps by this issue, try removing and adding your platform again (in my case, it was platform/ios since I am developing for an iPhone). Then rebuild your project. It worked for me.

**Comment by brody2consult** [comment]
Thanks @cballock I just added your idea as part of https://github.com/litehelpers/Cordova-sqlite-help/issues/25 to document general troubleshooting steps.
