### ISSUE TITLE
can't install latest version plugin

### ISSUE THREAD

**Issue by kerryf88** [brody2consult/cordova-sqlite-storage#537]
I'm having issue with installing the latest version of the plugin. 

> Fetching plugin "Cordova-sqlite-storage" via npm
> Installing "cordova-sqlite-storage" for ios
> installing external dependencies via npm
> npm install of external dependencies failed: Error: Command failed: /bin/sh -c npm install
> npm WARN locking Error: EACCES, open '/Users/kerryfang/.npm/_locks/cordova-sqlite-storage-d-40ce6082ae94cd26.lock'
> npm WARN locking     at Error (native)
> npm WARN locking  /Users/kerryfang/.npm/_locks/cordova-sqlite-storage-d-40ce6082ae94cd26.lock failed { [Error: EACCES, open '/Users/kerryfang/.npm/_locks/cordova-sqlite-storage-d-40ce6082ae94cd26.lock']
> npm WARN locking   errno: -13,
> npm WARN locking   code: 'EACCES',
> npm WARN locking   path: '/Users/kerryfang/.npm/_locks/cordova-sqlite-storage-d-40ce6082ae94cd26.lock' }
> npm ERR! Darwin 15.5.0
> npm ERR! argv "node" "/usr/local/bin/npm" "install"
> npm ERR! node v0.12.7
> npm ERR! npm  v2.11.3
> npm ERR! Attempt to unlock /usr/local/lib/simple/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies, which hasn't been locked
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     https://github.com/npm/npm/issues
> npm ERR! Please include the following file with any support request:
> npm ERR!     /usr/local/lib/simple/plugins/cordova-sqlite-storage/npm-debug.log
> Error during processing of action! Attempting to revert...
> Failed to install 'cordova-sqlite-storage':Error: Uh oh!
> "/usr/local/lib/simple/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies/sqlite3.c" not found!
>     at Object.module.exports.common.copyFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:38:40)
>     at Object.module.exports.common.copyNewFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:69:16)
>     at installHelper (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:54:16)
>     at Object.module.exports.source-file.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:139:13)
>     at installWrapper (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
>     at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
>     at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:576:20)
>     at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:363:28
>     at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
>     at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
> Error: Uh oh!
> "/usr/local/lib/simple/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies/sqlite3.c" not found!
>     at Object.module.exports.common.copyFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:38:40)
>     at Object.module.exports.common.copyNewFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:69:16)
>     at installHelper (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:54:16)
>     at Object.module.exports.source-file.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:139:13)
>     at installWrapper (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
>     at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
>     at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:576:20)
>     at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:363:28
>     at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
>     at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)

The highest version I can install is 1.2.0. My current Cordova version is 3.9.2. PhoneGap version 5.3.6.  I'm building an app using xCode with PhoneGap on my Macbook and wanted to use Sqlite to create database. I'm really new to all these PhoneGap thing so I'm not sure why I can't install this.

**Comment by brody2consult** [comment]
For some reason your npm is getting stuck with something. Cordova versions older than 5.x are not supported. Also PhoneGap is _not_ supported since it does not honor the `before_plugin_install` hook. Please do the following:
- Upgrade Cordova to a recent version. It is also recommended to a recent version.
- Try working with a very simple plugin such as cordova-plugin-dialogs.
- If that works, then try something harder such as cordova-plugin-file.
- If you can get these to work then you can try adding this plugin.

As documented in README.md, here are some resources to get started with the Cordova CLI.
- http://cordova.apache.org/ (redirected from http://cordova.io)
- http://www.tutorialspoint.com/cordova/
- https://ccoenraets.github.io/cordova-tutorial/
- https://www.toptal.com/mobile/developing-mobile-applications-with-apache-cordova
- http://www.tutorialspoint.com/cordova/index.htm

More resources can be found by https://www.google.com/search?q=cordova+tutorial. There are even some tutorials available on YouTube as well.

Good luck!

**Comment by kerryf88** [comment]
Do you think I can use the Cordova-sqlite-evcore-extbuild-free plugin instead? I can install that fine and it's said to work with PhoneGap. Is that the same thing as Cordova-sqlite-storage? Can that create, store and view database aswell? And I do have other plugin installed successfully on my current version of cordova/phonegap, i.e the notification plugin and iSpeech plugin.

**Comment by GeorgeRamos** [comment]
I'm stucked with this message to install this plugin on ionic cordova . Some tips?

Error: Failed to fetch plugin https://github.com/litehelpers/Cordova-sqlite-storage.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! exited with error code: 128

**Comment by GeorgeRamos** [comment]
the command : ionic cordova plugin add https://github.com/litehelpers/
Cordova-sqlite-storage.git

**Comment by MichelJautzy** [comment]
Hey George, I had excatly the same problem , try the following (because default branch name is not master but storage-master): 
ionic plugin add https://github.com/litehelpers/Cordova-sqlite-storage#storage-master --save

**Comment by GeorgeRamos** [comment]
Thanks but I'm steel have same problem. Look the message bellow: 

D:\googleDrive\Sistemas\Desenvolvimento\Fk\FkDoc\TestDb\testSQLite>ionic cordova plugin add https://github.com/litehelpers/Cordova-sqlite-storage#storage-master --save
> cordova plugin add https://github.com/litehelpers/Cordova-sqlite-storage#storage-master --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add
        https://github.com/litehelpers/Cordova-sqlite-storage#storage... (exit
        code 1):

        Error: Failed to fetch plugin
        https://github.com/litehelpers/Cordova-sqlite-storage#storage-master via
        registry.
        Probably this is either a connection problem, or plugin spec is
        incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! code 128
        npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule
        update -q --init --recursive
        npm ERR! fatal: 'submodule' appears to be a git command, but we were not
        npm ERR! able to execute it. Maybe git-submodule is broken?
        npm ERR!

        npm ERR! A complete log of this run can be found in:
        npm ERR!
Thanks in advance for any tips
regards

**Comment by johnnynode** [comment]
I have the same puzzle in the first place, but when I try again, it worked!
```
$ cordova plugin add https://github.com/litehelpers/Cordova-sqlite-storage.git
Fetching plugin "https://github.com/litehelpers/Cordova-sqlite-storage.git" via git clone
Repository "https://github.com/litehelpers/Cordova-sqlite-storage.git" checked out to git ref "master".
Installing "cordova-sqlite-storage" for android
installing external dependencies via npm
npm install of external dependencies ok
ANDROID_HOME=/.../Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
Subproject Path: CordovaLib

> Configure project :
Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_gbu6pfq6xj89i8y3b1w77z6m.run(/../platforms/android/build.gradle:143)

> Configure project :CordovaLib
publishNonDefault is deprecated and has no effect anymore. All variants are now published.


BUILD SUCCESSFUL in 1s
2 actionable tasks: 1 executed, 1 up-to-date
```
