### ISSUE TITLE
Why aren't there any tags?

### ISSUE THREAD

**Issue by Defcon0** [brody2consult/cordova-sqlite-storage#543]
Hello,

at first thanks for the plugin! Nice work. Only one thing bothers me:

Why aren't there any stable tags which I can rely on when adding them to my cordova plugin json file? When installing the master branch and check out on another machine, I possibly get a different incompatible version :(

I don't have that much experience in cordova but in ordinary web development, I can tell composer to use a specific version (tag).

Using tags would also introduce semantic versioning.

Why only a master branch?

Bye Defcon0

**Comment by brody2consult** [comment]
Unfortunately I do not understand what you are asking. This project does use tags and you can install it from `npm`. It is possible to install an older version using an older release tag. The history is tracked in CHANGES.md.

This project includes SQLite library dependencies via `npm` but I think that is stable and does not change very often.

Another small thing is that this project does not actually have a standard `master` branch. The default branch is `storage-master` which is periodically merged directly or indirectly into the other versions that I maintain.

Please report if this helps you or if I am missing something here. Thanks!

**Comment by Defcon0** [comment]
Ah, thanks for clarification. I didn't know that cordova plugin add ...@version uses npm. I thought, also npm uses the tags in github like packagist does in the composer ecosystem. In this case, we have no issue :)
