### ISSUE TITLE
Is this plugin supported in Phonegap Desktop App?

### ISSUE THREAD

**Issue by SaifuMak** [brody2consult/cordova-sqlite-storage#550]
I am trying to build an app using Phonegap Desktop App. I have added the plugin to the project. After running the app, Server log shows that 

```
OPEN database: MyTestingDB
new transaction is waiting for open operation
```

And none of the database operations work for me. Even through I have used the correct code from the README.md file.
Before posting my codes, it would be better to know if the plugin is supported or not. 
Is this plugin supported in Phonegap Desktop App? Please help.

**Comment by brody2consult** [comment]
Unfortunately not. Under future consideration. Thanks for asking, will be documented when I get a chance.

**Comment by SaifuMak** [comment]
Thank you very much for the quick reply. So I need to use Apache Cordova to make use of this plugin I guess?

**Comment by brody2consult** [comment]
I would definitely recommend Cordova. MS Visual Studio tools should also support this plugin.

**Comment by SaifuMak** [comment]
Thanks a million! I spent my whole day in phonegap to fix the issue. I will try other 2 options anyway :)
