### ISSUE TITLE
new transaction is waiting for open operation - like Issue #540

### ISSUE THREAD

**Issue by LeandroFranciscato** [brody2consult/cordova-sqlite-storage#554]
Hello, like the issue #540, I also have this "error".
But, in my case the App doesn't crash or stop, It just became slow.

Below, my code that make transactions.

``` javascript
var dbUtil = {
    DATABASE: "",
    NOME_DATABASE: "LineMob.db",
    LOCALIZACAO_DATABASE: "default",
    initialize: function (cb) {
        if (!this.DATABASE) {
            this.DATABASE = window.sqlitePlugin.openDatabase({name: this.NOME_DATABASE, location: this.LOCALIZACAO_DATABASE},
                    function (tx) {
                        if (cb) {
                            cb(tx);
                        }
                    },
                    function (err) {
                        if (cb) {
                            cb(err);
                        }
                    });
        } else {
            if (cb) {
                cb();
            }
        }
    },
    dropDatabase: function (callback) {
        window.sqlitePlugin.deleteDatabase({name: this.NOME_DATABASE, location: this.LOCALIZACAO_DATABASE}, function () {
            if (callback) {
                callback();
            }
        });
    },
    executeSql: function (sql, parametros, cb) {
        this.initialize(function () {
            dbUtil.DATABASE.transaction(function (transaction) {
                transaction.executeSql(sql, parametros,
                        function (tx, res) {
                            if (cb) {
                                cb(res);
                            }
                        },
                        function (err) {
                            alertUtil.confirm("Error executing SQL ->" + err.valueOf());
                            if (cb) {
                                cb(err);
                            }
                        });
            });
        });
    }
};
```

Like you see, I only open the DB once and then use always the `dbUtil.DATABASE.` to make transactions.
What did I do Wrong?
Thank you for this amazing plugin.

**Comment by brody2consult** [comment]
Hi @LeandroFranciscato,

Unfortunately I really do not know where to start to reproduce your issue where you see an app become "slow".

Please keep in mind that transactions are run in sequence. A long running transaction would block operations requested afterwards.

I would need a couple things to reproduce this issue:
- Which platform(s)
- The simplest Cordova project you can make to demonstrate this issue, along with clear, unambiguous instructions how to run it. https://github.com/brodybits/Cordova-sqlite-bootstrap-test may be a good starting point. Please do **not** include the `platforms` directory. In addition, if you add all plugins with the `--save` flag then there is no need to include the `plugins` directory either.

**Comment by LeandroFranciscato** [comment]
Hi @brodybits, I think that I was not clear.
Anyway...  I will follow what you suggest, 

Thanks for your answer.
