### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by hypery2k** [brody2consult/cordova-sqlite-storage#556]
Is there a change to get macOS support for this plugin. I locally tried it by justing copying the iOS folder and works for me

**Comment by brody2consult** [comment]
> Is there a change to get macOS support for this plugin. I locally tried
> it by justing copying the iOS folder and works for me

Unfortunately I cannot promise when I will get a chance to look at this due
to my current workload. A pull request would definitely be welcome.

**Comment by brody2consult** [comment]
macOS support is now available in this repo and will be a part of the next npm release. Tests and documentation have been adjusted as well. Thanks @hypery2k for your efforts.
