### ISSUE TITLE
Support Opening DB  In location that allow sharing data between app & extensions

### ISSUE THREAD

**Issue by shibins** [brody2consult/cordova-sqlite-storage#559]
I have requirement where I need to share the data  between App & Extensions. As per  http://www.tekramer.com/sharing-data-between-apps-extensions/  I can store DB is shared location. How Do I open DB using Cordova-sqlite-storage in Shared Location ?

**Comment by brody2consult** [comment]
Thanks for the request, I will keep it for future consideration. Priority goes to paid customers. Unfortunately I cannot promise this before December 2016.

**Comment by brody2consult** [comment]
Closing now. I think #858 would be the same.
