### ISSUE TITLE
Cordova SQLite Storage issue

### ISSUE THREAD

**Issue by sumit13423** [brody2consult/cordova-sqlite-storage#566]
I'm using cordova SQLite plugin in my cordova mobile app project .

Android 5.0 , cordova 6.3.1 cordova-sqlite-storage 1.4.7

DB is getting opened properly but after execution of any transaction like select ,update delete etc I'm getting below error
!JavaScript ERROR: Plugin SQLitePlugin.open is not supported
Please suggest and help .
Thanks in advance

**Comment by brody2consult** [comment]
I suspect you are using an unsupported platform. This version supports Android, iOS, and Windows. This version does _not_ support WP8. Also browser platform is currently _not_ supported, for future consideration.

**Comment by sumit13423** [comment]
Please specify the supported version of android and cordova to get rid of this issue.

I have specified above I am using Android 5.0 version on my emulator. 
Cordova 6.3.1 and cordova-sqlite-storage 1.4.7 which I guess is the latest one. 

I am not using windows phone platform or SDK . I am using android SDK.

Kindly let me know, what could be the possible option towards resolution.

Regards,
Sumit

**Comment by brody2consult** [comment]
These items already documented, though maybe not clearly enough. I will document these items more clearly when I get a chance.

A further enhancement would be to hack config.xml so that SQLitePlugin.js is _only_ installed in case of the supported platforms.

**Comment by brody2consult** [comment]
My apologies I think I misunderstood your issue. If you get this error on Android, iOS, or Windows please try using `cordova prepare`. (For some reason the iOS version does not seem to work on my Xcode 8.0 installation unless I do `cordova prepare`.) I will document this when I get a chance.
