### ISSUE TITLE
iOS support very confused !!

### ISSUE THREAD

**Issue by MehdiGuelloub** [brody2consult/cordova-sqlite-storage#572]
Hello,

The following code works perfectly on android but not on iOS.

```
window.plugins.sqlDB.copy("mydba.db", 0, function() {
            $rootScope.base = $cordovaSQLite.openDB({name: "mydba.db", location: 'default'}); //device
            alert('Copied');
        }, function(error) {
            alert(error.message);
            $rootScope.base = $cordovaSQLite.openDB({name: "mydba.db", location: 'default'}); //device
        });
```

I have looked everywhere and found hundreds of propositions to solve this problem, none of them have worked for me!!

Why don't this plugin provide a clear documentation or use case?

Please what is the right way to create a database SQLite working on iOS?

**Comment by brody2consult** [comment]
Please raise this question on the cordova-plugin-dbcopy project.

The recommended solution is to use cordova-sqlite-ext which supports pre-populated databases out of the box.
