### ISSUE TITLE
How to backup data  or import data from PC

### ISSUE THREAD

**Issue by shizhidi** [brody2consult/cordova-sqlite-storage#574]
Are there any solutions

**Comment by brody2consult** [comment]
You can treat the sqlite database like a file, with the following caveats:
- do not copy or overwrite the file while a transaction is in progress
- The Android version stores the database in a standard `databases` directory which is hidden and locked from outside the mobile app. https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free has a feature to store the Android database in an arbitrary location (GPL or commercial licensing terms). It is under future consideration to port this feature to cordova-sqlite-ext (permissive licensing terms).
