### ISSUE TITLE
How to change the default database to store location?

### ISSUE THREAD

**Issue by shizhidi** [brody2consult/cordova-sqlite-storage#577]
1、not 'data/data/xxxx.com.xx/databases/xxxx.db' directory。

2、Changed the default location, the app can also call to?

**Comment by brody2consult** [comment]
From your question I think you want to store the database in a different location on Android. This is available in: https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free (GPL or commercial licensing terms)

I may port this to cordova-sqlite-ext with permissive license terms at some point.
