### ISSUE TITLE
Valid iOS database location could not be determined in openDatabase call

### ISSUE THREAD

**Issue by filipefreitas82** [brody2consult/cordova-sqlite-storage#578]
I'm getting this error on ios10 after updating cordova and, also, the plugin.

`window.sqlitePlugin.openDatabase({name: dbName, location: 'Library'})`

Currently using:
- cordova 6.4.0
- cordova iOS 4.3.0
- cordoba-sqlite-storage 1.4.8

Any feedback? Thanks.

**Comment by brody2consult** [comment]
As documented:

``` js
var db = window.sqlitePlugin.openDatabase({name: 'my.db', iosDatabaseLocation: 'Library'}, successcb, errorcb);
```

Was it not clear enough?

**Comment by filipefreitas82** [comment]
My bad. Subversion mistake.
Thanks brodybits.
