### ISSUE TITLE
Drop support for Windows 8.1/Windows Phone 8.1 from this version?

### ISSUE THREAD

**Issue by brody2consult** [brody2consult/cordova-sqlite-storage#579]
I would like to drop support for Windows 8.1 and Windows Phone 8.1 from this version for the following reasons:
- faster testing of bug fixes and releases
- ability to move the Windows SQLite3 library calls into a web worker: this should work consistently on Windows 10, not sure about Windows 8.1 or Windows Phone 8.1

Windows 8.1 and Windows Phone 8.1 would still be supported by the Cordova-sqlite-legacy-build-support version.

Feedback is also requested from @nikhilkh and @sgrebnov in case this would affect Visual Studio TACO.

**Comment by vladimir-kotikov** [comment]
@brodybits, VS TAC in VS 15 Preview does not (and probably will not) support building for Windows 8.1, so there is no objections from our side

**Comment by brody2consult** [comment]
Thanks @vladimir-kotikov

**Comment by brody2consult** [comment]
Windows 8.1/Windows Phone 8.1 is now dropped from version 1.5.0. New version for Visual Studio 2017 RC (nee VS 15 preview) for #580 coming next.
