### ISSUE TITLE
installing the plugin in OS X but not getting entry in config.xml

### ISSUE THREAD

**Issue by yashktrivedi** [brody2consult/cordova-sqlite-storage#590]
Hi @brodybits ,

I have installed cordova-sqlite-storage plugin using cordova in Mac OS X system but not getting entry of it in config.xml
so does this plugin support Mac OS X ?

**Comment by brody2consult** [comment]
As I already documented you have to use the `--save` flag to tell the `cordova plugin add` command to add the plugin to `config.xml`.

I wish this were documented in <https://cordova.apache.org/docs/en/latest/guide/cli/#add-plugins> and already raised this in https://github.com/cordova/cordova-discuss/issues/56.
