### ISSUE TITLE
Windows 10 OuputPath property is not set for project 'SQLite3.UWP.vcxproj'

### ISSUE THREAD

**Issue by txavier** [brody2consult/cordova-sqlite-storage#592]
Im using, Windows 10, Ionic 2 CLI, Cordova CLI, Visual Studio 2015.  The below steps worked fine when building for Android.  When building for Windows 10 though this problem occured.

In my quick search it looks like the closest to this that I have found is this issue, which seems to describe exactly what I am seeing except for the fact that I am using Visual Studio 2015 instead of Visual Studio 2017 (https://github.com/litehelpers/Cordova-sqlite-storage/issues/580).  If I cannot find this issue I will create one.

To reproduce:

npm install -g ionic cordova
ionic start cutePuppyPics --v2
cd cutePuppyPics
ionic platform add windows
[add < preference name="windows-target-version" value="10.0" /> to the config.xml]
cordova plugin add cordova-sqlite-storage --save
[Modify ngModule and a component page as per http://ionicframework.com/docs/v2/storage/]
ionic run windows [or if you want to specify a processor i.e.: ionic run windows --archs="x64"]
[Also, if switching to Visual Studio 2015 at this point the build will fail with a message "tsc.exe" exited with code 1.]

Then the following error appears:

C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(724,5): error : The OutputPath property
is not set for project 'SQLite3.UWP.vcxproj'.  Please check to make sure that you have specified a valid combination of
Configuration and Platform for this project.  Configuration='debug'  Platform='x64'.  You may be seeing this message bec
ause you are trying to build a project without a solution file, and have specified a non-default Configuration or Platfo
rm that doesn't exist for this project. [R:\dev\HarborWaterQuality\HarborWaterQuality.Ionic\plugins\cordova-sqlite-stora
ge\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]

Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe: Command failed with exit code 1

**Comment by txavier** [comment]
My package.json

{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.45",
    "typescript": "2.0.6"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-statusbar",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "description": "HWQ.Ionic: An Ionic project"
}

**Comment by brody2consult** [comment]
Hi @txavier,

Thanks for raising this issue. Unfortunately I have never dealt with using Ionic together with Visual Studio before. I hope to get to this sometime next week.

In general I give higher priority to paid support work. If you are interested in higher priority support please contact me at <brodybits@litehelpers.net> or <sales@litehelpers.net>.

Please feel free to ask again after 1-2 weeks. I hope we can find a solution for the benefit of the user community in general.

**Comment by txavier** [comment]
Thanks.  I think I figured it out though.  Stay tuned for the pull request.

**Comment by txavier** [comment]
For somereason my configuration set the <PlatformToolset> value in the SQLITE3.UWP.vcxproj to v141.  It should be v140 as you have it in your source control.  I cant figure out how it changed to v141 but for anyone else that is having this issue (@Perroquiet), the way to solve this is changing the line 

`<PlatformToolset>v141</PlatformToolset>`

to

`<PlatformToolset>v140</PlatformToolset>`

**Comment by brody2consult** [comment]
According to @andreujuanc this was not really solved. Discussion is now continued in #599. This one is now marked as a duplicate.
