### ISSUE TITLE
Getting message: Native: tried accessing the SQLite plugin but it's not installed. ionic ios emulator 10

### ISSUE THREAD

**Issue by vangelisv** [brody2consult/cordova-sqlite-storage#594]
It works fine in android both emulator and device. 
Plugin is installed for both platforms

**Comment by brody2consult** [comment]
I suspect there is something wrong with your installation. I suggest you try cordova-plugin-dialogs and maybe cordova-plugin-file first. I am busy with an urgent assignment and can take a look after 1-2 weeks. Marked **community-help-welcome**.

For priority support please contact <brodybits@litehelpers.net> or <sales@litehelpers.net>.

**Comment by aces-tm** [comment]
Did you ever find solution for this?

**Comment by vangelisv** [comment]
Yes, indeed I tried cleaning and re-installing all plugins and it worked.
Thanks,

**Comment by aces-tm** [comment]
for me it happens only when I run it with ionic run android --prod and it works fine with ionic run android but it takes 15-18 seconds to load. Did you have the same problem?

**Comment by rodineijf** [comment]
@acessoftware Same problem here

**Comment by brody2consult** [comment]
To get help from the community I suggest you guys post a minimal reproduction sample.

**Comment by rodineijf** [comment]
Hi @brodybits, by default the attribution of rootPage on ionic 2 is on declaration of var rootPage. I can solve my problem moving the rootPage attribution to the platformReady on app.component

  initializeApp() {
    this.platform.ready().then(() => {

      this.rootPage = MyPage;
      StatusBar.styleDefault();
      Splashscreen.hide();
    });
  }

**Comment by rodineijf** [comment]
Hi @brodybits, by default the attribution of rootPage on ionic 2 is on declaration of var rootPage. I can solve my problem moving the rootPage attribution to the platformReady on app.component

```
initializeApp() {
this.platform.ready().then(() => {

  this.rootPage = MyPage;
  StatusBar.styleDefault();
  Splashscreen.hide();
});
}
```

**Comment by brody2consult** [comment]
Thanks @rodineijf. I just raised #613 to document this and related items.

**Comment by BasantPandey** [comment]
Hi All, 

i am facing the same issue. can you please help me to fix this issue. I have cross check at my end. I installed all the mentioned plugins. But not sure why it is showing this type of message. 

<img width="689" alt="2017-01-19_8-56-26" src="https://cloud.githubusercontent.com/assets/896016/22115915/c33bbeb4-de94-11e6-89fe-8b0d786c5077.png">

**Comment by rodineijf** [comment]
@BasantPandey You're running on your browser or on the phone?

**Comment by BasantPandey** [comment]
@rodineijf  I am using chrome browser emulator. As per my knowledge the old version was working well on  chrome browser emulator.

**Comment by brody2consult** [comment]
This plugin does not support the Browser platform. I hope to add it in the near future.

**Comment by pbreuss** [comment]
The most common reason for this error is calling the plugin too early before the app has been fully loaded. Use the platform.ready() command to make sure everything is loaded ...

this.platform.ready().then(() => {

  // add your code here

});

**Comment by Alejo22** [comment]
@pbreuss you have reason, the plugin is ready for use once the current platform is ready. In a browser the plugin storage doesn't work because it needs an operating system to access.

   platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      this.initilizeApp();
    });

**Comment by fpassa** [comment]
I was able to use not only to interact to SQLite but also able to manage it under browser by falling into WebSQL. In addition, extended as well to MySQL. 
Check it out here: https://sellfy.com/p/gUWH/

**Comment by thyagobudal** [comment]
Even inside platform.ready() I'm facing the same erro.. "plugin_not_installeed"... running on my android device.

**Comment by ravatsinh** [comment]
same issue anyone found solution please help

**Comment by nationdata-it** [comment]
any solution to this?
