### ISSUE TITLE
txlock: true error on sqllite query success

### ISSUE THREAD

**Issue by sagarhiremath6** [brody2consult/cordova-sqlite-storage#595]
When I execute sqlite insert query, I get success function callback and result is something link this:

**{ "db": {"openargs":{"name":"test","location":"default", "dblocation":"nosync"},"dbname":"test"},
"txlock":"true","readOnly":"false","executes":[]}**

**Comment by sagarhiremath6** [comment]
Please help with this, it wont happen for other queries like create table...

**Comment by MikeDimmickMnetics** [comment]
Which version of the plugin are you using? Which platform is it running on (Android, iOS, Windows) and what version? If on Android, are you using the `androidDatabaseImplementation: 2` setting to use the built-in Android SQLite API rather than the bundled version of SQLite?

**Comment by brody2consult** [comment]
@sagarhiremath6 it looks like a problem with your code. Please show your INSERT query code to get help thanks!

**Comment by sagarhiremath6** [comment]
@brodybits 
`db.transaction(function(tx)
{  
   var insert_sql = "INSERT INTO story( data, status, did, images, userid, imageStatus, videos ) VALUES( ?, ?, ?, ?, ?, ?, ? )";
   
   tx.executeSql( insert_sql, ['fgdfgfd', 'fgfgg', '443', 'nbn', '121', 'nbvnv', 'nvbnv'],
      function (resultSet)
      {      
         alert(JSON.stringify(resultSet));
      },
      function(error)
      {

         console.log('Insert error: ' + error.message);
     }
  );
});`

**Comment by MikeDimmickMnetics** [comment]
The first parameter for the callback functions is the transaction object `tx`. The _second_ parameter is the `resultSet` for the success callback, and the `error` for the error callback. Your code is dumping the transaction object, not the results of running the query.

**Comment by sagarhiremath6** [comment]
@MikeDimmickMnetics : Thanks for noticing. Now I not getting that message
{ "db": {"openargs":{"name":"test","location":"default", "dblocation":"nosync"},"dbname":"test"},
"txlock":"true","readOnly":"false","executes":[]}

But insert is not happening.

**Comment by brody2consult** [comment]
@sagarhiremath6 please post a reproduction program.

**Comment by sagarhiremath6** [comment]
// In separate function  
    var db = window.sqlitePlugin.openDatabase({name: 'test', location: 'default'});

     // In separate function  
     db.transaction(
      function(tx)
      {  
        var create_story_sql =
        'CREATE TABLE IF NOT EXISTS story(id INTEGER PRIMARY KEY AUTOINCREMENT, data TEXT NOT NULL, status TEXT NOT NULL, node INTEGER DEFAULT 0, userid INTEGER NOT NULL, imageStatus TEXT NULL, images TEXT NULL, videos TEXT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP)';
        tx.executeSql( create_story_sql,[], function (tx, results) { 
             console.log('story table created');
        });
        
      },
      function(err)
      {
         console.log('Open database ERROR: ' + JSON.stringify(err));
      });


     // In separate function  
    db.transaction(function(tx)
      {  
         var insert_sql = "INSERT INTO story( data, status, images, userid ) VALUES( ?, ?, ?, ?)";
         tx.executeSql( insert_sql, ['hfghg', 'ready', 'commaSeparatedImages', 3232],
            function (tx, resultSet)
            {      
               alert(JSON.stringify(resultSet));

            },
            function(error)
            {
               console.log('Insert error: ' + error.message);
           }
        );
      });

**Comment by sagarhiremath6** [comment]
Success callback of Insert query is getting called not error callback.

Success message : **{ "rows" :{"length" :0}, rowsAffected":1, "insertId":1 }**

**Comment by sagarhiremath6** [comment]
I am using this sqlite plugin in **angurjs+phonegap+bootstrap** project. It should work without any issues right? OR Should I use it differently in angularjs. Create database and table are working though.

**Comment by sagarhiremath6** [comment]
new transaction is waiting for open operation", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (106)

Seeing above line 3 times in console.

**Comment by brody2consult** [comment]
Use of this plugin with Ionic and other forms of Ionic has proven to be very tricky. I already documented some pitfalls that you have to watch for. This may be the same as #593. I leave this to the community for now.

In case of continued problems I suggest you post a complete test project that can demonstrate your issue for community support.

For commercial support you may contact <sales@litehelpers.net>.
