### ISSUE TITLE
getting this error "Error: Cannot find plugin.xml for plugin "cordova-sqlite-storage". Please try adding it again."

### ISSUE THREAD

**Issue by dawoodahmad** [brody2consult/cordova-sqlite-storage#597]
I am getting this error 

> Error: Cannot find plugin.xml for plugin "cordova-sqlite-storage. Please try adding it again.

 when i  execute command `cordova plugin add cordova-sqlite-storage`

**Comment by brody2consult** [comment]
Hi @dawoodahmad,

It sounds like an issue with your project or Cordova installation. Please do a fresh new install of Cordova, create a new project, and try it again.

**Comment by groukx** [comment]
Hi,

I just delete the cordova-sqlite-storage folder from the root folder plugins and `cordova plugin add cordova-sqlite-storage` command work.
