### ISSUE TITLE
Windows 10 OuputPath property is not set for project 'SQLite3.UWP.vcxproj'

### ISSUE THREAD

**Issue by andreujuanc** [brody2consult/cordova-sqlite-storage#599]
This should not be closed, as it mean that it's fixed, and it's not:
https://github.com/litehelpers/Cordova-sqlite-storage/issues/592

Manually changing the project file from:
`<PlatformToolset>v141</PlatformToolset>`
to
`<PlatformToolset>v140</PlatformToolset>`

Does fix the problem.

Because that issue was closed, i spend some time thinking it was something on my side debugging the project, and in reality (or at least i think that) the issue is not yet fixed.

**Comment by brody2consult** [comment]
Thanks @andreujuanc for reporting this. From #580 I got agreement with @vladimir-kotikov that we should use an `engines` specification in `package.json` that automatically uses an `edge` branch (cordova-sqlite-storage 2.0.x) in case you use a newer version of Cordova. This is a trick that solves the problem for people who use the Visual Studio GUI.

Unfortunately this trick causes a problem for people who use a newer version of Cordova with the CLI and Visual Studio 2015.

I think the right thing is to tell people to use the following to install the correct version for Visual Studio 2015:
```sh
cordova plugin add cordova-sqlite-storage@latest --save
```

I will document this as soon as I get a chance.

**Comment by andreujuanc** [comment]
@brodybits  Thanks!! Will do.

**Comment by samized** [comment]
I am using the latest `cordova-sqlite-storage` plugin (2.0.2) but the generated `SQLite3.UWP.vcxproj` File still has `<PlatformToolset>v141</PlatformToolset>` on every platform configuration. So my build fails without manually changings.

I use Ionic and VS Code.

**Comment by brody2consult** [comment]
@samized I don't think you quite followed the instructions I gave above.

**Comment by samized** [comment]
Ok, you mean I should use version 1.5.2 which is fine... I think I run into #632 :/

**Comment by brody2consult** [comment]
Further discussion will be in #615. Support for Visual Studio 2015 will be dropped soon (will still be supported by Cordova-sqlite-legacy-build-support).

**Comment by andreujuanc** [comment]
Downloading VS2017 in 3..2..1.. 👍 
Jokes aside. @brodybits If i cant upgrade right now to VS17, should I move to legacy? Whats the recommendation here? I´m in the middle of project deployment, and cant risk to change tools now.

Cheers

**Comment by brody2consult** [comment]
> If i cant upgrade right now to VS17, should I move to legacy?

Yes, I would recommend it. I will continue to support the legacy version in case of major bug fixes.
