### ISSUE TITLE
Installing Cordova SQLite plugin causes compile error on Ionic 2 

### ISSUE THREAD

**Issue by mobilesoftsmith** [brody2consult/cordova-sqlite-storage#603]
I am using ionic 2.1.12.

I installed native SQLite plugin into my project:
ionic plugin add cordova-sqlite-storage

I built the project for android platform:
ionic build android

I got this error message:
Execution failed for task ':transformNative_libsWithStripDebugSymbolForDebug'.

java.lang.NullPointerException (no error message)

**Comment by brody2consult** [comment]
Please try this without Ionic or other form of Angular. If this is still a problem please post some more info about which Android API version you are using, JDK version, host platform, etc. I have never seen this issue myself.
