### ISSUE TITLE
Native: tried accessing the SQLite plugin but it’s not installed

### ISSUE THREAD

**Issue by clems36** [brody2consult/cordova-sqlite-storage#604]
I am trying to use the `SQLite `plugin in the browser view of my Ionic 2 App, but I keep getting that warning message eventhough the plugin is installed (refer to the title).
Is it impossible to use `SQlite `with `ionic serve` ?

**Comment by brody2consult** [comment]
This plugin does not support the browser platform.

**Comment by clems36** [comment]
Thanks

**Comment by azyth** [comment]
Are there plans to support the browser in the future?

**Comment by brody2consult** [comment]
@azyth I already started it in PR #576. I will need a couple months or so due to some other work items.
