### ISSUE TITLE
Galaxy S6 takes extremely long for a SELECT

### ISSUE THREAD

**Issue by markarupert** [brody2consult/cordova-sqlite-storage#606]
I have a Galaxy S6 that is frequently taking a very long time for a simple SELECT statement. The statement below can take as long as 161 seconds to come back. Other times it will take less than 100 milliseconds. At the very bottom is the table structure.

Any idea why it would take so long?

//=====================================================
   var startCheckElogLock = new Date().getTime();
   var deferred = $q.defer();

   var sql = "SELECT * FROM elog WHERE starttime >=" + logDate + " AND starttime < " + (logDate + DAY_UNIX) + " AND status = 4 ORDER BY starttime";
   appDB.exeDBSQL(sql)
       .then(function (r) {
           deviceLog("checkElogLock: Run Time Get the time for lock: " + (new Date().getTime() - startCheckElogLock), function (str) {console.log(str)});
               deferred.resolve();
           }
       });
//=====================================================

                
//=====================================================
// SQL EXECUTER
//=====================================================
   app.service('appDB', function($q, $rootScope) {
     function exeDBSQL(sql, param) {
          var deferred = $q.defer();
          db.executeSql(sql, [], function (results) {
              sqlResult = new Object();
              sqlResult.return = true;
              sqlResult.tx = 0;
              sqlResult.param = param;
              sqlResult.sql = sql;
              sqlResult.results = results;
              $rootScope.unableToRecordData = false;
              deferred.resolve(sqlResult);
          }, function (err) {
              sqlResult = new Object();
              sqlResult.sql = sql;
              sqlResult.return = false;
              sqlResult.tx = -1;
              sqlResult.err = err;
              $rootScope.unableToRecordData = true;
              deviceLog("appDB.exeDBSQL Failed, err=" + err.message, function (str) {console.log(str)});
              deferred.resolve(sqlResult);
          });
         return deferred.promise;
     }

     return {
         exeDBSQL: exeDBSQL
     };
   });

//======================================================
                    tx.executeSql("CREATE TABLE IF NOT EXISTS elog (status, starttime, endtime)");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN lat TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN lon TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN uploaded TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN city TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN state TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN inspectiontime TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN defects TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN violation TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN reason TEXT NOT NULL DEFAULT ''");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN odometer TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN assetid TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN inspectionassetid TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN resolvedby TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN resolution TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN parts TEXT");
                    appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN eventstatus TEXT");
                    tx.executeSql("CREATE INDEX IF NOT EXISTS timeStatusElogIdx ON elog (starttime, endtime, status)");
//=============================================================

**Comment by brody2consult** [comment]
I can think of a couple possible causes:
- Java-side garbage collection cycles
- Delays due to sqlite disk I/O

There are no plans for performance improvements to this version. Performance enhancements are available in Cordova-sqlite-evcore-extbuild-free (GPL or commercial license options). You could also try sqlite plugin 2 by Nolan Lawson.

**Comment by markarupert** [comment]
Do I need a license key for Cordova-sqlite-evcore-extbuild-free? It does not seem to work beyond the open.

**Comment by brody2consult** [comment]
No it does not need a license key. Either there is something wrong with the way you use it or there is a compatibility issue.

I suggest that you try both the echoTest and selfTest on your Galaxy S6 and report the results.

**Comment by markarupert** [comment]
Got it working. I have a question but will post in the other plugin page since it is not related to this one.
