### ISSUE TITLE
Syntax for inserting multiple values in a column  dynamically? 

### ISSUE THREAD

**Issue by Priya-Ahuja** [brody2consult/cordova-sqlite-storage#614]
I am writing this piece of code for inserting values into dB dynamically , it works fine for a single record in  column, How shall I modify it for multiple records?
  
function importJsonTodb(json) {

        console.log("json received", json);
        var cols = [],values = [];            
        for (var key in json) {
            var records = json[key],
                query;
            if (records.length > 0) {
                for (let i = 0; i < records.length; i++) {
                    cols = Object.keys(records[i]);
                    records.map((record) => {
                           cols.forEach(colName => {
                            values.push(record[colName]);
                        });
                       });
                    console.log(values);
                    query = `INSERT INTO ${key} (${cols.join(',')}) VALUES (${cols.map(() => '?')})`;
                    console.log('Query: ', query);
                   return $cordovaSQLite.execute(db,query,values);
                }

            }
        }
json structure 
var json = {"firsttablename":[{"col1": "val1"},{"col1":"val2"}]}

**Comment by brody2consult** [comment]
I suspect the '?' characters are not separated by ','. Please be sure to have the '?' characters separated by ','.
