### ISSUE TITLE
master branch vs edge question

### ISSUE THREAD

**Issue by maoamid** [brody2consult/cordova-sqlite-storage#615]
cordova plugin add cordova-sqlite-storage pull the edge branch, ~v2.x.x, as default while the master is v1.5.2 when I write this comment. 
What are the difference between them? 9 day ago I saw the master branch code was merged into edge one (logical I supposed it should be testing code merged in master when proved stable ). 
Thank you for your work, appreciate.

**Comment by brody2consult** [comment]
From #580: edge branch has changes needed to support VS 2017. I plan to make this the default pretty soon.

**Comment by brody2consult** [comment]
To answer a couple questions by @mirko77:

From https://github.com/litehelpers/Cordova-sqlite-storage/issues/632#issuecomment-288734133:
> @brodybits this does not affect Android (4.4+) and iOS (8+), right? I have a build with 2.0.2 from 1.4.5 which I will have to revoke if it is going to break

This should absolutely not affect functionality on the Android or iOS platforms.

From #654:
> When installing the latest version I get:
> `cordova-sqlite-storage 2.0.2 "Cordova sqlite storage plugin"`
> 
> Reading through Changes.MD, I do not see anything past 1.5.3
> 
> Am I missing something?

That is correct. As discussed in #580 this is specified by the `engines` entry in `package.json` and was done to support both Visual Studio 2015 and Visual Studio 2017 RC.

> Are there any breaking changes I need to take care of?

Not for Android or iOS.

> I have seen other issues about this. I have an existing app on Android (4.4+) and iOS (8+), am I good to go?

Yes.

> according to #615, differences are only on the Windows platform?

Yes.

Now that Visual Studio 2017 is released I will drop the engines rule and just support Visual Studio 2017. Visual Studio 2015 will be supported by the Cordova-sqlite-legacy-build-support version.

**Comment by mirko77** [comment]
Thanks @brodybits for your help. Good stuff as always!

**Comment by brody2consult** [comment]
Support for Visual Studio 2017 is now part of the default `storage-master` branch. VS 2015 is now supported in [litehelpers / Cordova-sqlite-legacy-build-support](https://github.com/litehelpers/Cordova-sqlite-legacy-build-support), dropped from this project.
