### ISSUE TITLE
"Too many sql statements" error while inserting multiple records using single query?

### ISSUE THREAD

**Issue by Priya-Ahuja** [brody2consult/cordova-sqlite-storage#616]
Receving a json as ["tableName" :"mytable", "columns" :["col1","col2"], "tableData" :[["1","@"],["2","3"]]; 

I am inserting multiple records using following code.However, for one table the total no. of parameters are more than 1000 and i am getting too many SQL variables error. I searched there is a way we can split the query. How can i split the query in the following code?

var table_name, row_args_str;
        json.map(function (record) {
            var values = [], cols = [], row_args = [];
            table_name = record.tableName;
            record.columns.map(function (column) { cols.push(column); });
            record.tableData.map(function (value) {
                values = values.concat(value);
                row_args.push(cols.map(function () { return '?' }));
                row_args_str = (row_args.map(function(arg){  return '(' + arg.join(', ') + ')'} )).join(", ");
            });
            var query = "INSERT INTO " + table_name + ' (' + cols.join(', ') + ') VALUES ' + row_args_str;         
            $cordovaSQLite.execute(db, query, values).then(function (res) {
                        }, function (err) {
                console.log("Unable to insert data",err,query,values,cols);
            });

**Comment by brody2consult** [comment]
You could split the information from tableData such as described in <http://stackoverflow.com/questions/8495687/split-array-into-chunks>.

It is best if you can INSERT all records within a single transaction but ngCordova does not seem to support this. You should be able to just call db.transaction directly as documented.

**Comment by Priya-Ahuja** [comment]
Thanks @brodybits , I have discovered the same way and looping into subarrays to make an insert query call..Following is the code:
if (values.length > 999) {
                var no_of_cols = cols.length;
                var max_no_recors_at_a_time = parseInt(999 / no_of_cols); //Max no of records inserted at a time
                console.log("max_no_recors_at_a_time", max_no_recors_at_a_time);


                /** Need to divide the  values in max_no_recors_at_a_time records */

                var new_modified_values = [], size = max_no_recors_at_a_time, new_modified_params = [];
                while (record.tableData.length > 0) {
                    var subarr = [];
                    var subparam;
                    //Splitting the ? first
                    subparam = (row_args.splice(0, size).map(function (arg) { return '(' + arg.join(', ') + ')' })).join(", ");
                    record.tableData.splice(0, size).map(function (arrval) { subarr = subarr.concat(arrval) });
                    new_modified_values.push(subarr);
                    new_modified_params.push(subparam);
                }
                console.log(new_modified_values);
                console.log(new_modified_params);

                /***Once you get the values divided into pairs we can go ahead and loop into query respective
                 * no. of times
                 */
                for (let i = 0; i < new_modified_values.length; i++) {


                    var query = "INSERT INTO " + table_name + ' (' + cols.join(', ') + ') VALUES ' + new_modified_params[i];
                    console.log("query when value exceeds 1000", query);
                    $cordovaSQLite.execute(db, query, new_modified_values[i]).then(function (res) {
                        $ionicLoading.hide();
                        console.log("Data Inserted Successfully", res);
                    }, function (err) {
                        console.log("Unable to insert data when data exceeds 1000", err);
                    });

                }




            }
Its working fine now :)

**Comment by ujjvaljoshi4** [comment]
@brodybits Is there a way we can combine multiple insert query and then execute it in a single execution?
Executing query in For loop takes much time.
