### ISSUE TITLE
How to query two tables and put the result of one of then in the object key

### ISSUE THREAD

**Issue by marcusvbp** [brody2consult/cordova-sqlite-storage#625]
Hi!

I am querying two tables:

`SELECT tab1.id, tab1.col2, tab2.id as tab2_id, tab2.col2 as tab2_col2 FROM tab1, tab2 WHERE tab1.id = tab2.id`

And I get an object like this:

```
{
  id: 1,
  col2: "nonono",
  tab2_id: 3,
  tab2_col2: "lalala"
}
```

but I want create an object like this:

```
{
  id:1,
  col2: "nonono",
  tab2: {
    id: 3,
    col2: "lalala"
  }
}
```
It's possible?

Thanks!

**Comment by brody2consult** [comment]
That will not be supported.

**Comment by nuclearsagar** [comment]
@brodybits , Can you suggest any other alternate approach to achieve this?
It will be very helpful.

My Current code is as follows : 
`db.transaction(function(tx) {`
                `tx.executeSql("SELECT * FROM exam e", [], function(tx, examRows) {`
                   `var exams = [];`
                    `for(var x = 0; x < examRows.rows.length; x++) {`
                        `(function() {`
                        `var exam = {};`
                        `var subjects = [];`
                        `tx.executeSql("SELECT s.* FROM subject s, examSubject ex WHERE  s.id=ex.subjectId and ex.examId=?", [examRows.rows.item(x).id], function(tx, examSubjectRows) {`
                             `for(var y = 0; y < examSubjectRows.rows.length; y++) {`
                                `subjects.push(examSubjectRows.rows.item(y));`
                             `}`
                            `},function(tx,error) {`
                                `console.log("Error in examSubject function , and due to "+error.message);`
                            `});`
                            `exam.name = examRows.rows.item(x).title;`
                            `exam.startTime = examRows.rows.item(x).startTime; `
                            `exam.endTime = examRows.rows.item(x).endTime;`
                            `exam.subjects = subjects;`
                            `exams.push(exam);`
                    `})();`
                             `console.log("exam after tx : " + examRows.rows.item(x));`                    
                    `}`
		`deferred.resolve({`
                        `rows : exams`
                    `});`
                `},function(tx,error) {`
                    `console.log("Error in function , and due to "+error.message);`
                `});`
            `});`
            `return deferred.promise;`
        `}`

But I am getting subjects empty.


Thanks in advance.

**Comment by marcusvbp** [comment]
@nuclearsagar I have achieved this. Look at the code:

```
getFromPet(pet_id) {
    return new Promise((resolve, reject) => {
      this.db.tx.executeSql(`
        SELECT
          treatments.*,
          pets.birthdate AS pet_birthdate,
          pets.image AS pet_image,
          pets.name AS pet_name,
          pets.race AS pet_race,
          pets.species AS pet_species,
          recipes.simpledesc AS recipe_simpledesc,
          recipes.fulldesc AS recipe_fulldesc,
          recipes.image AS recipe_image,
          recipes.createdAt AS recipe_createdAt,
          remedies.name AS remedy_name,
          remedies.image AS remedy_image,
          remedies.createdAt AS remedy_createdAt
        FROM
          treatments
        LEFT JOIN
          pets
        ON
          treatments.pet = pets.id
        LEFT JOIN
          recipes
        ON
          treatments.recipe = recipes.id
        LEFT JOIN
          remedies
        ON
          treatments.remedy = remedies.id
        WHERE
          treatments.pet=?
        `, [pet_id]).then(
        success => {
          if (success.rows.item(0)) {
            let treatments = [];
            for(let i = 0; i < success.rows.length; i++) {
              treatments.push({
                id: success.rows.item(i).id,
                duration: success.rows.item(i).duration,
                interval: success.rows.item(i).interval,
                quantity: success.rows.item(i).quantity,
                recipe: {
                  id: success.rows.item(i).recipe,
                  simpledesc: success.rows.item(i).recipe_simpledesc,
                  fulldesc: success.rows.item(i).recipe_fulldesc,
                  image: success.rows.item(i).recipe_image,
                  createdAt: success.rows.item(i).createdAt,
                  pet: {
                    id: success.rows.item(i).pet,
                    birthdate: success.rows.item(i).pet_birthdate,
                    image: success.rows.item(i).pet_image,
                    name: success.rows.item(i).pet_name,
                    race: success.rows.item(i).pet_race,
                    species: success.rows.item(i).pet_species
                  }
                },
                unity: success.rows.item(i).unity,
                remedy: {
                  id: success.rows.item(i).remedy,
                  name: success.rows.item(i).remedy_name,
                  image: success.rows.item(i).remedy_image,
                  createdAt: success.rows.item(i).remedy_createdAt
                },
                notifications: success.rows.item(i).notifications,
                pet: {
                  id: success.rows.item(i).pet,
                  birthdate: success.rows.item(i).pet_birthdate,
                  image: success.rows.item(i).pet_image,
                  name: success.rows.item(i).pet_name,
                  race: success.rows.item(i).pet_race,
                  species: success.rows.item(i).pet_species
                },
                createdAt: success.rows.item(i).createdAt
              });
            }
            console.log("retornando os tratamentos do pet id: " + pet_id, treatments);
            resolve(treatments);
          } else {
            resolve("");
          }
        },
        err => {
          console.log('Não foi possível ler os dados ', err);
        });
    })
  }
```

**Comment by nuclearsagar** [comment]
@marcusvbp This is working for some cases.
But in my case the relation between two tables is many to many.
Exam is related to Subject with many to many relation. So comes third table ExamSubject which contains ids of both the tables.

 I am trying to create a JSON Object which will look similar to this :
```
[
   {
      id : 1,
      name : "E1",
      date : "2017-14-02"
      subjects : [
                        {
                                id : 1,
                                name : "S1"
                        },
                       {
                                id : 2,
                                name : "S2"
                        }
       ]
   } ,
{
      id : 2,
      name : "E2",
      date : "2017-14-02"
      subjects : [
                        {
                                id : 1,
                                name : "S1"
                        },
                       {
                                id : 3,
                                name : "S3"
                        }
       ]
   }
]
```

Now, when done in your way, by taking join of all 3 tables, I get Multiple rows for same exam.

Some guidelines for this will be much helpful.


Thanks in Advance.
Sagar.


Small Update : I am using ionic 1
