### ISSUE TITLE
How to return column names with camel case?

### ISSUE THREAD

**Issue by tuanbs** [brody2consult/cordova-sqlite-storage#629]
Hi there, thanks for this awesome plugin. I'm facing a problem that my sqlite DB has Pascal Case applied both for the name of tables and columns. So when I read data it returns Pascal Case for column names. At this moment, my temporary solution is to use the lodash to convert the column names (keys) into Camel Case:
_.mapKeys(item, function (v, k) {return _.camelCase(k);})
But it seems this is not an elegant way to solve this issue. Is there any way to config this plugin to return data with Camel Case for column names from SQLite? Thanks in advance.

**Comment by brody2consult** [comment]
It is not possible to configure this plugin to do such conversion for you and I would not recommend adding such an enhancement to this plugin. Such an enhancement would only add to the existing complexity of this plugin. I think your "workaround" solution is the best way to solve your problem. If it is too ugly you may want to put it into a special function or better yet refactor your code to cleanly encapsulate the database access part.

**Comment by tuanbs** [comment]
I just figured out a better solution by using "As" in SQL query: "Select Name As name ... From ...". Anyway, thanks Brodybits for your quick reply. Cheers.

**Comment by brody2consult** [comment]
That sounds like a better solution thanks!
