### ISSUE TITLE
Please make option to use prefilled SQLite database!

### ISSUE THREAD

**Issue by mushketer888** [brody2consult/cordova-sqlite-storage#631]
At now it is possible only to create database (or am i wrong?)
But what if i want to ship app with prefilled .db ?
I know there are options like cordova-plugin-dbcopy ...but this feauture must be in this plugin
Example:
i place db in www folder and then with this plugin I update prefilled DB in /data/.../databases/.. .db
and then use my db in normal way

**Comment by brody2consult** [comment]
I already documented that this is available in cordova-sqlite-ext.
