### ISSUE TITLE
Database created but callbacks not working

### ISSUE THREAD

**Issue by Attaullah7396** [brody2consult/cordova-sqlite-storage#633]
Database opened (OPEN database: data.db - OK)
but callbacks not working.
> Error opening database TypeError: Cannot read property 'then' of undefined
    at main.js:100075
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (main.js:35992)
    at t.invoke (polyfills.js:3)
    at e.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (main.js:35983)
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)

**Comment by brody2consult** [comment]
This appears to be a problem with your own program. I have given plenty of instructions and samples with and without Ionic. In case of a problem like this:
- start by playing with https://github.com/brodybits/cordova-sqlite-storage-starter-app (tested with Android, iOS, and Windows platforms)
- try one thing at a time until you can see what works and what does not work

In case you use Ionic there are a couple decent tutorials (see #585):
- https://www.thepolyglotdeveloper.com/2016/08/using-sqlstorage-instead-sqlite-ionic-2-app/ (more recent)
- https://www.thepolyglotdeveloper.com/2015/12/use-sqlite-in-ionic-2-instead-of-local-storage/ (older)
