### ISSUE TITLE
New install through apple removes previous DB?

### ISSUE THREAD

**Issue by nitzanwilnai** [brody2consult/cordova-sqlite-storage#635]
So we are running into a problem where our newest update causes the local sql db to be erased. 

We are fairly sure it doesn't have to do with our new code, as this problem does not seem to happen when running through xcode. 

Has anyone else faced a problem where installing an update through apple causes the local sqlite db to be erased?

I should add that we are running v1.5.1. It worked for us so far and never saw a reason to update.

**Comment by nitzanwilnai** [comment]
Ok, so I am guessing the issue is that the database location changed. I am using the 'default' location. 

If I change it to either Library or Documents, I get an error. 
[Error] Error: Valid iOS database location could not be determined in openDatabase call
	(anonymous function) (SQLitePlugin.js:571:103)
	(anonymous function) (SQLitePlugin.js:58)
	Init (sketchnation_app.js:1162)
	PhoneGapDeviceReady (index.html:314)
	(anonymous function) (index.html:300)
	fire (cordova.js:777)
	(anonymous function) (cordova.js:231)

This is the line:
      if (!dblocation) {
        throw newSQLError('Valid iOS database location could not be determined in openDatabase call');
      }

This is how I try to initialize the DB
            m_localSQLDatabase = window.sqlitePlugin.openDatabase({name: 'my.db', location: 'Documents'}, function(){log("DB success");}, function(){log("DB error");});

Using 'default' for location works. 'Library' or 'Documents' causes the same error. 

This is with version 1.5.3 (latest) of the plugin.
cordova-sqlite-storage 1.5.3 "Cordova sqlite storage plugin"

**Comment by nitzanwilnai** [comment]
The problem appears to be that openargs.iosDatabaseLocation is undefined.

Copying openargs.location to openargs.iosDatabaseLocation solves the error. I am not sure what the difference between them is and why openargs.iosDatabaseLocation is undefined.

**Comment by nitzanwilnai** [comment]
So in the end it appears that we were initially running version 0.7.11. Updating to any version 4.0+ doesn't bring back the data, regardless of whether we are pointing to default, Documents or Library.

**Comment by brody2consult** [comment]
Sorry for the delay. An upgrade should never erase an old database. Some of the older versions would store the database in `Documents` in which case this should be specified in `iosDatabaseLocation` according to the documentation.
