### ISSUE TITLE
android sqlite database works awesome ios fails unless less then 100 records

### ISSUE THREAD

**Issue by northeastrc** [brody2consult/cordova-sqlite-storage#636]
I am using visual studio 2015 and my android sq lite data base works great
 when i port it to ios, 2 tables fail. I have reset the sim and if i delete all but 100 rows of the table i can get it to work on ios so it is seeing it. i can see the data base in Mozilla and can see nothing wrong with the data.
the database contains 1904 records and some fields have 1000 characters. the database only contains three fields
It appears that it may be timing out, but i am seriously lost i have been beating my head against the wall for 3 days. Any help would be great. Thanks Ron

**Comment by brody2consult** [comment]
Unfortunately I cannot understand what is going on here. Can you make a demo based on https://github.com/brodybits/cordova-sqlite-storage-starter-app or https://github.com/brodybits/cordova-sqlite-test-app?

**Comment by northeastrc** [comment]
Chris think I know what it is.I think the data base has some chars that is
doesn't like maybe line feeds or some non visible chars as I tried
different  tables and they work fine ever heard of such a thing

**Comment by brody2consult** [comment]
That makes sense, thanks!
