### ISSUE TITLE
Vacuum Always return error

### ISSUE THREAD

**Issue by devobenavidez** [brody2consult/cordova-sqlite-storage#637]
Hello i need to VACUUM the database, but when i run the command in a transaction it returns error code 0, this is my example, thanks for your help:

 `vacuumDataBase: function ($scope) {
        var deferred = $q.defer();
        //var queryInsert = " VACUUM";
        var db = $rootScope.dbTmp;

        db.transaction(function (tx) {

          var query = " VACUUM; ";
          //tx.executeSql(" PRAGMA AUTO_VACUUM = 1; ");
          tx.executeSql(query);

        }, function (error) {
          deferred.reject(error);
        }, function () {
          deferred.resolve();
        });

        /*$cordovaSQLite.execute($rootScope.dbTmp, queryInsert).then(function (resInsert) {
          deferred.resolve();
        }, function (err) {
          deferred.reject(err);
        });
      */
        return deferred.promise;
      },`

**Comment by brody2consult** [comment]
Unfortunately I really cannot follow what is going on here. Can you make a demo based on https://github.com/brodybits/cordova-sqlite-storage-starter-app or https://github.com/brodybits/cordova-sqlite-test-app?
