### ISSUE TITLE
u+2028 sqlite

### ISSUE THREAD

**Issue by northeastrc** [brody2consult/cordova-sqlite-storage#639]
Chris i have found my issue in my data base but i have having an issue with replacing them all
 it is the unicode char U+2028. I tried writing a replace statement like 
UPDATE demo7 SET lake= replace(lake, char('u+2028')," ") 
 but no luck am i calling the right char?

Thanks for all your help Ron

**Comment by brody2consult** [comment]
I would do it something like this (within a transaction, NOT TESTED):
```js
tx.executeSql('UPDATE demo7 SET lake=replace(lake,?," ")', '\u2028');
```

Please report if this works for you or not.

**Comment by northeastrc** [comment]
I will try to test soon thanks for the help
