### ISSUE TITLE
Where to put the .db

### ISSUE THREAD

**Issue by tktorza** [brody2consult/cordova-sqlite-storage#640]
Hello, since the beginning that I try to use this plugin, I can't to access to the db: I think that the function create a new db demo.db, I don't know really where and open this base, so where I do:

```Javascript
document.addEventListener('deviceready', function () {
	db = window.sqlitePlugin.openDatabase({ name: 'demo.db', location: 'default' });
	db.transaction(function (tx) {
		tx.executeSql('SELECT * from membre', [], function (tx, rs) {
			alert('Record count (expected to be 2): ' + rs.rows.item(0));
		}, function (tx, error) {
			alert('SELECT error: ' + error.message);
		});
	});
});
```
I work on an IOS simulator, IOS device (iphone 6s), and samsung device.
The alert return that table membre no exists. I have put demo.db in www/ folder and I had test to put in the folder www/../, same result. 
If I understood the documentation, the default location is Library/LocalDatabase folder but my www/ folder is copy at this location or it's not automatic?
Can you help me? I don't understood how to access to my db and where to put .db and to precise the location of .db on ios. 
Thanks a lot.

**Comment by brody2consult** [comment]
> The alert return that table membre no exists. I have put demo.db in www/ folder and I had test to put in the folder www/../, same result.

Not supported by this version. I will document this as a pitfall when I get a chance.

> If I understood the documentation, the default location is Library/LocalDatabase folder

right

> but my www/ folder is copy at this location or it's not automatic?

Not supported by this version. You have to use cordova-sqlite-ext and follow the directions given there.

Please go to the cordova-sqlite-ext version and read the documentation very carefully.

**Comment by tktorza** [comment]
Thanks a lot, it works!
