### ISSUE TITLE
Executing a SELECT * FROM ? doesn't work

### ISSUE THREAD

**Issue by bengrah-miller** [brody2consult/cordova-sqlite-storage#648]
Hi there,

Going on the idea that queries should not be _constructed on the fly_, I've got a few functions that I want to reuse to retrieve values from two different tables, that have the same columns in them. So say I've got a table for _fixeditems_ and a table for _customitems_ - both tables have the same columns. 

My function would return something from either table, the only thing that changes in the query is the table being queried.

So I've tried the following

`this.db.executeSql("SELECT DISTINCT col FROM ?", [table]).then
...
`

When I use the above query, the query will not execute - the code does not run - no errors or nothing. If I modify it so instead of using the _questionmark_ I insert the value of table as part of the query string:

`this.db.executeSql("SELECT DISTINCT col FROM " + table. []).then
...
`

The query will run as expected - am I doing this right?

Thanks,
ben

**Comment by brody2consult** [comment]
> So I've tried the following
> ```js
> this.db.executeSql("SELECT DISTINCT col FROM ?", [table]).then ...
> ```
> When I use the above query, the query will not execute - the code does not run - no errors or nothing.

The `?` placeholder is only supported for expressions. Your code does not seem to catch the error. (It looks like you are using an Ionic or some other kind of ngCordova wrapper.)

> If I modify it so instead of using the *questionmark* I insert the value of table as part of the query string:
> ```js
> this.db.executeSql("SELECT DISTINCT col FROM " + table. []).then ...
> ```
> The query will run as expected - am I doing this right?

The `"SELECT DISTINCT col FROM " + table` part looks right, the following `. []` characters do not look right to me.

To improve the code: you may want to determine the SQL string before running `this.db.executeSql`.

To improve your code even further you may want to consider a more functional approach. Here is a simple example which is *NOT TESTED* and could probably use some improvements:

```js
function newTableAccessor(db, table) {
  const selectColSQL = "SELECT DISTINCT col FROM " + table;
  // other consts

  return {
    getCols: function getCols() {
      return db.executeSql(selectColSQL).then(function(resultSet) {
        return Promise.resolve(resultSet.rows);
      };
    },
    // other accessor functions
}

// near the beginning
const myTableAccessor = newTableAccessor(this.db, "MyTable");

// to get data:
var colData = myTableAccessor.getCols();
```

**Comment by bengrah-miller** [comment]
Hi there,

I've managed to get around it by just updating the actual query ran -
so if this is expected behaviour this could be closed off.

Ben.

Ben Graham | ECM Lead | Miller Homes
T : 0870 336 5062 | M : 07718 526232 | www.millerhomes.co.uk
Miller House, First Floor, 2 Lochside View, Edinburgh Park, Edinburgh,
EH12 9DH



Miller Homes Limited Registered in Scotland - SC255429 

2 Lochside View, Edinburgh Park, Edinburgh, EH12 9DH 

Disclaimer: The Information in this e-mail is confidential and for use
by the addressee(s) only. It may also be privileged. If you are not the
intended recipient please notify us immediately on +44 (0) 870 336 5000
and delete the message from your computer: you may not copy or forward
it, or use or disclose its contents to any other person. We do not
accept any liability or responsibility for: (1) changes made to this
email after it was sent, or (2) viruses transmitted through this email
or any attachment.

>>> "Christopher J. Brody" <notifications@github.com> 15/03/2017 14:27
>>>
So I've tried the following
this.db.executeSql("SELECT DISTINCT col FROM ?", [table]).then ...
When I use the above query, the query will not execute - the code does
not run - no errors or nothing.
The ? placeholder is only supported for expressions. Your code does not
seem to catch the error. (It looks like you are using an Ionic or some
other kind of ngCordova wrapper.)
If I modify it so instead of using the questionmark I insert the value
of table as part of the query string:
this.db.executeSql("SELECT DISTINCT col FROM " + table. []).then ...
The query will run as expected - am I doing this right?
The "SELECT DISTINCT col FROM " + table part looks right, the following
. [] characters do not look right to me.
To improve the code: you may want to determine the SQL string before
running this.db.executeSql.
To improve your code even further you may want to consider a more
functional approach. Here is a simple example which is NOT TESTED and
could probably use some improvements:
function newTableAccessor(db, table) { const selectColSQL = "SELECT
DISTINCT col FROM " + table; // other consts return { getCols: function
getCols() { return db.executeSql(selectColSQL).then(function(resultSet)
{ return Promise.resolve(resultSet.rows); }; }, // other accessor
functions}// near the beginningconst myTableAccessor =
newTableAccessor(this.db, "MyTable"); // to get data:var colData =
myTableAccessor.getCols();
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(
https://github.com/litehelpers/Cordova-sqlite-storage/issues/648#issuecomment-286758141)
, or mute the thread
(

**Comment by brody2consult** [comment]
Thanks!
