### ISSUE TITLE
Application crash if ZBar plugin is installed

### ISSUE THREAD

**Issue by SirusDoma** [brody2consult/cordova-sqlite-storage#651]
I'm creating application that heavily depend on barcode scanner.
Since phonegap-barcodescanner-plugin works really slow, I found alternative that perform faster scanning called [ZBar](https://github.com/tjwoon/csZBar).

After installing this plugin, I realize that I require SQLite in my application. I installed the plugin and it works! but when I try scan with zbar the application crash.

Not sure what happened, and it strange that I suppose there is no relation between storage and camera right? so Is there any chance to fix this from SQLite side?

**Comment by brody2consult** [comment]
You may want to try requesting sqlite and zbar operations in different event ticks, similar to a workaround needed for the Pusher plugin ref #196. I will document this when I get a chance.

To get support from the user community I suggest you make a small, self contained test program.

For priority, commercial support you may contact <sales@litehelpers.net> for more information.
