### ISSUE TITLE
Question about versions/build numbers

### ISSUE THREAD

**Issue by mirko77** [brody2consult/cordova-sqlite-storage#654]
Hi there,

I have an app that uses version 1.4.5 which is having problems on iOS (on all versions we support, 8+)

When installing the latest version I get:
`cordova-sqlite-storage 2.0.2 "Cordova sqlite storage plugin"`

Reading through Changes.MD, I do not see anything past 1.5.3

Am I missing something? 

Are there any breaking changes I need to take care of?

I have seen other issues about this. I have an existing app on Android (4.4+) and iOS (8+), am I good to go?

according to #615, differences are only on the Windows platform?

**Comment by brody2consult** [comment]
Answered in https://github.com/litehelpers/Cordova-sqlite-storage/issues/615#issuecomment-288842039
