### ISSUE TITLE
error while trying to roll back: undefined

### ISSUE THREAD

**Issue by MeMTn** [brody2consult/cordova-sqlite-storage#66]
Does anyone knows why am I getting this error Msg? and why the transaction is failing?
error while trying to roll back: undefined.

**Comment by dfabreguette-ap** [comment]
Looks like i'm facing the same error. I'm using sqlite Plugin the simple way. Here's my code :

```
    var db = window.sqlitePlugin.openDatabase({name: db_name});

    var tables = [
      'CREATE TABLE IF NOT EXISTS MISSIONS  (ID TEXT, CLIENT TEXT, CLIENT_ID TEXT, DATE TEXT, DATE_CLOTURE TEXT, ESPACE TEXT, PRESTATION TEXT, COORDS TEXT, ADRESSE TEXT, CP TEXT, VILLE TEXT, ETAT TEXT, MISSION_STATE TEXT, DIRECTION INTEGER)',
    ];

    for(i=0; i < tables.length; i++){
      table = tables[i];

      db.transaction(function(tx) {
        tx.executeSql(table, null, function(e){}, function(e){
          console.error(e);
        });
      },function(e){
        console.error(e);
      });
    };

    db.close();
```

I looked further in and found this error supposed to appear when transaction is aborted. Thing is would this method be called during a transaction ?

**Comment by dfabreguette-ap** [comment]
Eventually, problem was on my side.
Getting rid of the "db.close()" part solved the problem.
