### ISSUE TITLE
Problem on device and emulator

### ISSUE THREAD

**Issue by mireen** [brody2consult/cordova-sqlite-storage#662]
Hello, 
First sorry for my English, i'm French...
I am developing an app with Ionic and when I launch "Ionic serve", everything works well, I can register new entries in my database and display them. 
But when I run my app on an emulator (IOS) or on my phone (Android), nothing seems to work.

Here's what I want to do:
From the home screen I can click on "Photographie".
The list of recorded albums is displayed and I can create a new one by name.
 
But on my phone and the emulator I can not even click on Photography ... And after that the whole application bug.

**app.js :** 
.run(function($ionicPlatform, $cordovaSQLite) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      cordova.plugins.Keyboard.disableScroll(true);
    }
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
    **if (window.cordova) {
          db = $cordovaSQLite.openDB({ name: "my.db" }); //device
        }else{
          db = window.openDatabase("my.db", '1', 'my', 1024 * 1024 * 100); // browser
          console.log(db)
        }
    $cordovaSQLite.execute(db, "CREATE TABLE IF NOT EXISTS albumPhoto (id integer primary key autoincrement, nom text, dateCreation date default CURRENT_DATE)")**
  });
})

**controllers.js :** 
.controller('PhotographieCtrl', function($scope, $ionicPopup, $cordovaSQLite) {
  **$scope.Init = function () {
    $scope.albums= [];

    var query = "SELECT * from albumPhoto";
    $result = $cordovaSQLite.execute(db, query) .then(
         function(res) {
              if (res.rows.length > 0) {
                  for (var i=0; i<res.rows.length; i++) {
                     $scope.albums.push(res.rows.item(i));
                  }
                  console.log($scope.albums)
               }
          },
          function(error) {
               alert("Error on loading: " + error.message);
          }
       );
  }**

  $scope.newAlbum = function() {

    $scope.data = {};

    var popupPhoto = $ionicPopup.show({
      cssClass: 'mypopup',
      title: 'Nouvel Album',
      template: ' Nom <input type="text" ng-model="data.album"> ',
      scope: $scope,
      buttons: [
        {
          text: 'Retour',
          type: 'button-calm',
        },
        {
          text: 'Valider',
          type: 'button-calm',
          onTap: function(e) {
            if(!$scope.data.album) {
              e.preventDefault();
            } else {
              var query = "INSERT INTO albumPhoto (nom, dateCreation) VALUES (?, ?)";
              $cordovaSQLite.execute(db, query, [$scope.data.album, new Date()]).then(function(res) {
                $scope.Init();
              }, function(err) {
                console.error(err);
              })
            }
          }
        }
      ]
    })
  };

  $scope.Init();
})
This is my home screen : 
![screen shot 2017-04-04 at 11 56 23](https://cloud.githubusercontent.com/assets/16655517/24651342/bc82ec4a-192d-11e7-9d60-7807c0bbd26a.png)

And my photography page : 
![screen shot 2017-04-04 at 11 57 29](https://cloud.githubusercontent.com/assets/16655517/24651385/e5f7b1d2-192d-11e7-9b5d-82c887c10122.png)

Hope you understand my request, 

Thank you

**Comment by mankeomorakort** [comment]
I have the same issue. It work only on browser by not work in android 6.0

My system information:
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.2
Node Version: v6.9.5
Xcode version: Not installed

and cordova-sqlite-storage: 2.0.2

**Comment by brody2consult** [comment]
> ```js
> db = $cordovaSQLite.openDB({ name: "my.db" }); //device
> ```

the `location` setting is missing.

**Comment by mireen** [comment]
Thank you @brodybits ! So stupid error ....
