### ISSUE TITLE
Cannot create additional tables

### ISSUE THREAD

**Issue by luigi37** [brody2consult/cordova-sqlite-storage#664]
Hi.
I'm using Cordova 6.5.0 and cordova-sqlite-storage (tried 1.5.3 and 2.0.3)
I use this statement to add tables:

tx.executeSql("CREATE TABLE IF NOT EXISTS my_Track (id INTEGER PRIMARY KEY AUTOINCREMENT, Track_ID INTEGER, Track_Name TEXT)", []);

tx.executeSql("CREATE TABLE IF NOT EXISTS my_Track2 (id INTEGER PRIMARY KEY AUTOINCREMENT, Track_ID INTEGER, Track_Name TEXT)", []);

If the App is not installed, everything works fine and all the tables get created.

If the DB and some tables are already existing, it does not allow me to add the new table...

What I'm doing wrong here?

Thanks

**Comment by luigi37** [comment]
I went a little bit deeper.
First of all, apologies, because I realised that my app uses STD websql implementation for Android and this plugin for iOS.
So the issue with std websql was sorted using:

myweb.db.changeVersion(myweb.db.version, "1.1", function(tx){
                    tx.executeSql("CREATE TABLE IF NOT EXISTS....

Questions:
1- Is something similar required to change the structure of the DB? Which instruction specifically?
2- If I want to migrate my db to this plugin also for Android, can I do that straight or shall I cancel and recreate the db?

Thanks

Luigi

**Comment by luigi37** [comment]
Tried to simply apply also this one:
tx.executeSql("CREATE TABLE IF NOT EXISTS xyz (id INTEGER PRIMARY KEY AUTOINCREMENT, Track_ID INTEGER, Track_Name TEXT)", [],function(){console.log('all good');},function(){console.log('problem');});

Unfortunately it seems like it does not get executed...

**Comment by luigi37** [comment]
For anybody interested...

websql std: 
myweb.db.changeVersion(....

sqlite: 
db: sqlitePlugin.openDatabase({name: dbName, location: 2},function(tx) {				
                            tx.executeSql("CREATE TABLE IF NOT EXISTSTrack (id INTEGER PRIMARY KEY AUTOINCREMENT, Track_ID INTEGER, Track_Name TEXT)", [],function(){console.log('all good');},function(){console.log('problem');});
                        }
                    )

In brief, in sqlite-storage it's ok to add a table as long as it's done at db opening

Maybe it's common behaviour but it took me some time to figure out.

**Comment by brody2consult** [comment]
Thanks and my apologies for the delay. In general this kind of question should be asked in <https://github.com/litehelpers/Cordova-sqlite-help/issues>.

**Comment by luigi37** [comment]
No problem at all. Thank you!
