### ISSUE TITLE
v2.0.3 Invalid Database Hanle in Windows

### ISSUE THREAD

**Issue by ajberry** [brody2consult/cordova-sqlite-storage#665]
` var db = null;
            db = window.sqlitePlugin.openDatabase({ name: "presales.db", location: 'default' });
            db.transaction(function (tx) {
                tx.executeSql("CREATE TABLE IF NOT EXISTS form (customer text primary key, data text)");
                tx.executeSql("CREATE TABLE IF NOT EXISTS settings (setting text primary key, value text)");
                tx.executeSql("CREATE TABLE IF NOT EXISTS token (token text primary key, date text)");
            }, function (error) {
                navigator.notification.alert("An error occured when initialising the app.", function alertDismissed() { }, "Error", "OK");
            }, function () {
                console.log('Populated database OK');
            });`

Basic code above, v2.0.3 of plugin causes error on Windows build, same code works with Android

**Comment by brody2consult** [comment]
It looks like an installation issue, please see #655 and <https://github.com/litehelpers/Cordova-sqlite-help/issues/16> for discussion. In case of further issues please ask in <https://github.com/litehelpers/Cordova-sqlite-help/issues>.
