### ISSUE TITLE
Version 1.5.4 not published to npm

### ISSUE THREAD

**Issue by mobidev111** [brody2consult/cordova-sqlite-storage#670]
Version 1.5.4 is not published to npm, version 2.0.3 is published though.

**Comment by brody2consult** [comment]
Version 1.5.4 contained some last-minute changes needed for cordova-sqlcipher-adapter and does not contain the changes needed for VS 2017. All new versions will be based on 2.0.3 which DOES include the changes needed for VS 2017. VS 2015 is now supported by Cordova-sqlite-legacy-build-support, no longer supported by this version.

I may publish 1.5.4 under a special legacy tag on npm, not decided yet.
