### ISSUE TITLE
How to VACUUM?

### ISSUE THREAD

**Issue by tktorza** [brody2consult/cordova-sqlite-storage#678]
Hello,
I try to VACUUM my db after to have delete table content but I don't know how to do this with the pugin.

I have try this:

`

 tx.executeSql("DELETE FROM event", [], function (tx, rs) {
			console.log('SQLITE 1');
			tx.executeSql("VACUUM", [], function (tx, rs) {

				console.log('SQLITE 2');

			});
		});
`

but it doesn't work. In documentation you said that it's good to VACUUM database sometimes but I haven't see where to do this? 

Thanks

**Comment by brody2consult** [comment]
Answered in litehelpers/Cordova-sqlite-help#28.
