### ISSUE TITLE
'SQLite3' is undefined: Build windows Ionic 2

### ISSUE THREAD

**Issue by sherozejoomun** [brody2consult/cordova-sqlite-storage#689]
Hello,

I am having the following issue on building windows in Visual Studio.

`Exception was thrown at line 126, column 7 in ms-appx://com.xxxx.xxxxx/www/plugins/cordova-sqlite-storage/src/windows/SQLite3-Win-RT/SQLite3JS/js/SQLite3.js
0x800a1391 - JavaScript runtime error: 'SQLite3' is undefined`

In the Javascript console i have the following:
`The method Windows.UI.ApplicationSettings.SettingsPane.getForCurrentView has been deprecated. SettingsPane is deprecated and might not work on all platforms. For more info, see MSDN.
The event Windows.UI.ApplicationSettings.SettingsPane.add_CommandsRequested has been deprecated. SettingsPane is deprecated and might not work on all platforms. For more info, see MSDN.
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
deviceready has not fired after 5 seconds.
Channel not fired: onPluginsReady
Channel not fired: onCordovaReady
adding proxy for Device
adding proxy for NetworkStatus
adding proxy for SplashScreen
adding proxy for StatusBar
adding proxy for SQLitePlugin
adding proxy for Keyboard
adding proxy for PushNotification
DEVICE READY FIRED AFTER 4887 ms
OPEN database: __ionicStorage
open db name: __ionicStorage at full path: C:\Users\user\AppData\Local\Packages\com.xxxx.xxxxxxx_h35559jr9hy9m\LocalState\__ionicStorage
Platform Ready
OPEN database: __ionicStorage FAILED, aborting any pending transactions
Error: Could not open database
   {
      [functions]: ,
      __proto__: { },
      code: 0,
      description: "Could not open database",
      message: "Could not open database",
      name: "Error",
      Symbol(observable)_l.s1ba2exi1e0: undefined,
      Symbol(rxSubscriber)_k.s1ba2exi1e0: undefined
   }

EXCEPTION: Uncaught (in promise): Error: Could not open database
ORIGINAL STACKTRACE:
Error: Uncaught (in promise): Error: Could not open database
   at s (ms-appx://com.xxxx.xxxx/www/build/polyfills.js:3:4205)
   at s (ms-appx://com.xxx.xxxxxx/www/build/polyfills.js:3:4034)
   at Anonymous function (ms-appx://com.xxxxxci.xx/www/build/polyfills.js:3:4574)
   at t.prototype.invokeTask (ms-appx://com.xxx.xxxx/www/build/polyfills.js:3:9614)
   at onInvokeTask (ms-appx://com.xxxx.xxxx/www/build/main.js:40157:21)
   at t.prototype.invokeTask (ms-appx://com.xxxx.xxx/www/build/polyfills.js:3:9614)
   at e.prototype.runTask (ms-appx://com.xxxx.xxx/www/build/polyfills.js:3:7057)
   at i (ms-appx://com.xxxx.xxx/www/build/polyfills.js:3:3664)
   at invoke (ms-appx://com.xxxxx.xxxxx/www/build/polyfills.js:3:10876)
   at e.args[0] (ms-appx://com.xxxxx.xxxxx/www/build/polyfills.js:2:30114)
`
cordova-sqlite-storage v2.0.3

Ionic Info

-  Cordova CLI: 6.5.0
- Ionic Framework Version: 2.0.0
- Ionic CLI Version: 2.2.3
- Ionic App Lib Version: 2.2.1
- Ionic App Scripts Version: 1.0.0
- OS: Windows 10
- Node Version: v6.9.2

**Comment by brody2consult** [comment]
As I said in https://github.com/litehelpers/Cordova-sqlite-storage/issues/688#issuecomment-300473350:
- Start with https://github.com/brodybits/cordova-sqlite-storage-starter-app and use Cordova CLI to add Windows platform
- Open the generated Visual Studio solution project with Visual Studio 2017 and try both debug and release builds
- Then try building and running from Cordova CLI (no Ionic)

Marking as duplicate for now.

**Comment by sherozejoomun** [comment]
Visual Studio 2017 works for me.
