### ISSUE TITLE
property sqliteplugin dose not exist on type 'window'

### ISSUE THREAD

**Issue by hexufeng** [brody2consult/cordova-sqlite-storage#691]
i have installed the plugin by document!

then i run test:
window.sqlitePlugin.echoTest(function() {
      console.log('ECHO test OK');
    });

webstorm note that "**Property sqliteplugin dose not exist on type 'Window'**". also my program can not run because of the error.

something i have not done ?

**Comment by chaje** [comment]
try this
(< any > window).plugins
or
window.plugins.myplugin.someMethod();
maybe you can find a solution here:
https://www.joshmorony.com/using-cordova-plugins-in-ionic-2-with-ionic-native/

**Comment by hexufeng** [comment]
@chaje thanks for reply, but it dose not work. the same error:
`Uncaught (in promise): TypeError: Cannot read property 'sqlitePlugin' of undefined
TypeError: Cannot read property 'sqlitePlugin' of undefined`

**Comment by brody2consult** [comment]
You may want to try starting with <https://github.com/brodybits/cordova-sqlite-storage-starter-app>.

**Comment by hexufeng** [comment]
@brodybits Hi , thanks for advise. but i have done a lot of work on my app, so i can not create a new app do everything again. i just want to find a sqlite plugin and saw this plugin looks great !

**Comment by brody2consult** [comment]
Here is what I would advise:

Start with <https://github.com/brodybits/cordova-sqlite-storage-starter-app> and try adding or changing one thing at a time until you find out what does and does not work.
