### ISSUE TITLE
After update, it doesn't work

### ISSUE THREAD

**Issue by abram456** [brody2consult/cordova-sqlite-storage#696]
Attached the log below

```
OPEN database: d2a.db
plugins/cordova-sqlite-storage/www/SQLitePlugin.js:106 
new transaction is waiting for open operation 
plugins/cordova-sqlite-storage/www/SQLitePlugin.js:197 
OPEN database: d2a.db FAILED, aborting any pending transactions 
plugins/cordova-sqlite-storage/www/SQLitePlugin.js:83 
Could not open database

```
@brodybits

**Comment by brody2consult** [comment]
My apologies for the delay, more information needed to investigate.

**Comment by wilywork** [comment]
hello,
I'm getting the same error. Was working but something corrupted.

my code:
banco = window.sqlitePlugin.openDatabase({ name: "produtos.db",location: "2"});

error try execute:
Could not open database
OPEN database: produtos.db FAILED, aborting any pending transactions


Is there any way to delete or reassemble this same bank at location 2?

**Comment by wilywork** [comment]
solved!
I deleted DB produtos.db using:
window.sqlitePlugin.deleteDatabase({ name: "produtos.db",location: 2});
