### ISSUE TITLE
iOS Memory Consumption grows with each query

### ISSUE THREAD

**Issue by enayetn** [brody2consult/cordova-sqlite-storage#699]
Hello, 

I am seeing that each transaction with the DB results in a spike in RAM consumption, followed by a persistent bump in memory usage. I have included a memory usage graph below. I have observed this behavior both in this plugin (Cordova-sqlite-storage) as well as the evcore distribution (Cordova-sqlite-evcore-extbuild-free). Would love some fresh eyes on my steps and see if I'm just doing something silly or if this is happening to others. I did not see any sort of API to close my transaction after running one, so I'm at a loss as to why the memory consumption keeps rising with each query. Thanks in advance for any insight anyone can provide. 

![image](https://user-images.githubusercontent.com/4724674/27234751-be703474-5283-11e7-9867-497963ae03dd.png)
_Notice the drop after the 2nd query, this seems to happen after running a new query after leaving the application alone for some time. I have left this running for hours and the memory usage remains steady, and then the first query run after a long idle period will clear some memory (but not back to baseline), so it seems something is tying up the memory and not allowing it to be removed (Excuse my theorizing, I don't have much native experience with this stuff)._

Note that this is in a brand new, clean Ionic application. I have included replication steps & code below, theoretically this should be usable & reproducible in a plain cordova environment as well. 

**Create DB** 
```
var dbOptions = {
        name : 'mydb.db',
        location : 'default'
      };
     db = window.sqlitePlugin.openDatabase(
        dbOptions
      );
```

**Create Table**
```
db.transaction(function(tx){
	tx.executeSql("CREATE TABLE IF NOT EXISTS user_applications (id TEXT PRIMARY KEY NOT NULL,name TEXT,logo BLOB,appfile BLOB)", null, function(tx,r){console.log(r)})
}, function(e){console.log(e);});
```

**Insert Dummy 10,000 Rows** - The memory usage is more easily seen with larger SELECT statements
```
db.transaction(function(tx){
	for (var i=0; i<10000; i++) {tx.executeSql("INSERT INTO user_applications (id,name,logo,appfile) VALUES ("+i+",1,1,1)", null, function(tx,r){console.log(r)});}
}, function(e){console.log(e);});
```

**Perform Queries** - Each query run here (tested through both running in console & code) will result in a little spike followed by a persistent bump in memory consumption. This seems to be proportional to the # of rows being selected. 
```
db.transaction(function(tx){
	tx.executeSql("SELECT * FROM user_applications", null, function(tx,r){console.log(r)})
}, function(e){console.log(e);});
```

Below is a gif of me running the last query & observing the memory spike in XCode

![image](https://i.gyazo.com/ce8acb841b8dd2279fc7a4eb65cad795.gif)

**Comment by enayetn** [comment]
@brodybits any thoughts?

**Comment by dvdpzzt-webmapp** [comment]
@enayetn Did you solve it?

**Comment by enayetn** [comment]
@dvdpzzt-webmapp embarrassingly this issue was my own doing, the memory grew due to the console logging after each query. Apologies, I should have listed that when I closed the issue!

Cheers
