### ISSUE TITLE
echoTest - errorCallback doesn't work on iOS

### ISSUE THREAD

**Issue by jdnichollsc** [brody2consult/cordova-sqlite-storage#700]
Hi my friend,

I'm testing the **echoTest** method, on Android work's perfect but on iOS doesn't work. I'm testing with the javascript file (Because I need that case), so the **sqlitePlugin** object exist but the plugin is not installed on the device.

Let me know what you think.
Thanks in advance, Nicholls

**Comment by brody2consult** [comment]
This indicates either a problem with the installation or that the app does not wait for the `deviceready` event on iOS.
