### ISSUE TITLE
Error: exec proxy not found for :: Zip :: unzip

### ISSUE THREAD

**Issue by amlalnabil** [brody2consult/cordova-sqlite-storage#704]
installed platforms:  android, browser

i tested it in browser and i get this:
Error: exec proxy not found for :: Zip :: unzip  cordova.js:989:9
-1
FAILED

this is my function:

Unzip() {

    var source = "../../assets/eval.zip";

    this.zip.unzip(source , '../../assets/folder/', (progress) => console.log('Unzipping, ' + Math.round((progress.loaded / progress.total) * 100) + '%'))
      .then((result) => {
        console.log(result);
        if(result === 0) console.log('SUCCESS');
        if(result === -1) { 
          console.log('FAILED');
        }
    });

  }

Thank you!

**Comment by brody2consult** [comment]
Not supported by this project.
