### ISSUE TITLE
Sqlite : insert dynamic array into table

### ISSUE THREAD

**Issue by arijitnaskar** [brody2consult/cordova-sqlite-storage#705]
I am trying to insert an array into my sqlite database. But all the data is getting inserted into the first column. Please help. I already checked this issue: [](https://github.com/litehelpers/Cordova-sqlite-storage/issues/392)

my code is 
 ` let insertarr:Array<string>;
      
for(var i=0;i<this.fullData.length;i++)
      
{
        insertarr = [];
          for(var j=0;j<this.fullData[i].length;j++)
          {
         
            insertarr.push(this.fullData[i][j].val);
          
          }
         alert(insertarr);
          db.executeSql('insert into mytable (col1, col2, col3) values(?,?,?)', [insertarr]);  
      }`

**Comment by enayetn** [comment]
You're nesting your array in the `executeSql` command. (`insertarr` is already an array, so you end up with `[['item1','item2','item3']]`), therefore it makes sense that your first column gets populated with the 1st index of this array, which is the array you meant to inject. 

Try this instead:

`db.executeSql('insert into mytable (col1, col2, col3) values(?,?,?)', insertarr);`
