### ISSUE TITLE
DEFAULT LOCATION

### ISSUE THREAD

**Issue by payoh** [brody2consult/cordova-sqlite-storage#707]
I put a prepopulated 'db.sqlite3' in  cordova.file.documentsDirectory on IOS, i open with command

db =  window.sqlitePlugin.openDatabase({name: 'db.sqlite3', location: 1}); 

but when i try to read the table insert the console say "no such table *** "

What is the default location in IOS?

**Comment by brody2consult** [comment]
location: 1 means library, please double-check the documentation.
