### ISSUE TITLE
UWP error SQLite3 step error result code: 1

### ISSUE THREAD

**Issue by jhjulkun** [brody2consult/cordova-sqlite-storage#712]
Thanks for the plugin!!

I have a project that works in both Android and iOS, and just started working on the UWP version.
The plugin manages to open a database (pre-populated) and although it seems to return some data I always get a 
'sql exepction error: SQLite3 step error result code: 1'

The plugin DOES however seem to work on a more straight forward database (also prepopulated), 
so my question is, are there some types of database object/schemas that need to be avoided for the UWP version ? 

This is the testcase and the results:
function testDB() {
    window.sqlitePlugin.openDatabase({ name: 'test.db',
				       location: 'default' },
      function (db) {
	  db.executeSql("select name,value from metadata", [], function (res) {
	      console.log("res.rows.length: " + res.rows.length);
              for (var i = 0; i < res.rows.length; i++) {
		  console.log("SQL rc: "+JSON.stringify(res.rows.item(i)));
	      }
   });
  });
}

OPEN database: test.db - OK
sql exepction error: SQLite3 step error result code: 1
res.rows.length: 7
SQL rc: {"name":"name","value":"Blah"}
etc (for next 6 lines)

Sorry for typing the messages from VS, doesn't seem you can save JS output to file ??

Thanks!

**Comment by jhjulkun** [comment]
Tried to narrow down the problem a little more.
Turns out even the https://github.com/brodybits/cordova-sqlite-test-app also (for me) throws
'sql exepction error: SQLite3 step error result code: 1'
(but otherwise appears to be working)

However, the example also has issues after switching pages, but sounds like you have been debugging that already ?

It almost sounds like there are some async issues with the UWP version ?

I tried using the pre-populated (LARGE) downloaded .db files I want to use (used in iOS and Android), 
and I get a ton of these:
sql exception error: Unsupported column type in column 0
(these queries are definitely async, and lots of them)

When testing the downloaded .db file in the command line sqlite3 tool it appears to be correct as they pass the 'pragma integrity_check' 
(and again these files are used in both iOS and Android)
 
Thanks!

**Comment by brody2consult** [comment]
Closing as invalid. As documented pre-populated databases are supported by cordova-sqlite-ext, please raise issue there along with demo if it still does not work. For cordova-sqlite-test-app beware that you have to add sqlite plugin for it to work (as documented).
