### ISSUE TITLE
iOS threading issue with openDatabase?

### ISSUE THREAD

**Issue by craig-at-rsg** [brody2consult/cordova-sqlite-storage#716]
I have intermittent crashes when my app starts up on iOS, and my guess is it's related to calling openDatabase from different places. I need to restart my app multiple times before I hit this. Here's a screenshot - if this doesn't point to the cause, let me know and I'll try creating a test app.

![screen shot 2017-09-05 at 4 37 38 pm](https://user-images.githubusercontent.com/6004181/30082546-38fb420a-9259-11e7-9aa2-452178cc2210.png)

**Comment by craig-at-rsg** [comment]
openDBs is an NSMutableDictionary, which isn't designed for thread safety...

**Comment by craig-at-rsg** [comment]
I used a thread safe dictionary (https://gist.github.com/steipete/5928916) in my local build for openDBs, and that fixed the problem I was seeing. I tried to branch this plugin, but I haven't gotten that working yet..

**Comment by brody2consult** [comment]
On Tue, Sep 5, 2017 at 9:43 PM, craig-at-rsg <notifications@github.com>
wrote:

> I used a thread safe dictionary (https://gist.github.com/steipete/5928916)
> in my local build for openDBs, and that fixed the problem I was seeing. I
> tried to branch this plugin, but I haven't gotten that working yet..
>

Thanks @craig-at-rsg for the report, details, and workaround. I will deal
with this when I get a chance, been extremely busy with some work for a
client.

**Comment by craig-at-rsg** [comment]
Thanks @brodybits, no rush; my fork is working for me. 
https://github.com/litehelpers/Cordova-sqlite-storage/compare/storage-master...craig-at-rsg:2.0.4.1?expand=1

**Comment by brody2consult** [comment]
Marking this as a bug, with possible data loss risk. Will integrate the proposed workaround / solution  in the near future.

**Comment by brody2consult** [comment]
Proposed workaround solution and flag fix for #703 are now integrated with cordova-sqlite-ext, will be integrated with this version in the near future.

**Comment by brody2consult** [comment]
Proposed workaround solution is now integrated with this plugin version (cordova-sqlite-storage), will be merged into the other plugin versions in the near future. Thanks again for the contribution.
