### ISSUE TITLE
Cordova  SQLite  IOS

### ISSUE THREAD

**Issue by koronaldo** [brody2consult/cordova-sqlite-storage#718]
Bom dia.

Estou com um problema que não consegui resolver, poderia me ajudar?

Tenho uma aplicação que desenvolvi com Cordova 7.1.0, adicionei o plugin Cordova-sqlite-storage.  No android funciona que é uma blz. já no ios ele não roda. Abre a conexão com o banco , mas quando chega no db.transaction ele trava, minutos depois ele executa, leva em media 3 minutos pra responder. ja testei varios plugin tive o mesmo problema, não sei mais oque posso testar, não gera nenhum tipo de erro, apenas fica lento e demora pra retornar.

OBrigado.

**Comment by brody2consult** [comment]
From Google Translate <https://translate.google.com/#auto/en/Bom%20dia.%0A%0AEstou%20com%20um%20problema%20que%20n%C3%A3o%20consegui%20resolver%2C%20poderia%20me%20ajudar%3F%0A%0ATenho%20uma%20aplica%C3%A7%C3%A3o%20que%20desenvolvi%20com%20Cordova%207.1.0%2C%20adicionei%20o%20plugin%20Cordova-sqlite-storage.%20No%20android%20funciona%20que%20%C3%A9%20uma%20blz.%20j%C3%A1%20no%20ios%20ele%20n%C3%A3o%20roda.%20Abre%20a%20conex%C3%A3o%20com%20o%20banco%20%2C%20mas%20quando%20chega%20no%20db.transaction%20ele%20trava%2C%20minutos%20depois%20ele%20executa%2C%20leva%20em%20media%203%20minutos%20pra%20responder.%20ja%20testei%20varios%20plugin%20tive%20o%20mesmo%20problema%2C%20n%C3%A3o%20sei%20mais%20oque%20posso%20testar%2C%20n%C3%A3o%20gera%20nenhum%20tipo%20de%20erro%2C%20apenas%20fica%20lento%20e%20demora%20pra%20retornar.%0A%0AOBrigado.>:

<blockquote>
Good Morning.

I have a problem that I could not solve, could you help me?

I have an application that I developed with Cordova 7.1.0, I added the Cordova-sqlite-storage plugin. In android works that is a blz. already in the ios it does not rotate. It opens the connection to the bank, but when it arrives in db.transaction it hangs, minutes later it executes, it takes in average 3 minutes to respond. I tried several plugins and I had the same problem, I do not know what I can test, it does not generate any type of error, it only slows down and it takes a while to return.

Thank you.
</blockquote>

Looks like the same question in <https://github.com/nolanlawson/cordova-plugin-sqlite-2/issues/53>

**Comment by brody2consult** [comment]
This is likely caused by another long-running operation in the sqlite database.
