### ISSUE TITLE
Question about new recommended calls

### ISSUE THREAD

**Issue by jondediego** [brody2consult/cordova-sqlite-storage#722]
I am working in a project were performance is important. So we try to insert a lot of records. Also, when some insertion fails we don't need to rollback, but we need to do detect which element produced the error, don't execute next inserts, but allow the previous inserts to persist.
So in order to achieve good performance we want to use db.sqlBatch method instead of db.executeSql. Is there a way we can achieve this behaviour using db.sqlBatch? I know how to achieve it using deprecated db.transaction, but I wanted to know if this also could be achieved using new calls.

**Comment by brody2consult** [comment]
Adding a cross-reference to #720.

You seem to have an almost perfect case for the deprecated Web SQL API, which I have not seen so often. It would be possible to add an option to the sqlBatch call to support your use case but then we would start another road to the kind of complexity I was hoping to get rid of.

For your case I would recommend using the cordova-sqlite-ext version which will continue to support the Web SQL API for the foreseeable future.

I would like to continue the discussion in #720, closing this one.
