### ISSUE TITLE
Crash's in iOS with cordova-sqlitestorage SQLiteStatement::executeCommand()

### ISSUE THREAD

**Issue by naren97** [brody2consult/cordova-sqlite-storage#724]
Hi

Lately after upgrading to cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin" noticed lot of crashes in app store. reason - WebCore: WebCore::SQLiteStatement::executeCommand() + 116.

I am not able to reproduce the issue and debug the root cause. Crash reports are high close to 16k.
Is it because of database is corrupted? its not related to queue's as all transactions are happening on Global-queue.
I searched a lot, but I did not find a solution. Who has any ideas? Thanks

<img width="687" alt="screen shot 2017-11-06 at 6 46 14 am" src="https://user-images.githubusercontent.com/6494546/32446585-3d5fa7b0-c2be-11e7-96ba-38c661d57ecc.png">

**Comment by brody2consult** [comment]
The trace indicates to me that your app is using Web SQL. Please double check and follow the instructions very carefully. It is recommended to use <https://github.com/brodybits/cordova-sqlite-storage-starter-app> as a starting point, as documented.

**Comment by naren97** [comment]
@brodybits the application is built using cordova and using native plugin cordova-sqlite-storage to create db on disc. So we are not using web SQL. 

                    db = window.sqlitePlugin.openDatabase({
                        name: "XXX",
                        iosDatabaseLocation: "Documents"
                    });

**Comment by brody2consult** [comment]
Please post reproduction project based on <https://github.com/brodybits/cordova-sqlite-storage-starter-app> or <https://github.com/brodybits/cordova-sqlite-test-app> if you want help with this (be sure to explicitly add the sqlite plugin in case of <https://github.com/brodybits/cordova-sqlite-test-app>).
