### ISSUE TITLE
Driver.so files in apk

### ISSUE THREAD

**Issue by jntr06** [brody2consult/cordova-sqlite-storage#728]
Hi Chris,
This plugins include five driver.so files in apk file of the app which increase the app size by almost 2 mb. I do not want to change the plugin as it works absolutely fine in my app. Is there any way we can avoid these files to reduce the app size.

**Comment by brody2consult** [comment]
You *could* leave some of the *.so files out. For example: if you omit 64-bit *.so files then it should work on 32-bit platform. Also you may not want both `armeabi` and `armeabi-v7a` libs. But you have to do this for all libraries. For example: if you omit 64-bit *.so files for this plugin but NOT for another library then it will not work. Also for armeabi and armeabi-v7a.

Next major release may be make without the *.so files ref: #687

**Comment by jntr06** [comment]
Chris
Thanks for your response on this. That would be great, sqlite without the so files.
Any timeline for next major release. By when we can expect this to be available.

**Comment by brody2consult** [comment]
Unfortunately I really cannot make any promises due to some other urgent issues and commitments. As I said in <https://github.com/litehelpers/Cordova-sqlite-storage/issues/729#issuecomment-355194460> I may support this in a special "express" version instead.

**Comment by brody2consult** [comment]
New express version without the *.so objects is now tracked in #740, closing this one.
