### ISSUE TITLE
Android: cannot open existing database after update, using location 'default'

### ISSUE THREAD

**Issue by mbmerrill** [brody2consult/cordova-sqlite-storage#734]
I have an application that was written using 0.7.10 of this plugin.  I'm attempting to bring it up to version 2.1.2 of this plugin.

I noticed the doc stating that I need to specify a location; I've specified 'default'.

After deploying my application to an Android device running the previous version of my app, I cannot see any previously-existing data.

The documentation for this plugin made me think that the dire warning of "WARNING: The new "default" location value is NOT the same as the old default location and would break an upgrade for an app that was using the old default value (0) on iOS." applied ONLY to iOS, not to Android.

Further, if I perform an adb backup of both versions of my app, I can see a different directory structure.

When backing up my old app version (using v0.7.10 of this plugin), I end up with 'apps/[package]/r/app_webview/databases/file__0/1'.  I can inspect this "1" with sqlitebrowser and see my data.

When backing up my new app version (using v2.1.2 of this plugin), I end up with BOTH ''apps/[package]/r/app_webview/databases/file__0/1' AND 'apps/[package]/db/[db name]'.  I can inspect both of those files, and see my previous data in "1" and my new data in "[db name]".

Is there a way to get the v2.1.2 of this plugin to use the same location as was used by v0.7.10 for Android devices?

If not, is there a way to migrate the database used by v0.7.10 to the location used by 'default' in v2.1.2?

Thank you.

**Comment by brody2consult** [comment]
> When backing up my old app version (using v0.7.10 of this plugin), I end up with 'apps/[package]/r/app_webview/databases/file__0/1'. I can inspect this "1" with sqlitebrowser and see my data.

This indicates to me that you app would have been using Web SQL to store the data.

I recommend that you use something like <https://github.com/dpa99c/cordova-sqlite-porter> to port the data to the new database file.

In case you need private support please contact <sales@litehelpers.net> for more information.

**Comment by brody2consult** [comment]
Closing for now. Still marked **doc-todo**, will be documented as a pitfall when I get a chance.
