### ISSUE TITLE
missing exec:SQLitePlugin.close

### ISSUE THREAD

**Issue by mit140888** [brody2consult/cordova-sqlite-storage#735]
Hi,
i am using cordova SQLite plugin for storing data.

Queries such as Create Table, Insert are not executing because of DB is not open properly.

In my console i am not getting OK as a response in next to the database name i.e. my.db.
even i am not getting "DB Opened" response.
its showing "new transaction is queued, waiting for open operation to finish".

please check screenshot as well for reference.

![issue](https://user-images.githubusercontent.com/3060753/34379244-5463c664-eb20-11e7-8755-3672fa60ae15.png)

**Comment by brody2consult** [comment]
It looks like the plugin was not installed correctly. Please read through the documentation and double-check your installation. Tools other than Cordova CLI are NOT supported for this plugin version.
