### ISSUE TITLE
Minimum Android SDK version?

### ISSUE THREAD

**Issue by Dizzzlectic** [brody2consult/cordova-sqlite-storage#737]
Hello,

What's the minimum SDK version required to run this plugin? I have no issues as long as I run SDK version 24 and above, however I'd like to be able to support at least API level 19/21.

Using the base Cordova HelloWorld example and this plugin on API level 19 and 21 results in the following error message being shown:

**Uncaught TypeError: Cannot read property 'openDatabase' of undefined**

The plugin is installed correctly and I've verified it by removing and re-adding the android platform multiple times.
https://i.imgur.com/Ofu9RND.png

Would appreciate help if possible.

**Comment by brody2consult** [comment]
The picture shows that you are using the wrong sqlite plugin version.

**Comment by Dizzzlectic** [comment]
Holy crap, I didn't even think of checking that. This is embarrassing.

Thanks for being a champ about it.

**Comment by brody2consult** [comment]
No worries, please report if you encounter any other issues.
