### ISSUE TITLE
THREAD WARNING: exec() call to SQLitePlugin.executeSqlBatch blocked the main thread

### ISSUE THREAD

**Issue by kozuch** [brody2consult/cordova-sqlite-storage#74]
I get following error for each db transaction with Cordova 3.3 and 3.5 running on Samsung Galaxy S3 mini and Android simulator:

07-03 16:03:57.004: W/PluginManager(20249): THREAD WARNING: exec() call to SQLitePlugin.executeSqlBatch blocked the main thread for 18ms. Plugin should use CordovaInterface.getThreadPool().

Can anyone help me?

Btw, I get a thread warning on every single plugin in my project... thus might not really be a fault of SQLitePlugin.

**Comment by mauricioac** [comment]
Still getting this using latest version.... :/
