### ISSUE TITLE
PouchDB allDocs by any keys return all docs

### ISSUE THREAD

**Issue by andig89** [brody2consult/cordova-sqlite-storage#743]
### Issue
allDocs with any keys return always all docs. Maybe it's a problem with pouchDB, see [this report](https://github.com/pouchdb/pouchdb/issues/7007#issuecomment-359165902).
I checked this example on cordova-sqlite-test with [pouchDB 6.4.1](https://cdn.jsdelivr.net/npm/pouchdb@6.4.1/dist/pouchdb.min.js), [pouchDB 6.3.4](https://github.com/pouchdb/pouchdb/releases/download/6.3.4/pouchdb-6.3.4.min.js) and [adapter](https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite). With v. 6.4.1 it's not work but with v. 6.3.4 it's work. Self and echo tests are ok. I will try find issue but maybe someone will be faster.

### Info
- Environment: (hybrid app - Cordova)
- Platform: (Android)
- Adapter: (Native by pouchdb.cordova-sqlite and cordova-sqlite-storage)
- Server: (Cordova)

### Reproduce
```
var DBApplication = new PouchDB('dbname', {
    adapter: 'cordova-sqlite',
    skip_setup: false,
    location: 'default'
});
DBApplication.put({
        _id: 'mydoc',
        title: 'Heroes'
    })
    .then(function(response) {
        DBApplication.put({
                _id: 'mydoc2',
                title: 'Heroes2'
            })
            .then(function(response) {
                DBApplication.allDocs({
                    include_docs: true,
                    keys: ['s']
                }).then(function(result) {
                    console.log(result);
                }).catch(function(err) {
                    console.log(err);
                });
            }).catch(function(err) {
                console.log(err);
            });
    }).catch(function(err) {
        console.log(err);
    });
```

**Comment by brody2consult** [comment]
Please raise this on `pouchdb-adapter-cordova-sqlite`
