### ISSUE TITLE
[LayoutConstraints] Unable to simultaneously satisfy constraints

### ISSUE THREAD

**Issue by SwethaEnixta** [brody2consult/cordova-sqlite-storage#744]
Hi @brodybits, 
I tested the plugin working fine, by creating an app & opening and accessing a database. After this, I added my own html files into the [Cordova Project] -> platform -> ios -> www folder. My index.html has a textbox with a search button which should take it to a new page, using window.location('newpage.html').The problem is, once I enter some text & hit search, it throws a lot of constraints issues in the logs, as attached. 
[XCode_Issue.txt](https://github.com/litehelpers/Cordova-sqlite-storage/files/1655469/XCode_Issue.txt)

====
After the logs, it loads the new page, but I do not see any of the processing output which was done before this page was loaded. 
Not sure which other plugin should I install or what layout constraints should be set as I am new to iOS XCode. 

Please help.

**Comment by brody2consult** [comment]
Not related to this plugin. Please ask on PhoneGap forum or StackOverflow.
