### ISSUE TITLE
How to connect to other android native app Database 

### ISSUE THREAD

**Issue by yasser-mas** [brody2consult/cordova-sqlite-storage#746]
I would like to connect to other android native application Database , 

I have created shared database in android native app and content provider 

I have created a permission and uses permission to ionic app 

I can access to database in ionic app from main activity before loadUrl(launchUrl);

by the below code :  

      contentResolver = getContentResolver();
      cursor = contentResolver.query(table_URI, mColumnProjection, "grade > 8", null, null);

      // here is the cursor to choose among the database columns one by one and adding contents of the columns in the string builder

      if(cursor != null && cursor.getCount() > 0)
      {
        StringBuilder stringBuilderQueryResult=new StringBuilder("");
        while (cursor.moveToNext()){
          stringBuilderQueryResult.append(cursor.getString(0)+" , "+cursor.getString(1)+" , "+cursor.getString(2)+"\n");
        }
        Toast.makeText(this, stringBuilderQueryResult.toString()  , Toast.LENGTH_LONG).show();

      }else{
        Toast.makeText(this,"No Content" , Toast.LENGTH_LONG).show();
      }

but I can't access to database from Ionic native sqlite

**Comment by brody2consult** [comment]
<https://github.com/phearme/cordova-ContentProviderPlugin> should be able to handle this case
