### ISSUE TITLE
Cannot read property 'openDatabase' of undefined if exitApp();

### ISSUE THREAD

**Issue by oman21** [brody2consult/cordova-sqlite-storage#750]
I am working on ionic 2, this error came when I open apps previously close apps used function exitApp(), but when I clear ram of my phone, apps work perfectly.

here i used code for open/create DB
`this.db = (<any>window).sqlitePlugin.openDatabase({name:'test.db', key: 'test', location: 'default'});`

my plugin

> cordova-plugin-backbutton 0.3.0 "Backbutton"
> cordova-plugin-device 1.1.4 "Device"
> cordova-plugin-facebook4 1.9.1 "Facebook Connect"
> cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
> cordova-plugin-googleplus 5.1.1 "Google SignIn"
> cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
> cordova-plugin-network-information 1.3.4 "Network Information"
> cordova-plugin-splashscreen 4.0.3 "Splashscreen"
> cordova-plugin-whitelist 1.3.1 "Whitelist"
> cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
> cordova-sqlcipher-adapter 0.1.11 "Cordova sqlcipher adapter"
> cordova-sqlite-storage 2.1.4 "Cordova sqlite storage plugin"
> es6-promise-plugin 4.1.0 "Promise"
> ionic-plugin-keyboard 2.2.1 "Keyboard"
> phonegap-plugin-push 1.10.5 "PushPlugin"
> uk.co.workingedge.cordova.plugin.sqliteporter 1.0.2 "sqlite porter"

**Comment by brody2consult** [comment]
Please post a simple, self-contained demo project and ask in cordova-sqlite-help .
