### ISSUE TITLE
Locaton attribute

### ISSUE THREAD

**Issue by DevillBuster** [brody2consult/cordova-sqlite-storage#753]
Hi, 
just wanted to know what options can be passed to the location attribute. Because in the whole documentation only thing i read is location: 'default'. Please guide me i want to save my database file in sdcard

**Comment by brody2consult** [comment]
> just wanted to know what options can be passed to the location attribute. Because in the whole documentation only thing i read is location: 'default'.

Already documented in <https://github.com/litehelpers/Cordova-sqlite-storage#opening-a-database>

> Please guide me i want to save my database file in sdcard

This is currently supported in <https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free>, available under GPL or commercial license terms, as documented at: <https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free#opening-a-database>

Flexible database location for all platforms will be part of cordova-sqlite-ext at some point in the future ref: <https://github.com/litehelpers/cordova-sqlite-ext/issues/43>

For priority feature development please contact <sales@litehelpers.net> for more information.
