### ISSUE TITLE
App submitted to MS Store says SQLite3.UWP.dll calls other .dlls that violate MS Store Certification requirements

### ISSUE THREAD

**Issue by bucktaylor** [brody2consult/cordova-sqlite-storage#758]
We included this library to enable our Cordova Windows app to work with SQL. We have it running only for windows, as iOS and Android are using webSQL (not my chioce). We are able to build and run it on ARM, x86 and x64 from VS-2017 with no issues we have seen. After testing, we submitted our app to the MS Store and got a certification rejection with this as the only issue:

> Error Found: The supported APIs test detected the following errors:

> API _CrtDbgReport in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _CrtDbgReportW in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API __stdio_common_vsprintf_s in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _cexit in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _configure_narrow_argv in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _crt_at_quick_exit in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _crt_atexit in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _except1 in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _execute_onexit_table in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _free_dbg in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _initialize_narrow_environment in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _initialize_onexit_table in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _initterm in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _initterm_e in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _localtime64_s in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _msize in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _register_onexit_function in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _seh_filter_dll in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _wmakepath_s in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _wsplitpath_s in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API free in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API malloc in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API qsort in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API rand_s in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API realloc in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API strcat_s in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API strcmp in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API strcpy_s in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API strlen in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API strncmp in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API wcscmp in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API wcscpy_s in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API wcslen in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ??0COMException@Platform@@Q$AAA@H@Z in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ??0NotImplementedException@Platform@@Q$AAA@XZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ??0Object@Platform@@Q$AAA@XZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?AlignedFree@Heap@Details@Platform@@SAXPAX@Z in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?Allocate@Heap@Details@Platform@@SAPAXII@Z in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?AllocateException@Heap@Details@Platform@@SAPAXII@Z in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?Free@Heap@Details@Platform@@SAXPAX@Z in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?GetActivationFactory@Details@Platform@@YGJPAVModuleBase@1WRL@Microsoft@@PAUHSTRING__@@PAPAUIActivationFactory@@@Z in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?GetIidsFn@@YGJHPAKPBU__s_GUID@@PAPAVGuid@Platform@@@Z in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?InitializeData@Details@Platform@@YAJH@Z in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?ReleaseTarget@ControlBlock@Details@Platform@@AAEXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?TerminateModule@Details@Platform@@YG_NPAVModuleBase@1WRL@Microsoft@@@Z in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?UninitializeData@Details@Platform@@YAXH@Z in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseAccessDeniedException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseCOMException@@YGXJ@Z in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseChangedStateException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseClassNotRegisteredException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseDisconnectedException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseFailureException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseInvalidArgumentException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseInvalidCastException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseNotImplementedException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseNullReferenceException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseObjectDisposedException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseOperationCanceledException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseOutOfBoundsException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseOutOfMemoryException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_WinRTraiseWrongThreadException@@YGXXZ in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API ?__abi_translateCurrentException@@YGJ_N@Z in vccorlib140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _CxxThrowException in vcruntime140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API __CxxFrameHandler3 in vcruntime140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API __std_type_info_destroy_list in vcruntime140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API __vcrt_GetModuleFileNameW in vcruntime140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API __vcrt_GetModuleHandleW in vcruntime140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API __vcrt_LoadLibraryExW in vcruntime140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API _except_handler4_common in vcruntime140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API memcmp in vcruntime140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API memcpy in vcruntime140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API memmove in vcruntime140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> API memset in vcruntime140d_app.dll is not supported for this application type. SQLite3.UWP.dll calls this API.
> 

> Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements. 
> How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Microsoft Store apps. Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these environments may pull in unsupported APIs. Retest your app in a release configuration, and with .NET Native enabled if applicable. See the link below for more information: 

[Alternatives to Windows APIs in Microsoft Store apps](http://go.microsoft.com/fwlink/?LinkID=244022). 

We are totally new to submitting a Cordova app to the Windows store, and are not really sure what to make of this. Any suggestions on how to proceed here?

Thanks - Buck.

**Comment by brody2consult** [comment]
My response is in <https://github.com/litehelpers/Cordova-sqlite-help/issues/43> (I suspect it needs Release build)
