### ISSUE TITLE
Cannot select data, function always return null

### ISSUE THREAD

**Issue by vinhloc1996** [brody2consult/cordova-sqlite-storage#759]
Hi, I have a function to select data for searching as below:
```
function searchActivity (keyword) {
    var result = null;
    myDB.transaction(function (tx) {
        var query = "SELECT * FROM Activity WHERE VolunteerActivityName LIKE '%" + keyword + "%'";
        tx.executeSql(query, [], function(tx, res) {
            if(res.rows.length != 0) {
                result = res.rows;
            }
        },
        function(tx, error) {
            alert('Search error: ' + error.message);
        });
    });

    return result;
}
```

It always returns the null result for me, I don't know where I was wrong but I run the sql command manually in `DB Browser for SQLite`, they return the result as I expectedly.
```
SELECT * FROM Activity WHERE VolunteerActivityName LIKE '%A%'
```
While the other CRUD functions run as I expected.

P/s: I've removed the condition of the search query, so it becomes a simple select query
`SELECT * FROM Activity`
and it doesn't return anything? I really don't know what happened to it. Detail function can be found here:
https://github.com/vinhloc1996/VolunteerActivity/blob/master/js/index.js

**Comment by brody2consult** [comment]
Answered in <https://github.com/litehelpers/Cordova-sqlite-help/issues/38>, with your JavaScript code marked as follows to achieve JavaScript highlighting:

    ```js
    // ...
    ```

This issue is marked as a doc-todo pitfall, to be documented more clearly when I get a chance.
