### ISSUE TITLE
Cannot create trigger with executeSql() command

### ISSUE THREAD

**Issue by longdangduy** [brody2consult/cordova-sqlite-storage#760]
Hi,

I am using Cordorva-Sqlite-Storage ver 2.2.0.
In my iOS application, I tried to create a trigger like below:
<code>
var table_name = tableList[i];
var createTrigger = 'CREATE TRIGGER TRIGGER_CREATE_TABLE '+table_name+' AFTER INSERT ON '+table_name+' BEGIN INSERT INTO TABLE_LOG (NEW.idName, null) VALUES (); END;';
tx.executeSql(createTrigger, [], null, null);
</code>
This sql command run successful.
After that, I tried to insert data to table_name table, but trigger not work.
And I also checked existence of trigger in DB by command: 'SELECT * FROM sqlite_master WHERE TYPE ="trigger"'.
But number record is 0.

To check my createTrigger command, I tried to run in DB by using [DB Browser for SQLite], and it's successful, with existence trigger in DB.

Could you please help me to check and give me your opinion?

Thank you very much for your kind help.
Best regards,

**Comment by brody2consult** [comment]
Please make a more complete demo program and post it with your question in cordova-sqlite-help.
