### ISSUE TITLE
ALTER TABLE not working

### ISSUE THREAD

**Issue by nive745** [brody2consult/cordova-sqlite-storage#761]
I was tried alter table field add but not working

this.db.transaction(
            function(tx) {
                       tx.executeSql("ALTER TABLE interview_video ADD COLUMN homecluboption VARCHAR(255)', [], function() {
                            console.log('alter success');
                        }, function(tx, error) {
                            console.log('SELECT error: ' + error.message);
                        });
                }
        );

**Comment by brody2consult** [comment]
Please ask in cordova-sqlite-help, with a more complete demo program, with proper indentation and JavaScript highlighting as in the following example:

    ```js
    // ...
    ```
