### ISSUE TITLE
How to use with phonegap if your plugin does not support desktop browser?

### ISSUE THREAD

**Issue by Benoit1980** [brody2consult/cordova-sqlite-storage#762]
Hello,

I am a little lost here.
I have installed your plugin but I cannot test my ajax calls in the chrome browser because your plugin does not support a desktop browser.
My question is...how can I develop on phonegap and check all my Ajax calls using your plugins to save and retrieve data if I am not able to analyze the calls in the chrome dev tools?

Thank you.

**Comment by brody2consult** [comment]
How to develop and test with desktop browser platform is documented in <https://github.com/litehelpers/Cordova-sqlite-help/issues/39> (to be documented in README.md when I get a chance). If this does not answer your question then please explain in more details.

**Comment by Benoit1980** [comment]
Thank you for the reply. I did find it a bit tricky to use. I ended up using "pouch", much easier.
https://pouchdb.com/

Thanks again for your feedback.
