### ISSUE TITLE
Failing to open/create a database.

### ISSUE THREAD

**Issue by mountainclimbing** [brody2consult/cordova-sqlite-storage#765]
I keep getting failing to open database with a reference being made to Cordova but maybe it is because of the SQLite plugin. See my code below

`			<!DOCTYPE html>
			<html>
				<head>
					<meta charset="utf-8">
					<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
					<title>SQLLite DB App</title>
					  <script type="text/javascript" src="cordova.js"></script>
						<script type="text/javascript" src="SQLitePlugin.js"></script>
					<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
					<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
					<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
			<script type="text/javascript">

				document.addEventListener("deviceready", onDeviceReady, false);
				var db=null;
				
				function onDeviceReady() {
				 //alert("device ready");
					db = window.sqlitePlugin.openDatabase({
					name: "ivolunteer.db",
					location: "default",
						});
						//db = window.openDatabase("ivolunteer","1.0","ivolunteer_db",5*1023*1024);
						db.transaction(createDB, errorCB, successCB);
						}
					
				function createDB(tx) {
					 tx.executeSql('CREATE TABLE IF NOT EXISTS activitytbl (ActivityID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,ActivityName TEXT,VolunteerName TEXT,Location TEXT,ActivityDate TEXT,ActivityTime TEXT)');
				}
				
				function errorCB(err) {
					alert("Error processing SQL: "+err.message);
				}
				
				function successCB() {
					//alert("success!");
				}

			  function insertDB(tx) {
					 alert("Data reached at insertDB");
						var vactivity = $('[name="activity"]').val();
						var vname = $('[name="name"]').val();
						var vlocation = $('[name="location"]').val();
						var veventdate = $('[name="eventdate"]').val();
						var veventtime = $('[name="eventtime"]').val();
						var sql = 'INSERT INTO activitytbl(ActivityName,VolunteerName,Location,ActivityDate,ActivityTime)							                                     VALUES(?,?,?,?,?)';
						tx.executeSql(sql, [vactivity,vname,vlocation,veventdate,veventtime], sucessQueryDB, errorCB);
						}
					 
			   function sucessQueryDB(tx) {     
							tx.executeSql('SELECT * FROM activitytbl', [], renderList, errorCB);
						}

				function renderList(tx,results) {
							var htmlstring = '';
							 
							var len = results.rows.length;
							 
							for (var i=0; i<len; i++){
								htmlstring += '<li>' + results.rows.item(i).ActivityName + '</li>';
								 
							}
							 
							$('#resultList').html(htmlstring);
							$('#resultList').listview('refresh');
							 
							 
						}
			 
				function submitForm() {
							db.transaction(insertDB, errorCB);
							$.mobile.changePage( "#pageb", { reverse: false, transition: "slide" } );
							return false;
						}
				</script>
				</head>
				<body>
					<div data-role="page" id="pageone">
			  <div data-role="header">
			<a href="#pageb" data-role="button">View Records</a></div>
			  
			  <div data-role="content">
			  
				<form id="Form"  method="POST" onSubmit="return submitForm()" data-ajax="false">
				
				
				<label for="name"><b>Activity </b></label>
				<input type="text"  name="activity"  id="activity" required /><br>
				
				 <label for="name"><b>FullName:</b></label>
				<input type="text"  name="name" id="name" required /><br>

				<label for="Location"><b>Place</b></label>
				<input type="text" name="location" id="location" /><br>
				
				<label for="eventdate"><b>Date: </b></label>
				   <input type="date"  name="eventdate" id="eventdate" required /><br>
			 
			  
				<label for="name"><b>Actual Time</b></label>
				<input type="text" name="eventtime" id="eventtime" placeholder ="hh:mm" /><br>
				
				<input type="submit" value="Submit Details" id="insert" name="insert" />
				
				</div>
			</form>
				</div>
			  
			  <div data-role="footer" data-position="fixed">
			 
				  </div>
			</div>

			</div> 
			  
			  <div id="pageb" data-role="page" data-add-back-btn="true">
					<div data-role="header">
						  <a href="#pageone" data-role="button">Back</a><h1>Records</h1>
					</div>
						<div data-role="content"> 
							<div id="output"></div>
							 
							<ul data-role="listview" id="resultList">
							</ul>
								 
						</div>
					<div data-role="footer" data-position="fixed">
			  
					</div>
			  </div>
				   
			</body>
			</html>
`

**Comment by brody2consult** [comment]
My apologies for the delay. Please try using [brodybits / cordova-sqlite-storage-starter-app](https://github.com/brodybits/cordova-sqlite-storage-starter-app) before asking this kind of a question. I would also prefer to answer this kind of question in [litehelpers / Cordova-sqlite-help / issues](https://github.com/litehelpers/Cordova-sqlite-help/issues).

**Comment by brody2consult** [comment]
Other recommended tutorial resources added in #609
- <https://codesundar.com/lesson/cordova-sqlite-storage/>
- <http://www.developerin.net/a/75-Code-Snippet/115-CRUD-Operation-using-Phonegap-and-SQLite>
