### ISSUE TITLE
Leer base de datos ya creada

### ISSUE THREAD

**Issue by faustox30** [brody2consult/cordova-sqlite-storage#767]
Hola a todos tengo un problema con mi codigo, estoy tratando de leer una base de datos ya existente con phonegap, ya llevo un buen rato intentando y siempre obtengo el mismo error: no such table, a alguien mas le ha sucedido?, quedo pendiente de cualquier comentario y coloco el copdigo que estoy utilizando. 

 var db = null;
document.addEventListener('deviceready', function() {
db = sqlitePlugin.openDatabase({name:"verpoffline5.db", location:"default", createFromLocation: 1})
if(db != null){
    alert("Base abre")
}else{
    alert("Error leer base")
}

        $("#ejecucion").click(function(event){
         event.preventDefault();

db.executeSql('SELECT count(*) AS mycount FROM maestroarticulosweb', [], function(rs) {
    console.log('Record count (expected to be 2): ' + rs.rows.item(0).mycount);
    alert(rs.rows.item(0).mycount)
  }, function(error) {
    console.log('SELECT SQL statement ERROR: ' + error.message);
        alert(error.message)
  });

        })            

                });

**Comment by brody2consult** [comment]
Please ask in cordova-sqlite-help, with English translation would be appreciated.
