### ISSUE TITLE
Ending support for old Android versions

### ISSUE THREAD

**Issue by brody2consult** [brody2consult/cordova-sqlite-storage#771]
Definite:
- Android pre-4.0 (no supported by recent version of cordova-android ref: [[1]](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#requirements-and-support), does not seem to be supported by recent version of Android Studio/SDK or NDK)

Extremely likely:
- Android 4.0 (does not seem to be supported by recent version of Android Studio/SDK; support for Android 4.0 was dropped by cordova-android@6 ref: [[1]](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#requirements-and-support))

Very likely:
- Android 4.1-4.3 (Android pre-4.4 support was dropped by cordova-android@7 ref: [[1]](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#requirements-and-support))

_To be partially maintained as described in comment below (<https://github.com/litehelpers/Cordova-sqlite-storage/issues/771#issuecomment-400843613>):_
- Android 4.4
- armeabi CPU (seems to be replaced by armeabi-v7a and arm64-v8a, does not seem to be supported by Android 5.0 and greater)

_P.S. Android version supported by Cordova depends on Cordova version ref: <https://cordova.apache.org/docs/en/latest/guide/platforms/android/>_

Purpose is to reduce burden of testing needed and special cases to be maintained. Feedback would be highly appreciated.

[1] <https://cordova.apache.org/docs/en/latest/guide/platforms/android/#requirements-and-support>

**Comment by jacobg** [comment]
Feedback: Continued support for Android SDK 19 (4.4) would be highly appreciated.

**Comment by brody2consult** [comment]
Thanks @jacobg for the feedback, hoping to receive more from the user community.

**Comment by csabbey** [comment]
@brodybits More of the same feedback - Android 4.4 is still over 10% of Android devices, so supporting that would be appreciated.

**Comment by juristr** [comment]
Definitely Android 4.4 support 🙏 . We're still having quite some customers on that platform

**Comment by ddegasperi** [comment]
@brodybits I agree, support for Android 4.4 is very important to me

**Comment by CarlosAyala** [comment]
Hi,
We are working in a App with need working on Android 4.4+.
¡Please support it!

**Comment by jacobg** [comment]
FYI, Android 4.4 is still installed on 10.3% of devices, so it's still significant:

https://developer.android.com/about/dashboards/

**Comment by brody2consult** [comment]
Thanks to all for the feedback. I would like to plan the following compromise approach for Android 4.4 & old armeabi CPU:

Build for the old armeabi CPU, as needed to support Android 4.4, will be made with some newer features missing such as FTS5, JSON1, BASE64, and possibly some other features such as FTS3, FTS4, and REGEXP.

Support for the old armeabi CPU increases package size and requires additional testing, hopefully can be dropped sometime later in the future.

**Comment by MikeDimmickMnetics** [comment]
The lowest supported version for our line-of-business app is still Jellybean (Android 4.1). Our customers use rugged devices with integrated barcode scanners e.g. Zebra TC51. A number still have Motorola Solutions MC40 with Jellybean. These customers expect at least 5 years of lifespan from these device purchases, and Motorola didn't offer a KitKat upgrade until relatively late in its life (February 2016). Upgrading the OS to KitKat or Lollipop is a big step that so far the affected customers have been resisting.

I realise that you can't continue to support old versions forever, but it would certainly be useful if possible.

**Comment by MikeDimmickMnetics** [comment]
Just an update to my previous comment: we have now dropped support for Android 4.1 Jellybean, as it was becoming very difficult to support (e.g. our jsHybugger license has expired and the company seems to have disappeared!)

Our minimum supported version is now Android 4.4 KitKat. The few customers we still have on Jellybean will have to upgrade to KitKat or later when they take a new release of our software.

**Comment by brody2consult** [comment]
Thanks to all for the feedback in 2018. This will now be tracked as part of #922. I would like to drop Android pre-5.0 and maybe pre-5.1 in the near future since they will be dropped by Cordova itself (<https://github.com/apache/cordova-android/pull/915>) and I would like to drop the burden of testing on the deprecated `armeabi` CPU (which was superseded by `armeabi-v7a`). I would like to keep any further discussion in #922 now.

**Comment by jacobg** [comment]
Thanks @brodybits for your continued support for this plugin.

I was the first person to reply to this issue in 2018 to plea for Android 4.4 support, but my app has since dropped support for Android 4.4. The current minimum version is Android 5.0. The main reason it even supports Android 5 is because Amazon was making Fire tablets as recently as 2018 based on Android 5.1.1.

So I'm totally fine with this plugin requiring Android 5.1.
