### ISSUE TITLE
Drop Android x86_64 build

### ISSUE THREAD

**Issue by brody2consult** [brody2consult/cordova-sqlite-storage#772]
I would like to drop the Android NDK build for x86_64 CPU. NDK x86 (32-bit) build will also work on x86_64 CPU. One less CPU to test NDK builds on. (My understanding is that Android x86 and x86_64 CPU builds are generally used for the emulator.)

Objections and any other feedback would be very welcome, I would be happy to reconsider if there are enough objections.

**Comment by Dizzzlectic** [comment]
You are absolutely right. x86 and x86_64 are mainly used for emulators having different optimizations depending on CPU architecture.

**Comment by brody2consult** [comment]
Keeping x86_64 build for now
