### ISSUE TITLE
Strict data comparison setting?

### ISSUE THREAD

**Issue by nostop8** [brody2consult/cordova-sqlite-storage#775]
Hi!

We are using SQLite plugin as a storage for our hybrid application. Its performing very good on all devices. Recently I found out that it is using strict data comparison in the query condition on MacOS (OSX), but it does not do that on Windows, Android and iOS, which is strange for me. I wonder if there's any setting for this? I could not find it. Can anyone help please?

My query looks like this:
`SELECT * FROM records WHERE field1 = 0`

The data stored inside the `field1` is string (not number), e.g. `"0"`, `"1"`. So, as result on MacOS I get no results. There is no problem to update query to properly for strict comparison. But because application is pretty big with lots of queries, I'm afraid there will be lots of bugs which we have to catch for a long time on MacOS. The simpler solution for us would be just to turn off this strict comparison everywhere.

Cordova SQLite Storage version: 2.3.0
MacOS version: 10.13.4

**Comment by brody2consult** [comment]
My apologies for the delay. It would be extremely helpful if you can show some sample data where you see this issue on macOS.

**Comment by brody2consult** [comment]
Closing due to lack of response. Please feel free to demonstrate the issue with sample data here or in a new issue if you like.
