### ISSUE TITLE
Visual studio 2017 fails build when cordova-sqlite-storage plugin is installed

### ISSUE THREAD

**Issue by pantelisGeo90** [brody2consult/cordova-sqlite-storage#777]
I guess this has been answered multiple times before and i apologise. I've found some issues but the answer in most of them is to run `cordova-sqlite-storage-starter-app`.  

I have installed on my pc `VS Community 2015 v.14.0.25431.01 Update 3` and `VS Community 2017 v.15.6.6`.

When i am using MS VS2017 Community I am getting the below error whenever I install the `cordova-sqlite-storage` plugin into my project (even a brand new project) and build (Debug | Windows-x86 | Local Machine):
_>MSBUILD` : cordova-build error : Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe: Command failed with exit code 1_

I've also used the project mentioned above but same issue when i try to build.
The project will continue failing even if i uninstall the plugin.

When i try to: 
**->** create a cordova app with VS2015 (throws an error at first but if you open `.jsproj` with notepad -> under one of the `PropertyGroup` find `TypeScriptCompileOnSaveEnabled` and paste below  that:  `<TypeScriptToolsVersion>2.3</TypeScriptToolsVersion>`)  
**->** add the `cordova-sqlite-storage` plugin
it will build and run the project.

If try to open the solution with VS2017 (after i update the `.jsproj` - change the VS version from 14 to 15 etc) it will fail building with this error:
_>MSBUILD : cordova-build error : Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe: Command failed with exit code 1_

So i guess it's something to do with VS2017 or the registry keys on my pc? I've read quite a few posts and tried some of the suggestions with no luck. Very weird issue. 
I wonder if this happens with `VS Professional 2017` or `VS Enterprise 2017`.
I also wonder if this issue stops if i also install VS2013? (maybe that's not needed though)

**Comment by brody2consult** [comment]
Can you please try with <https://github.com/brodybits/cordova-sqlite-storage-starter-app> and try Release build on Visual Studio 2017 GUI?

I also use Visual Studio 2017 Community Edition for testing, will try with the latest release of VS 2017 when I get a chance. I do very limited testing with command line tools, also do NOT support this plugin version with Visual Studio 2015.

**Comment by pantelisGeo90** [comment]
I've created a new cordova project on a different machine (with MS VS Professional 2017) (same steps with previous pc) and added the code from `cordova-storage-starter-app` and it builds/works fine. All tests passes.
Since you also run your projects on a VS Community 2017 then i guess the issue might be with my pc or registry keys on my pc or my VS installation. I'll repair VS and try again tonight.
Thanks for your response.

**Comment by pantelisGeo90** [comment]
Repaired VS2017 and that fixed the problem. I've spent too much time on this. :S
Awesome work btw. :thumbsup:
