### ISSUE TITLE
openDatabase Error: exec proxy not found for :: SQLitePlugin :: close

### ISSUE THREAD

**Issue by GuilhermeLessa** [brody2consult/cordova-sqlite-storage#783]
When executing echoTest this error is shown:
**Error: exec proxy not found for :: SQLitePlugin :: close**

I know it does not run in the browser, but the echoTest should be done in the right browser?

I'm using Monaca with OnsenUI, could this be messing up? I've tried a clean project, but the same thing happens.

**Comment by GuilhermeLessa** [comment]
CONSOLE LOG PRINT SCREEN:  https://ibb.co/hUmcdn

**Comment by GuilhermeLessa** [comment]
ok, it only works on android.
But I discovered something that the documentation does not mention. You need to create the .db file in the root. Please document this!

**Comment by brody2consult** [comment]
@GuilhermeLessa thanks for reporting. Unfortunately I do not really understand what you tried to do here. A code snippet would really help, looks like it does need to be documented as a pitfall.

**Comment by brody2consult** [comment]
Reopening for now. Hope we can get this cleared by for the next major release (#773).

**Comment by GuilhermeLessa** [comment]
Sorry, that was a bad coincidence. There is no need for .db file, my mistake. 
This issue was resolved in #784

I generated a lot of junk here.

**Comment by brody2consult** [comment]
Guess we can close this then. Please report if you encounter this or any other problem in the future.
