### ISSUE TITLE
database can't open version@2.3.2

### ISSUE THREAD

**Issue by zrain** [brody2consult/cordova-sqlite-storage#794]
I update this plugin to version@2.3.2 

what ever i execute any statement, it always prompt 
‘new transaction is queued, waiting for open operation to finish’。

and the openDatabase successCallback can't execute.

![image](https://user-images.githubusercontent.com/6274220/41894987-5ac82a2e-7953-11e8-9942-567cb7d465d8.png)

when i back version@2.3.1

it's work.  the openDatabase successCallback can execute.

![image](https://user-images.githubusercontent.com/6274220/41895268-258418f4-7954-11e8-9d85-99d8b6da5f68.png)

**Comment by brody2consult** [comment]
The only change in 2.3.2 other than test & documentation was logging fixes. This sounds like an installation problem.

In case of doubts I suggest you start with <https://github.com/brodybits/cordova-sqlite-storage-starter-app> and try one thing at a time until you can see what does and does not work right.

There is also no information that can help anyone else investigate the issue.
