### ISSUE TITLE
Question: Min iOS SDK and Android version

### ISSUE THREAD

**Issue by hooliapps** [brody2consult/cordova-sqlite-storage#803]
Hello,

Can you give me please the min iOS SDK version (9.0 ?) and Android (21) ?

**Comment by brody2consult** [comment]
Answer is in <https://github.com/litehelpers/Cordova-sqlite-storage#announcements>.

Please ask this kind of question in <https://github.com/litehelpers/Cordova-sqlite-help/issues> if the answer is not clear enough.
