### ISSUE TITLE
Issue is nested for loop

### ISSUE THREAD

**Issue by ajay92x** [brody2consult/cordova-sqlite-storage#804]
for loop does not wait for the db.executeSql to complete
Following code which I'm using and it always execute the INSERT query even though the same id exist. Not even once it execute the UPDATE command.

for (let gparent = 0; gparent < array.length; gparent++) {
              for (let parent = 0; parent < array[gparent].innerArray.length; parent++) {
                  for (let child of array[gparent].innerArray[parent]) {
		 db.executeSql('SELECT * FROM tableName WHERE id = ?', [child.id]).then(re => {
                      if (re.rows.length > 0) {
                        for (let i = 0; i < re.rows.length; i++) {
                          console.error(JSON.stringify(re.rows.item(i)));
                        }
                        //data update section
                        db.executeSql('UPDATE tableName SET name = ? WHERE id = ?', [child.name, child.id])
                          .then((re2) => {
                            console.log('Updated to local database', re2);
                          })
                          .catch(e => console.log(e));
                      } else {
                        //data insert section
                        db.executeSql('INSERT INTO tableName(id, name) VALUES(?, ?)', [child.id, child.name])
                          .then((re2) => console.log('Inserted in Table', re2))
                          .catch(e => console.log(e));
                      }
                    }).catch(e => console.log(e));
		}
 	}
}

**Comment by brody2consult** [comment]
API is asynchronous, please read through the documentation to get a better understanding. Please ask this kind of question in cordova-sqlite-help, use proper indenting in JavaScript code, and format JavaScript code as follows to show proper highlighting:

    ```js
    // your JavaScript code here
    ```
