### ISSUE TITLE
i can't create tables

### ISSUE THREAD

**Issue by yushinarch** [brody2consult/cordova-sqlite-storage#805]
i am having a problem when i run this command

db.executeSql('create table danceMoves(name VARCHAR(32))', {})
      .then(() => console.log('Executed SQL'))
      .catch(e => console.log(e));

i get the an error

{
	"resource": "/home/user/Desktop/projectname/src/providers/database/database.ts",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type '{}' is not assignable to parameter of type 'any[]'.\n  Property 'length' is missing in type '{}'.",
	"source": "ts",
	"startLineNumber": 57,
	"startColumn": 79,
	"endLineNumber": 57,
	"endColumn": 81
}

i am using rxjs 6.2.

**Comment by CST-Lucas** [comment]
https://stackoverflow.com/questions/51524962/the-argument-of-type-is-not-attributable-to-the-parameter-of-type-any

**Comment by brody2consult** [comment]
Agreed with @CST-Lucas that you should not have used `{}` in the db.executeSql call.

It is not clear to me what library you are using, such as Ionic-native, sql-promise-helper, or maybe something else? I think this is really important when asking for help.

I would prefer this kind of question on cordova-sqlite-help, closing here.

**Comment by kevinpallado** [comment]
I have also the same problem above. The link CST-Lucas provided is not available, I just solved the issue removing the {} in the db.executeSql. SQlite plugin is coming from here [here](https://ionicframework.com/docs/native/sqlite/) any answer why it worked when removing the {}
