### ISSUE TITLE
Dead links litehelpers

### ISSUE THREAD

**Issue by peterennis** [brody2consult/cordova-sqlite-storage#814]
![capture392](https://user-images.githubusercontent.com/140737/44942468-94d42280-ad66-11e8-8f03-8b1b303d0410.png)
![capture391](https://user-images.githubusercontent.com/140737/44942469-94d42280-ad66-11e8-99a5-f4fd055d4081.png)
![capture390](https://user-images.githubusercontent.com/140737/44942470-94d42280-ad66-11e8-9418-cb54534e2548.png)

**Comment by brody2consult** [comment]
Thanks @peterennis

I hope to resolve this within the next week or so.

Someone else reported this issue privately, all further status will be communicated here.

**Comment by brody2consult** [comment]
litehelpers.net is live again, thanks!
