### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by jlagunapkf** [brody2consult/cordova-sqlite-storage#827]
Hi!

I will try to do a transaction, and console report the following error

```
SQLitePlugin.js:461 Uncaught TypeError: Cannot read property 'type' of undefined
    at Object.mycb [as success] (SQLitePlugin.js:461)
    at Socket.<anonymous> (app-host.js:131)
    at Socket.Emitter.emit (socket.io.js:4)
    at Socket.onevent (socket.io.js:4)
    at Socket.onpacket (socket.io.js:4)
    at Manager.<anonymous> (socket.io.js:4)
    at Manager.Emitter.emit (socket.io.js:4)
    at Manager.ondecoded (socket.io.js:3)
    at Decoder.<anonymous> (socket.io.js:4)
    at Decoder.Emitter.emit (socket.io.js:3)
```

This error thow when i call this transaction

```
var db = null;
        db = (window.cordova.platformId === 'browser') ?
            window.openDatabase('HelpAPPDataBase', '1.0', 'Data', 2 * 1024 * 1024) :
            window.sqlitePlugin.openDatabase({ name: 'HelpAPPDataBase.db', location: 'default' });


        db.transaction(function (tx) {
            tx.executeSql('CREATE TABLE IF NOT EXISTS Users (UserId, Password)');
        }, function (error) {
            console.log('transaction error: ' + error.message);
        }, function () {
            console.log('transaction ok');
        });
```

someone help me please?

**Comment by brody2consult** [comment]
It looks like something else is going on in your program. It would be great if you could make a demo based on <https://github.com/brodybits/cordova-sqlite-storage-starter-app> or <https://github.com/brodybits/cordova-sqlite-test-app>.

**Comment by Siko91** [comment]
I think I figured out the problem.
It isn't about the project or the code,
It is about where it runs.

When the Sqlite code in my app runs on android it works.
When it runs on a simulated android in browser, it doesn't work and I get the exact same error.

Is the browser simulation not supported?

**Comment by brody2consult** [comment]
The browser platform is not supported by this plugin. This is already documented. Closing now.
