### ISSUE TITLE
Update sqlite version to ≥3.25.x for window functions

### ISSUE THREAD

**Issue by jdanbrown** [brody2consult/cordova-sqlite-storage#828]
Window functions were added in 3.25.0:
- https://www.sqlite.org/changes.html
- https://www.sqlite.org/windowfunctions.html

These are very useful, and they're usually difficult to emulate using other constructs (e.g. group by). I'd love to be able to use them in mobile sqlite.

Example: select the top 3 scoring users per region
```sql
select *
from (
  select
    *,
    row_number() over (partition by region order by score desc) as i
  from users
)
where i <= 3
```

(Thanks for all your great work!)

**Comment by brody2consult** [comment]
May be in a new release ref: #773, #687. This would need to be done in sql.js which will be used for browser platform support as discussed in #576.

**Comment by brody2consult** [comment]
Closing in favor of SQLite 3.26.0 update to resolve a known vulnerability (#837).

> (Thanks for all your great work!)

You are welcome, thanks for the kind word.
