### ISSUE TITLE
Could not open database Visual Studio 2015

### ISSUE THREAD

**Issue by GuilhermeLessa** [brody2consult/cordova-sqlite-storage#851]
I have try open database without success.

Visual Studio 2015 on Windows 10
Run debug x64 on windows 8.1
Cordova 8.1.6 with windows platform 6.0.1

cordova-sqlite-storage 3.0.0
cordova-sqlite-evcore-extbuild-free 0.9.10 

<img src="https://i.ibb.co/9WbFYWk/open-db.png">

`open db name: test.db at full path: C:\Users\Guilherme\AppData\Local\Packages\br.com.tiempresarial.ticorporativo_bzbj8h50hftv4\LocalState\test.db`  

### but folder LocalState is empty.

Output:
`'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/2.0)'. 
Exception was thrown at line 126, column 7 in ms-appx://br.com.tiempresarial.ticorporativo/www/plugins/cordova-sqlite-storage/src/windows/SQLite3-WinRT-sync/SQLite3JS/js/SQLite3.js
0x800a1391 - Erro em tempo de execução do JavaScript: 'SQLite3' não está definido
Exception was thrown at line 19, column 5 in ms-appx://br.com.tiempresarial.ticorporativo/www/plugins/cordova-sqlite-storage/src/windows/SQLite3-WinRT-sync/SQLite3JS/js/SQLite3.js
0x800a139e - Erro em tempo de execução do JavaScript: Error creating an SQLite database connection.
Exception was thrown at line 7, column 5 in ms-appx://br.com.tiempresarial.ticorporativo/www/js/prodES5/base/log.js
0x800a138f - Erro em tempo de execução do JavaScript: Não é possível obter a propriedade 'executeSql' de referência indefinida ou nula
Exception was thrown at line 47, column 5 in ms-appx://br.com.tiempresarial.ticorporativo/www/js/prodES5/init.js
0x800a1391 - Erro em tempo de execução do JavaScript: 'ons' não está definido
`

### Self test on console:
<img src="https://i.ibb.co/BcWwV14/db-error-self-test.png">

### A simple open database transaction test
<img src="https://i.ibb.co/ZfpN3Fj/db-error-opentest.png">

Any order that I should run or install things? Same clean or rebuild?

**Comment by brody2consult** [comment]
I see two issues in the description:

- Installation and use of multiple sqlite plugins is not tested and not supported. This should be considered "undefined behavior"; possible consequences may include build failure, crashing, database corruption, and other possible form of data loss.
- Visual Studio 2015 is not supported by this plugin version. It may be possible for someone to get it to work but I have not really tested it. Visual Studio 2015 is supported by cordova-sqlite-legacy; I cannot say for sure how much longer I would continue supporting critical updates for Visual Studio 2015.

Closing for now as invalid, with **doc-todo** label.
