### ISSUE TITLE
Windows App Certification failed VS 2017 

### ISSUE THREAD

**Issue by alikahwaji** [brody2consult/cordova-sqlite-storage#853]
Hi,

I'm developing a cordova app using VS 2017 community version, after struggling to get a release build I'm facing another problem passing the certification kit and the errors is following : 

Binary analyzer Error Found: The binary analyzer test detected the following errors: File SQLite3.UWP.dll has failed the SafeSEHCheck check. File SQLite3.UWP.dll has failed the WXCheck check.
Error Found: The supported APIs test detected the following errors: API _CrtDbgReport in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API. API _CrtDbgReportW in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API. API __stdio_common_vsprintf_s in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API. API _cexit in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API. API _configure_narrow_argv in ucrtbased.dll is not supported for this application type. SQLite3.UWP.dll calls this API.

Thanks in advance.

**Comment by brody2consult** [comment]
My apologies for the delay. Due to the lack of support from Visual Studio I am no longer actively supporting app store builds.

**Comment by alikahwaji** [comment]
No worries, Thanks for the reply.
