### ISSUE TITLE
The query queue with the database turned off for: db.sqlBatch, db.executeSql

### ISSUE THREAD

**Issue by ckamil** [brody2consult/cordova-sqlite-storage#854]
Hello,

in the application i am working on, the copy of the database is sent to the server once a day.
While the db file is being sent, the database is turned off, however it sometimes happens that a process running in the background tries to save something in it.

In the case of calling the query with the database turned off using the db.transaction and tx.executeSql methods,  the queries get queued - I get the notification saying: "new transaction is queued, waiting for open operation to finish". After opening the database, all the queued queries are performed correctly.

However, in the case of using db.sqlBatch and db.executeSql with the database turned off, I always get the error: "database not open".

Is there a parameter for these methods that allows to queue the queries?

**Comment by brody2consult** [comment]
> in the application i am working on, the copy of the database is sent to the server once a day.
> While the db file is being sent, the database is turned off, however it sometimes happens that a process running in the background tries to save something in it.

I do not really support this kind of usage.

If you try to copy a file while a process tries to save data, there is risk of a corrupted file.

Everything else you describe is by design.
