### ISSUE TITLE
Statement while the app is in the background goes sleep after 3/4 minutes on Android

### ISSUE THREAD

**Issue by LucaTrip** [brody2consult/cordova-sqlite-storage#857]
I need to save data both in the foreground and in the background. In foreground it works. In the background, after a few minutes it stops working and resumes the task that went to sleep as it returns to the foreground. I disabled the **battery optimization** and installed the **cordova-plugin-background-mode** plugin but nothing has changed. 
This is the snippet that goes to sleep

```
this.DB.transaction(tx => {
    tx.executeSql('INSERT INTO points2 VALUES (?,?,?,?,?,?,?,?,?,?,?)', tempPoints, (tx, resultSet) => {
        console.log("batch insert in points", resultSet);
      }, (tx, err) => {
        console.log("error to batch insert in points", err);
      });
}, err => {
   console.log("TRANSACTION -> ERROR TO SAVE LOCAL DATA", err);
   this.isDBAccessible = false;
}, succ => {
   console.log("TRANSACTION -> SAVE LOCAL DATA");
});

```
And the DB is initialized like this
```
this.DB = window.sqlitePlugin.openDatabase({name: 'whip-db', location: 'default'}, db => {
   console.log("DATABASE create/open", db);
   resolve();
}, err => {
  console.log("error to open database", err.message);      
});
```
**INFOS**
Cordova-platform -> 7.1.4
Ionic -> 3.9.2
cordova-sqlite-storage -> 3.2.0
Test device -> Samsung s8, Android 9

**Comment by brody2consult** [comment]
This looks like an issue between Android and Cordova. A [mvce](https://stackoverflow.com/help/mcve) demo project would be helpful.

**Comment by AleRohvt** [comment]
Hello, I add myself to the discussion because I will have to implement the plugin and make it work in the background. are there any news?

**Comment by brody2consult** [comment]
As I said before this really looks like an issue between the Android OS and Cordova and a [mvce (1) demo](https://stackoverflow.com/help/mcve) would be extremely helpful.

At this point I will just say that working in the background is not supported by this plugin.

Closing with a **doc-todo** label.

[1] <https://stackoverflow.com/help/mcve>

**Comment by brody2consult** [comment]
To clarify this further, this plugin is not tested with this kind of "background mode" and I would say that any attempt to do this kind of thing would result in undefined behavior. I would like to add reference to some things documented in <https://github.com/katzer/cordova-plugin-background-mode#store-compliance>:

> Infinite background tasks are not official supported on most mobile operation systems

and

> Use the plugin by your own risk!

**Comment by shamilovtim** [comment]
Hi @brodybits I was just wondering if there's any chance that maybe running for example the other plugin (cordova-sqlite-express-build-support) with a different kind of driver might yield background compatibility? As the other users have mentioned, Cordova + Android sleeps the default SQLite / WebSQL db after about 5 minutes. I find this very odd because there are many native plugins (and native apps themselves) which use SQL in the background. What would it take to bring SQL background compatibility into one of these plugins? Would you be open to a PR?

Also though I'd page @christocracy since he's familiar with the subject matter as well.

**Comment by brody2consult** [comment]
@shamilovtim you could try the `androidDatabaseProvider: 'system'` setting in the sqlitePlugin.openDatabase call, as I have documented. The cordova-sqlite-express-build-support plugin version always works as if this setting were used on Android.

I noticed that you tried paging someone by editing a comment, which I am not so sure will work on GitHub, so I will page him here - @christocracy

**Comment by shamilovtim** [comment]
Thanks @brodybits. It looks like `androidDatabaseProvider: 'system'` did not provide a resolution. I'll continue to investigate whether a PR could solve this situation or whether there's something else that could keep the SQLite db awake in the background.
