### ISSUE TITLE
Ionic Appflow won't build v1 app any more

### ISSUE THREAD

**Issue by prober996** [brody2consult/cordova-sqlite-storage#859]
Ionic AppFlow throws this error:  

> Failed to install 'cordova-sqlite-storage': CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

I have built the app many times but something changed in the Ionic platform that now causes this error.  Any ideas on how to "add this module to your dependencies and use regular "require" to load it."?

**Comment by prober996** [comment]
I think that this error comes about because AppFlow now uses Cordova CLI 9.0.3.  Previous builds were done with 8.0.0.  Does anyone else have this problem?  Any ideas on how to "add this module to your dependencies and use regular "require" to load it."?

**Comment by fonini** [comment]
Same issue here

**Comment by prober996** [comment]
I just resolved this by changing the config.xml file: 
  
`<plugin` name="cordova-sqlite-storage" spec="^3.2.0" />

App then built correctly and is is running on both iOS and Android devices.

**Comment by prober996** [comment]
See #856 for more on this topic
