### ISSUE TITLE
Conflicting use of this plugins PSPDFThreadSafeMutableDictionary class with PSPDFKit library

### ISSUE THREAD

**Issue by corran2go** [brody2consult/cordova-sqlite-storage#861]
Hi,
first of all, thanks for providing this cordova plugin and all the work related to keep it up-to-date.

I'm having an issue in a cordova app which also includes the commercial PSPDFKit. So Xcodes gives the following warning for a class you seemed to habe copied from PSPDFKit:

`objc[892]: Class PSPDFThreadSafeMutableDictionary is implemented in both /private/var/containers/Bundle/Application/xxx/My.app/Frameworks/PSPDFKit.framework/PSPDFKit (0x106b24198) and /var/containers/Bundle/Application/xxx/My.app/My (0x10532cdf0). One of the two will be used. Which one is undefined.`

Would it be possible to resolve this issue and release a bugfix release?

Thanks,
Steffen

**Comment by brody2consult** [comment]
I would likely fix this in a major release, maybe at the same time as #868 (build issue with cordova-plugin-file) & #867 (SQLite 3.28.0 security release).

**Comment by brody2consult** [comment]
Should be fixed now, see 7290f57d748bd1e1cfe688a36626fb16bbc93247
