### ISSUE TITLE
"insert or replace into" in ios not work

### ISSUE THREAD

**Issue by huangzida** [brody2consult/cordova-sqlite-storage#871]
INSERT OR REPLACE INTO issue_list(id unique, value) VALUES (?1, ?2)
In android it update the row success,but ios not update.

**Comment by azn1viet** [comment]
Have you fixed the issue? I got the same. INSERT OR REPLACE INTO is working in Chrome but not iOS. It does not update the records.

**Comment by maswerdna** [comment]
I think I'm having the same issue with 'INSERT OR IGNORE INTO'
