### ISSUE TITLE
For no rhyme or reason, I'll suddenly get "no such table" errors

### ISSUE THREAD

**Issue by willnix86** [brody2consult/cordova-sqlite-storage#878]
Issue occurs on iOS.

Everything will be going perfectly fine. Database will be loaded and populated from an sql file in the project's root directory. I can update the app / reinstall it, do whatever I like and it'll run as it should.

Then, at some point, it'll decide that it doesn't want to work any longer and I'll receive "no such table" errors. I'll revert commits to the latest working ones. Switch branches to ones that definitely worked. I'll undo everything to where it was working before. And yet.

No such table.

Here are the plugins and dependencies we're using. None of this is new or different to when the sql plugin was working. It literally makes zero sense to me! Same error on emulated device and physical device

**    "plugins": {
      "cordova-plugin-device": {},
      "cordova-plugin-dialogs": {},
      "cordova-plugin-file": {},
      "cordova-plugin-globalization": {},
      "cordova-plugin-device-orientation": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-appavailability": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-zip": {},
      "cordova-plugin-x-socialsharing": {
        "ANDROID_SUPPORT_V4_VERSION": "26.+"
      },
      "com.darktalker.cordova.screenshot": {},
      "cordova-plugin-google-analytics": {
        "GMS_VERSION": "11.0.1"
      },
      "cordova-android-play-services-gradle-release": {
        "PLAY_SERVICES_VERSION": "11.+"
      },
      "cordova-android-firebase-gradle-release": {
        "FIREBASE_VERSION": "11.+"
      },
      "cordova-custom-config": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-firebase": {},
      "cordova-support-google-services": {},
      "cordova-android-support-gradle-release": {
        "ANDROID_SUPPORT_VERSION": "26.+"
      },
      "cordova-sqlite-storage": {}
    }
  },
  "dependencies": {
    "acorn": "^6.1.1",
    "add": "^2.0.6",
    "android-versions": "^1.2.1",
    "com.darktalker.cordova.screenshot": "git+https://github.com/gitawego/cordova-screenshot.git",
    "cordova-android": "6.4.0",
    "cordova-android-firebase-gradle-release": "^3.0.0",
    "cordova-android-play-services-gradle-release": "^3.0.0",
    "cordova-android-support-gradle-release": "^3.0.0",
    "cordova-browser": "^5.0.1",
    "cordova-custom-config": "^5.1.0",
    "cordova-ios": "5.0.1",
    "cordova-plugin-appavailability": "^0.4.2",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-device-orientation": "^1.0.7",
    "cordova-plugin-dialogs": "^1.3.4",
    "cordova-plugin-file": "^4.3.3",
    "cordova-plugin-firebase": "^2.0.5",
    "cordova-plugin-globalization": "^1.11.0",
    "cordova-plugin-google-analytics": "^1.8.6",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.4.4",
    "cordova-plugin-zip": "^3.1.0",
    "cordova-sqlite-storage": "^3.2.0",
    "cordova-support-google-services": "^1.3.1",
    "es6-promise-plugin": "^4.2.2",
    "node-zip": "^1.1.1",
    "plugin": "^0.3.3",
    "xml2js": "^0.4.19"
  },
  "devDependencies": {
    "br_config": "./www/libs/br_config",
    "node-sass": "^4.12.0",
    "phonegap": "8.2.2",
    "rimraf": "^2.6.3"
  }
}**

**Comment by brody2consult** [comment]
To receive help, please give some more information about how the tables are created, how the tables may be modified, etc. Especially important is that all sqlite access code must wait for the `deviceready` event, otherwise it may be flakey behavior. This can be especially tricky on Angular and Ionic.

**Comment by willnix86** [comment]
It's working again now... couldn't tell you why! haha
