### ISSUE TITLE
Database path change on db store using android 9

### ISSUE THREAD

**Issue by mikulifourtechnolab** [brody2consult/cordova-sqlite-storage#883]
@brodybits 

I found that problem with **android 9** device, creating new database path to save DB on any operation 

I using 
**Cordova version : 6.4.0**
**Cordova-android : 6.1.0**

I used database call function 
 window.sqlitePlugin.openDatabase({ name: 'testdatabase', location: 'default' }, function (db) { })

![123](https://user-images.githubusercontent.com/23360587/61038284-62656e00-a3ea-11e9-8c67-1f7f145a0f0c.png)

How can my data store to my old database location folder (Location : "databases")

I also check below **android 9** version and check db path (Location : "databases")
but **change path using android 9** 

Can you please help me out ?

**Comment by shahramSo** [comment]
I encountered with same issue on Android 9 device under Ionic 4 project.

**Comment by brody2consult** [comment]
This plugin always uses the same database location on Android.
