### ISSUE TITLE
Plugin not working...

### ISSUE THREAD

**Issue by TomTruyen** [brody2consult/cordova-sqlite-storage#889]
I use Visual Studio 2017 with cordova app on it and I installed this plugin using the config.xml inside that project exactly the same way as I have installed other core plugins of cordova but for some reason this one doesn't work. When I try to open a connection it just says the following: "Uncaught TypeError: Cannot read property 'openDatabase' of undefined". Now I have come to the conclusion that it has something to do with it not being installed properly but I can't seem to find out why, as other plugins do work by installing the exact same way. I have tested it on the built in emulator (which uses chrome) and on my phone: Samsung Galaxy A8 (android version 9). Doesn't work on both...

**Comment by TomTruyen** [comment]
also I used the code from documentation which I copy pasted so it's not a typo or something. Is there maybe another way to install the plugin

**Comment by AubreyHewes** [comment]
Create a new cordova project and add the plugin via `cordova plugin add X` then use the plugin..
Does this wok?

If you have only "changed" the config.xml and not installed or prepared this may be the reason the plugin is not "available".
Without knowing what your steps (_exactly the same way as I have installed other core plugins of cordova_) it is hard to say why the plugin is not available. 

If you are doing everything correctly then how are you calling the method `openDatabase`? Show the code-line?

The minimal you can do is share a (dummy) project that is failing.. this way others may be able to reproduce your error and possibly help you...

In a new project I can not reproduce your problem... all works as intended...

**Comment by brody2consult** [comment]
A minimal, reproducible example is needed, see the following resource: https://stackoverflow.com/help/minimal-reproducible-example

Thanks @AubreyHewes for the extended response.

Commercial support is also available from: https://xpbrew.consulting/
