### ISSUE TITLE
pre-populate Issue/529

### ISSUE THREAD

**Issue by fernandoralha** [brody2consult/cordova-sqlite-storage#899]
Hi, has this matter been resolved?
https://github.com/xpbrew/cordova-sqlite-storage/issues/529
What is the solution for Ionic 4?

**Comment by brody2consult** [comment]
Answered in #529.

In terms of Ionic, I would *highly* recommend you consider using Ionic with Capacitor framework since they seem to work together more cohesively. I have seen way too many issues between Ionic and Cordova to recommend using them together now.
