### ISSUE TITLE
iOS: OPEN database: mydb.db FAILED, aborting any pending transactions

### ISSUE THREAD

**Issue by bastifix** [brody2consult/cordova-sqlite-storage#903]
Hi!
I used the plugin with pleasure so far ;-)
Unfortunately I'm now not able to open my db anymore.
I'm getting this error:

`OPEN database: mydb.db FAILED, aborting any pending transactions`

If I open a new simulator and do a clean start a new database is created without a problem. But I need to use the existing to use my data stored in there. So it seems to be a location problem. My current database is located in Library/LocalDatabase. I tried to get there by using
`iosDatabaseLocation: 'Library/LocalDatabase'`
but the error is still the same.

Can you please help me? - I tried for days now

**Comment by bastifix** [comment]
The problem was the connection between sqlcipher and sqlite: In a previous version sqlcipher-adapter 0.2.1 worked with sqlite-adapter 3.0.0 without a problem. I get it working now with sqlcipher-adapter 0.1.12-rc3 and sqlite-adapter 3.3.0. I'm not really getting it why the problem wasn't there and then appeared from nothing, but I'm happy it works so far right now.

**Comment by valery-lavrik** [comment]
@bastifix    hi!  faced the same problem!
Please explain in more detail what exactly you did to fix the problem

**Comment by bastifix** [comment]
Just use Sqlcipher like
   ` "cordova-sqlcipher-adapter": "^0.2.1",`
an no `sqlite-adapter` at all
