### ISSUE TITLE
JOIN table with view crash

### ISSUE THREAD

**Issue by brody2consult** [brody2consult/cordova-sqlite-storage#905]
http://sqlite.1065341.n5.nabble.com/A-crash-bug-in-sqlite-tc109917.html

At this point I have reproduced this crash on SQLite3 build from crash, outside of this plugin.

possibly related to #904

**Comment by julientype** [comment]
this is the SQL statement over error.....
CREATE TABLE v0 ( v2 DOUBLE CHECK( ( v2 IN ( v2 , v1) ) ) , v1 UNIQUE AS( v2 > v2 ) ) ;
INSERT INTO v0 VALUES ( 10 );
SELECT v0 . v1 , v0 . v1 FROM v0 JOIN v0 USING ( v1 , v1) ;

====  USING   and  JOIN=====
CREATE TABLE ccc(addr, text);
CREATE VIRTUAL TABLE ccc_fts USING fts4(addr, text, content=ccc);

https://www.sqlite.org/rbu.html#using_rbu_with_fts3_4_tables

**Comment by julientype** [comment]
-- At line 1:
CREATE TABLE v0 ( v2 DOUBLE CHECK( ( v2 IN ( v2 , v1) ) ) , v1 UNIQUE AS
-- Result: near "AS": syntax error
then you get error in next transaction no table... and the final transaction....

the problem is you corrupted the db-journal 
solution would be to delete  the db-journal and open the database...
may fix it...   like kill  the  db-journal temp file before opening a connection and you get a new copy
db-journal <---- is where roll backs work off..... 
with a corrupt db-journal your database will not run..... like a bad json file....

**Comment by julientype** [comment]
The rollback journal is usually created when a transaction is first started and is usually deleted when a transaction commits or rolls back. The rollback journal file is essential for implementing the atomic commit and rollback capabilities of SQLite. Without a rollback journal, SQLite would be unable to rollback an incomplete transaction, and if a crash or power loss occurred in the middle of a transaction the entire database would likely go corrupt without a rollback journal.

https://stackoverflow.com/questions/26209091/what-is-the-journal-sqlite-database-in-android

when i create a database it puts in journal file....<----this is where you get data base corruptions
https://www.sqlite.org/pragma.html#pragma_journal_mode

**Comment by julientype** [comment]
whats the better journal mode  
DELETE vs PERSIST
replacing a database  ..... in an android app.....  
PERSIST  is for mass request like a web server.... and you want to avoid io calls....
DELETE ends the journal.... only one file to replace yet more io calls......
PERSIST is 2 files operation ........ do you really want 2 files???? taking up space on an android device...
where you want to run add replace and move database....... with limited space....
ohh new app upgrade ..... or you want to share database files.... 
its easy to see how a database will get corrupted.....

**Comment by brody2consult** [comment]
I think a lot of these questions should be answered by the SQLite team itself.

I am using the default journal mode which is DELETE. Exception is if you open database with `androidDatabaseImplementation: 'system' ` setting in which case this is under control of the built-in Android SQLite library.

In general I will just use the releases as they are published on sqlite.org.
