### ISSUE TITLE
Is there anyway to get this plugin to continuously update a db row in the background 

### ISSUE THREAD

**Issue by Ayoitswiz** [brody2consult/cordova-sqlite-storage#909]
Hello,

I'm using @mauron85/cordova-plugin-background-geolocation in conjunction with this plugin. I've managed to get the app to run in the background, and update to the console every second with an incrementing value. That will run forever, but I'm also trying to update the db with that incrementing value. The db does update in the background but only for about 160-230 seconds.

It's weird that it seems to stop updating at infrequent times. Is there any way to get sqlite to update in the background until the app is killed by the user?
If not, is there a different option I could use to store my info? I only need to do two update statements in the background that update one row each every couple mins or so.

I've seen #857 which seems to be dealing with the same issue but no solution was found. However that was a year ago and I'm really just trying to find any solution even if it doesn't deal with sqlite. A simple push in the right direction would be very helpful as well.

**Comment by brody2consult** [comment]
I have no plans to support this kind of thing in this plugin. Please see my further comments in #857.
