### ISSUE TITLE
database.db file is not encrypting / asking for pass key while browsing database in DBBrowser

### ISSUE THREAD

**Issue by ParagShinde** [brody2consult/cordova-sqlite-storage#910]
I tried exporting database.db file from android device and import in SQLite DB browser it was asking me previously for password key before importing database but now it is not asking .I tried creating new project and test on it ,the result is same.
following is my code to set password key for SQLite 
`openDB() {
        return new Promise((resolve, reject) => {
            if (!this.db) {
                this.sqlite
                    .create({
                        name: "database.db",
                        location: "default",
                        key: "abc"
                    })
                    .then((db: SQLiteObject) => {
                        this.db = db;
                        resolve(this.db);
                    });
            } else {
                resolve(this.db);
            }
        });
    }`

**Comment by brody2consult** [comment]
This plugin does not include encrypting.
