### ISSUE TITLE
.db location

### ISSUE THREAD

**Issue by ghost** [brody2consult/cordova-sqlite-storage#912]
How to get the db file from android devices after installing the cordova app. Because I didnt find the package name or my app name in android/data folder

**Comment by ghost** [comment]
How to get the .db file from android devices after installing the Cordova app. Because I didn't find the package name or my app name in android/data folder...
Can you help me out, please..

**Comment by brody2consult** [comment]
My understanding is that the standard app Databases folder is hidden by the Android OS as a security feature. This was discussed before, I forget where now. I think this needs to be documented as a pitfall.

**Comment by AgDude** [comment]
You can get the file like this:
```
$window.resolveLocalFileSystemURL(cordova.file.applicationStorageDirectory + '/databases/my_database.db, function(file){ ... })
```
