### ISSUE TITLE
Display insert error

### ISSUE THREAD

**Issue by tiagocaus** [brody2consult/cordova-sqlite-storage#915]
How do I get the insert error?
I am unable to insert data into the table. So I would like to know how to catch the error to identify it.

I'm doing this:
````
db.transaction(function (tx) {
     tx.executeSql("INSERT INTO clientes (ID, nomeEmpresa) VALUES (?, ?)", [ID, nomeEmpresa] );
});
````

How to modify to display the error in console.log ()?

**Comment by brody2consult** [comment]
How to catch the error in an error callback is already documented.
