### ISSUE TITLE
Project confusion

### ISSUE THREAD

**Issue by Maikell84** [brody2consult/cordova-sqlite-storage#916]
Can someone explain me the difference between the cordova SQLite plugins?

- Here we have [cordova-sqlite-evcore-extbuild-free](https://github.com/brodysoft/cordova-sqlite-evcore-extbuild-free) by **brodysoft**. Written and maintained by Christopher J. Brody
- Then we have [cordova-sqlite-ext](https://github.com/brodybits/cordova-sqlite-ext) by **brodybits**. Written and maintained by Christopher J. Brody
- And of course we have this one [cordova-sqlite-storage](https://github.com/xpbrew/cordova-sqlite-storage) by **xbrew**. Written and maintainedby Christopher J. Brody

I probably forgot some...
On first look all plugins look more or less the same and I can use them with the same code.

- **Why are there so many variations of this plugin?**
- **What are the differences?**
- **Is there somewhere documented which version I should use for my project?**

**Comment by brody2consult** [comment]
I just added a table near the beginning of the documentation with a comparison of supported plugin versions. In general I would appreciate this kind of question in <https://github.com/litehelpers/Cordova-sqlite-help/issues> or <https://github.com/brodybits/ask-me-anything/issues>.
