### ISSUE TITLE
Browser support dropped?

### ISSUE THREAD

**Issue by jasonsultana** [brody2consult/cordova-sqlite-storage#918]
On Safari I'm getting "Web SQL is deprecated". 
On Chrome I'm getting "Unable to read version (1 WebKitDatabaseInfoTable__ doesn't exist)" (as of the latest Chrome version).

Is anyone else noticing this? It looks like Web SQL is pretty much unsupported at this stage. Any browser alternatives?

**Comment by brody2consult** [comment]
That makes sense. Using SQL.js is the recommended solution.

In terms of a "portable" solution for browser and mobile platforms, I would like to support the Cordova browser platform in the plugin redesign already started as discussed in <https://github.com/brodybits/ask-me-anything/issues/3>.

**Comment by brody2consult** [comment]
Browser platform support was added as documented, closing now.
