### ISSUE TITLE
select query where clause

### ISSUE THREAD

**Issue by Naberdz** [brody2consult/cordova-sqlite-storage#919]
The following query returns 0 rows
```
    database.transaction(function(transaction){
        transaction.executeSql('SELECT * FROM table WHERE field='+value,[], function(ignored, result){
            console.log(result.rows.length);
        });
    }, function(error) {
        console.log('Transaction ERROR: ' + error.message);
    }, function() {
        console.log('Read floors OK');
    });
```

tried following: 
`transaction.executeSql('SELECT * FROM table WHERE field=?;',[value], function(ignored, result){`
same result 0 rows.

if i use 
`transaction.executeSql('SELECT * FROM table',[], function(ignored, result){`
i get all records back. 

ofcourse i could add check if filed is equals value as post processing but if we have 1000 records it will be really slow.

**plugin version: cordova-sqlite-storage 4.0.0 
tested on android 10.**

**Comment by brody2consult** [comment]
[minimal, reproducible example ([1])](https://stackoverflow.com/help/minimal-reproducible-example) is needed

please ask in <https://github.com/xpbrew/cordova-sqlite-storage-help/issues>

thanks

[1] https://stackoverflow.com/help/minimal-reproducible-example
