### ISSUE TITLE
sqlite does not erase when uninstalling app

### ISSUE THREAD

**Issue by tiagocaus** [brody2consult/cordova-sqlite-storage#920]
I have a problem.
When I uninstall the app and then install it again, I notice that it is still loading old files.

When uninstalling the APP, you should delete everything, including the database, correct?

Am I doing something wrong?

My code is this:

````
var db;

try {
    document.addEventListener('deviceready', function() {
        db = window.sqlitePlugin.openDatabase({name: 'database.db', location: 'default'}, function(db) {});
    });
    console.log("SQLITE OK");
}catch (err) {
    alert('Erro:' + err);
}
````

**Comment by brody2consult** [comment]
Already discussed in pinned issue #612
