### ISSUE TITLE
Please redirect the deprecated repos to this one

### ISSUE THREAD

**Issue by nolanlawson** [brody2consult/cordova-sqlite-storage#95]
As an end-user, when I search for some variant of "sqlite plugin" on Google, I might see up to three other results:
- https://github.com/chbrody/Cordova-SQLitePlugin
- https://github.com/brodyspark/PhoneGap-SQLitePlugin-Android
- https://github.com/lite4cordova/Cordova-SQLitePlugin

Some of them even link to each other, meaning it takes me several clicks to get to the right repo!  As a contributor, it took me a long time to even figure out which repo was "the" SQLite Plugin. (I had to ask around on IRC.) For end-users, I can't imagine what they make of it.

Please [transfer ownership](https://help.github.com/articles/how-to-transfer-a-repository) of these repos to the brodysoft org.  If you need a reference implementation, you can use a branch or a tag.

It's a much better experience for end-users, since they'll get a 301 redirect to the current repo.  Plus, Google will only show 1 result instead of 4.

**Comment by brody2consult** [comment]
The following old links are now redirected to https://github.com/litehelpers/Cordova-sqlite-legacy:
- https://github.com/chbrody/Cordova-SQLitePlugin
- https://github.com/lite4cordova/Cordova-SQLitePlugin
- https://github.com/brodyspark/PhoneGap-SQLitePlugin-Android
- https://github.com/brodyspark/PhoneGap-SQLitePlugin-iOS
- https://github.com/pgsqlite/PG-SQLitePlugin-Android
- https://github.com/pgsqlite/PG-SQLitePlugin-iOS

**Comment by nolanlawson** [comment]
Thank you!! :)
