### ISSUE TITLE
UnsatisfiedLinkError when opening SQLite storage

### ISSUE THREAD

**Issue by NLueg** [brody2consult/cordova-sqlite-storage#993]
Hi there, I recently published a version of our ionic-app with the sqlite plugin.
It works pretty well for most users but there are currently a few devices that crash because of the exception below.
I created an issue for the `@ionic/storage` plugin, but they said that it's probably an issue of this plugin. https://github.com/ionic-team/ionic-storage/issues/210

- Galaxy S8 (Android 9)
- Pixel 3 XL (Android 9)
- Nexus 5X (Android 8)
....

![image](https://user-images.githubusercontent.com/48101693/107634314-9f9a7d80-6c69-11eb-9aa3-feacaedaf6b3.png)

**Comment by dherrero99** [comment]
Same issue.

`Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "...==/base.apk"],nativeLibraryDirectories=[...==/lib/x86_64, /system/lib64, /system/vendor/lib64]]] couldn't find "libsqlc-ndk-native-driver.so"
`

**Comment by juanmaldonadodev** [comment]
Same issue here. Any progress on this?

**Comment by andrerds** [comment]
Hey, I'm also getting the same error, any update?

**Comment by brody2consult** [comment]
Looks to me like a build issue, needs a minimal reproduction ref:

- https://stackoverflow.com/help/minimal-reproducible-example

**Comment by NLueg** [comment]
I just moved away from https://github.com/thgreasi/localForage-cordovaSQLiteDriver to connect to the database which solved the issue. I created my own plugin where I don't experience this issue anymore: https://github.com/NLueg/localforage-cordova-sq-lite-driver

The issue can be closed here as this plugin is not the cause of the issue.

**Comment by pinguluk** [comment]
I have the same problem with Pixel 3 XL and Moto G73 5G

**Comment by Carlosps** [comment]
@NLueg Can you elaborate more why this plugin is not the cause of this issue?

Has anyone found a solution for this?

**Comment by NLueg** [comment]
@Carlosps actually I can't tell you more. The issue disappeared after I stopped using `localForage-cordovaSQLiteDriver` and developed it by myself. After like one year of working I decided to publish it to make it easier for other people to solve the problem.
But I don't know the exact thing that this exception.

**Comment by juanmaldonadodev** [comment]
I have created a discussion in capacitor-community/sqlite repository. I think that if localForage-cordovaSQLiteDriver is not a good idea to continue using it.
